/**
 * Generated by quail.
 *
 * Clipboard-paste baseline for https://www.ing.nl/particulier. When the page exposes a
 * text input, asserts pasting HTML-formatted content into a plain
 * text field is sanitized — the field accepts the text, the page
 * does not eval or render the HTML as live markup (an XSS vector).
 * Emitted only when probe detected a text-like input.
 *
 * Filter: `npx playwright test --grep @kind:clipboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — clipboard @ https://www.ing.nl/particulier', () => {
  test('pasting HTML-like content into a text field does not execute scripts (XSS mitigation)', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
    await page.goto('/particulier', { waitUntil: 'domcontentloaded' })
    const input = page.locator('input[type="text"], input[type="search"], input:not([type]), textarea').first()
    if (await input.count() === 0) test.skip()
    await input.focus()
    // Paste a payload containing HTML and an inline script to test sanitization.
    const payload = '<img src=x onerror="window.__pasteXSS=true" />HELLO'
    await input.evaluate((el, p) => {
      const event = new ClipboardEvent('paste', {
        clipboardData: new DataTransfer(),
        bubbles: true,
      })
      event.clipboardData!.setData('text/html', p)
      event.clipboardData!.setData('text/plain', p)
      el.dispatchEvent(event)
      ;(el as HTMLInputElement).value = p
    }, payload)
    // Result must contain the literal text; script must not have executed.
    const value = await input.inputValue()
    expect(value).toContain('HELLO')
    const xssFired = await page.evaluate(() => (window as any).__pasteXSS === true)
    expect.soft(xssFired, 'paste fired inline script — XSS vulnerability').toBe(false)
  })
})
