/**
 * Generated by quail.
 *
 * Clipboard-paste safety check: ensures that when pasting HTML-like content into a text field on the page, the HTML is not executed — preventing XSS. Only runs if a text input is found.
 *
 * Filter: `npx playwright test --grep @kind:clipboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — clipboard @ https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen', () => {
  test('paste of HTML content into text field does not execute scripts', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    const input = page.locator('input[type="text"], input[type="search"], input:not([type]), textarea').first()
    if (await input.count() === 0) test.skip()
    await input.focus()
    // Paste HTML (with inline script) using clipboard event — simulates user paste action.
    const payload = '<img src=x onerror="window.__pasteXSS=true" />HELLO'
    await input.evaluate((el, p) => {
      const event = new ClipboardEvent('paste', {
        clipboardData: new DataTransfer(),
        bubbles: true,
      })
      event.clipboardData!.setData('text/html', p)
      event.clipboardData!.setData('text/plain', p)
      el.dispatchEvent(event)
      ;(el as HTMLInputElement).value = p
    }, payload)
    // Verify pasted text is preserved and script does not run.
    const value = await input.inputValue()
    expect(value).toContain('HELLO')
    const xssFired = await page.evaluate(() => (window as any).__pasteXSS === true)
    expect(xssFired, 'script ran on paste — possible XSS').toBe(false)
  })
})
