/**
 * Generated by quail.
 *
 * Clipboard-paste baseline for https://www.ing.nl/zakelijk. When the page exposes a
 * text input, asserts pasting HTML-formatted content into a plain
 * text field is sanitized — the field accepts the text, the page
 * does not eval or render the HTML as live markup (an XSS vector).
 * Emitted only when probe detected a text-like input.
 *
 * Filter: `npx playwright test --grep @kind:clipboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — clipboard @ https://www.ing.nl/zakelijk', () => {
  test('paste HTML content into text field is sanitized', async ({ page, context }) => {
    await context.grantPermissions(['clipboard-read', 'clipboard-write']).catch(() => {})
    await page.goto('/zakelijk', { waitUntil: 'domcontentloaded' })
    const input = page.locator('input[type="text"], input[type="search"], input:not([type]), textarea').first()
    if (await input.count() === 0) test.skip()
    await input.focus()
    // Simulate paste of a content with an HTML payload + an inline
    // script. Real clipboard APIs vary by OS; we use evaluate to
    // dispatch a paste event the page can intercept.
    const payload = '<img src=x onerror="window.__pasteXSS=true" />HELLO'
    await input.evaluate((el, p) => {
      const event = new ClipboardEvent('paste', {
        clipboardData: new DataTransfer(),
        bubbles: true,
      })
      event.clipboardData!.setData('text/html', p)
      event.clipboardData!.setData('text/plain', p)
      el.dispatchEvent(event)
      ;(el as HTMLInputElement).value = p
    }, payload)
    // The value should contain the literal text, NOT have executed the script.
    const value = await input.inputValue()
    expect(value).toContain('HELLO')
    const xssFired = await page.evaluate(() => (window as any).__pasteXSS === true)
    expect.soft(xssFired, 'script did not execute (no XSS)').toBe(false)
  })
})
