// Generated by reviewqa. Playwright configuration with sensible defaults
// for the suite reviewqa just probed. `baseURL` defaults to the origin
// reviewqa probed; override with `BASE_URL=...` to point the same suite
// at staging, a PR preview, or localhost.
//
// playwright-bdd is wired in: .feature files under tests/e2e/features/
// become the executable contract via step definitions in
// tests/e2e/steps/. Plain Playwright TS specs (api/*.api.spec.ts and
// *-fuzz.spec.ts) still run alongside them as a second project.
//
// Edit freely — the next probe run will not overwrite this file.
import { defineConfig, devices } from '@playwright/test'
import { defineBddConfig } from 'playwright-bdd'

const BASE_URL = process.env.BASE_URL ?? 'https://books.toscrape.com'

const bddTestDir = defineBddConfig({
  features: 'tests/e2e/features/*.feature',
  steps: 'tests/e2e/steps/*.ts',
})

export default defineConfig({
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI ? [['html', { open: 'never' }], ['list']] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 20_000,
  },
  projects: [
    {
      name: 'bdd',
      testDir: bddTestDir,
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'extras',
      testDir: './tests/e2e',
      testMatch: /\.(api|fuzz)\.spec\.ts$/,
      use: { ...devices['Desktop Chrome'] },
    },
  ],
})
