/**
 * Generated by quail.
 *
 * Health / readiness probe smoke for https://www.ing.nl. Hits the well-known
 * health endpoints and asserts at least one responds 2xx. Sites that
 * expose none of them produce a soft warning — the spec doesn't fail
 * because not having a health endpoint is a valid choice.
 *
 * Filter: `npx playwright test --grep @kind:health`
 */
import { test, expect } from '@playwright/test'

const HEALTH_PATHS = ['/health', '/healthz', '/ready', '/readyz', '/status', '/livez']

test.describe.configure({ mode: 'parallel' })
test.describe('Ing health probes @ https://www.ing.nl', () => {
  test('@kind:health @smoke verifies at least one well-known health endpoint returns 2xx', async ({ request }) => {
    const results: Array<{ path: string; status: number }> = []
    for (const path of HEALTH_PATHS) {
      try {
        const url = new URL(path, 'https://www.ing.nl').toString()
        const r = await request.get(url, { timeout: 5_000, maxRedirects: 0 })
        results.push({ path, status: r.status() })
      } catch (e) {
        results.push({ path, status: -1 })
      }
    }
    console.log('health probe results', results)
    const anyHealthy = results.some(r => r.status >= 200 && r.status < 300)
    if (!anyHealthy) console.log('no well-known health endpoint returned 2xx — consider exposing /health or /healthz')
    expectSoft(anyHealthy, 'no health endpoint returned 2xx').toBe(true)
    // Hard fail only if ALL probes errored (e.g., network down); 404s are valid.
    const allErrored = results.every(r => r.status === -1)
    expect(allErrored, 'all health probes errored — origin likely unreachable?').toBe(false)
  })
})
