/**
 * Generated by quail.
 *
 * Verifies health/readiness by hitting standard endpoints on https://www.ing.nl; passes if at least one returns 2xx. A site without any endpoints yields only a soft warning, as omitting health endpoints is valid per spec.
 *
 * Filter: `npx playwright test --grep @kind:health`
 */
import { test, expect } from '@playwright/test'

const HEALTH_PATHS = ['/health', '/healthz', '/ready', '/readyz', '/status', '/livez']

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — health probes on https://www.ing.nl', () => {
  test('@kind:health @smoke — at least one well-known health endpoint responds', async ({ request }) => {
    const results: Array<{ path: string; status: number }> = []
    for (const path of HEALTH_PATHS) {
      try {
        const url = new URL(path, 'https://www.ing.nl').toString()
        const r = await request.get(url, { timeout: 5_000, maxRedirects: 0 })
        results.push({ path, status: r.status() })
      } catch (e) {
        results.push({ path, status: -1 })
      }
    }
    console.log('Health probe results:', results)
    const anyHealthy = results.some(r => r.status >= 200 && r.status < 300)
    if (!anyHealthy) {
      console.log('No well-known health endpoint responded 2xx — consider exposing /health or /healthz')
    }
    expect.soft(anyHealthy, 'No health endpoint responded 2xx').toBe(true)
    // Fails hard only if ALL probes errored (e.g., network down), since 404s are acceptable.
    const allErrored = results.every(r => r.status === -1)
    expect(allErrored, 'All health probes errored — origin unreachable?').toBe(false)
  })
})
