/**
 * Generated by quail.
 *
 * Storage resilience for https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen. Asserts the page handles
 * corrupt or absent localStorage / sessionStorage / cookies without
 * blank-screening. Storage-corruption bugs are a frequent cause of
 * "works on my machine" support tickets — covering them deterministic-
 * ally lifts production reliability.
 *
 * Filter: `npx playwright test --grep @kind:storage`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — resilience when storage is missing or corrupted @ https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen', () => {
  test('@kind:storage @smoke page renders correctly when storage is empty', async ({ page, context }) => {
    await context.clearCookies()
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear() } catch {} })
    await page.reload()
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })

  test('@kind:storage @corrupt page handles invalid data in storage without breaking', async ({ page }) => {
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => {
      try {
        localStorage.setItem('user', '{not_json_at_all}')
        sessionStorage.setItem('theme', '\x00\x01\x02')
      } catch {}
    })
    await page.reload()
    // Page should still render — a JSON.parse exception on app boot
    // surfaces here as a missing h1.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})
