/**
 * Generated by quail.
 *
 * Ensures the page loads reliably even when localStorage, sessionStorage, or cookies are missing or corrupted, preventing blank screens—these bugs commonly cause "works on my machine" issues, and covering them improves production stability.
 *
 * Run with: `npx playwright test --grep @kind:storage`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — storage resilience (@ https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen)', () => {
  test('@kind:storage @smoke verifies page renders with empty storage', async ({ page, context }) => {
    await context.clearCookies()
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear() } catch {} })
    await page.reload()
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })

  test('@kind:storage @corrupt verifies page survives garbage in storage', async ({ page }) => {
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => {
      try {
        localStorage.setItem('user', '{not_json_at_all}')
        sessionStorage.setItem('theme', '\x00\x01\x02')
      } catch {}
    })
    await page.reload()
    // Page should still render — a JSON.parse exception on app boot
    // surfaces here as a missing h1.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})
