/**
 * Generated by quail.
 *
 * Storage resilience for https://www.ing.nl/particulier. Asserts the page handles
 * corrupt or absent localStorage / sessionStorage / cookies without
 * blank-screening. Storage-corruption bugs are a frequent cause of
 * "works on my machine" support tickets — covering them deterministic-
 * ally lifts production reliability.
 *
 * Filter: `npx playwright test --grep @kind:storage`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — storage resilience @ https://www.ing.nl/particulier', () => {
  test('@kind:storage @smoke loads correctly when no storage is present', async ({ page, context }) => {
    await context.clearCookies()
    await page.goto('/particulier', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear() } catch {} })
    await page.reload()
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })

  test('@kind:storage @corrupt handles corrupted data in local and session storage', async ({ page }) => {
    await page.goto('/particulier', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => {
      try {
        localStorage.setItem('user', '{not_json_at_all}')
        sessionStorage.setItem('theme', '\x00\x01\x02')
      } catch {}
    })
    await page.reload()
    // Page should still render — throwing an error on JSON.parse during startup shouldn’t break the app
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})
