/**
 * Generated by quail.
 *
 * Verifies the page remains usable when localStorage, sessionStorage, and cookies are missing, empty, or corrupted—preventing blank screens and common "works on my machine" issues.
 *
 * Filter: `npx playwright test --grep @kind:storage`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — storage resilience', () => {
  test('renders with empty storage', async ({ page, context }) => {
    await context.clearCookies()
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear() } catch {} })
    await page.reload()
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })

  test('survives garbage data in storage', async ({ page }) => {
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => {
      try {
        localStorage.setItem('user', '{not_json_at_all}')
        sessionStorage.setItem('theme', '\x00\x01\x02')
      } catch {}
    })
    await page.reload()
    // Page should still render — a JSON.parse exception on app boot
    // surfaces here as a missing h1.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})
