/**
 * Generated by reviewqa.
 *
 * Locale switching smoke for https://petstore3.swagger.io. Only emitted when the
 * crawler detected <link rel="alternate" hreflang> siblings; each
 * locale becomes one test.
 *
 * Asserts: the locale URL responds 2xx, <html lang> matches the
 * expected locale, and the page has a non-empty h1.
 *
 * Filter: `npx playwright test --grep @kind:i18n`
 */
import { test, expect } from '@playwright/test'

type Locale = { lang: string; url: string }

const LOCALES: Locale[] = [
]

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3Swagger — i18n locales', () => {
  // v0.43: always-attempt baseline — <html lang> attribute must be
  // present even when the site exposes no hreflang siblings. Catches
  // the common a11y/SEO regression where lang is dropped during a
  // framework migration.
  test('@kind:i18n @smoke <html lang> attribute is present', async ({ page }) => {
    await page.goto('/')
    const htmlLang = await page.locator('html').getAttribute('lang')
    expect(htmlLang, '<html lang> attribute should be set on every page').not.toBeNull()
    expect((htmlLang || '').trim().length, '<html lang> should be non-empty').toBeGreaterThan(0)
  })

  for (const locale of LOCALES) {
    test(`@kind:i18n @smoke ${locale.lang} variant renders`, async ({ page }) => {
      const response = await page.goto(locale.url)
      expect(response?.status(), `locale ${locale.lang} should respond`).toBeLessThan(400)
      const htmlLang = await page.locator('html').getAttribute('lang')
      // Match by language subtag prefix — "en-US" satisfies an "en"
      // expectation; "es-MX" satisfies "es".
      const expected = locale.lang.split('-')[0].toLowerCase()
      const actual = (htmlLang || '').split('-')[0].toLowerCase()
      expect.soft(actual, `<html lang> should reflect locale ${locale.lang}`).toBe(expected)
      await expect(page.locator('h1').first()).toBeVisible()
    })
  }
})
