# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — read journey
  As a visitor of https://www.spritecloud.com
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/style-guide"
    Then I see the heading "Aa"
    And the page title contains "Style Guide - Healix Webflow website HTML template"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: read — deep-link to the terminal page renders correctly
    Given I open the page "/style-guide"
    Then I see the heading "Aa"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: read — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/style-guide"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:read @priority:nice-to-have @kind:cross-journey
  Scenario: read — switching to landing and back leaves no broken state
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:read @priority:nice-to-have @llm-composed @kind:navigation @model:qwen3-coder-next-latest
  Scenario: Open style guide from home
    Given I open the landing page
    When I click the link to "/style-guide"
    Then the page title contains "Style Guide - Healix Webflow website HTML template"
    Then the main heading reads "Aa"

  @journey:read @priority:nice-to-have @llm-composed @kind:reload @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate style guide directly then reload
    Given I am not signed in
    When I navigate directly to "/style-guide"
    Then the page title contains "Style Guide - Healix Webflow website HTML template"
    When I reload the page
    Then the main heading reads "Aa"

  @journey:read @priority:nice-to-have @llm-composed @kind:navigation @kind:history @model:qwen3-coder-next-latest
  Scenario: Back navigation to landing after style guide
    Given I open the landing page
    When I click the link to "/style-guide"
    Then the page title contains "Style Guide - Healix Webflow website HTML template"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:read @priority:nice-to-have @llm-composed @kind:variant @kind:reload @model:qwen3-coder-next-latest
  Scenario: Reload landing after form submission error
    Given I open the landing page
    When I submit the form without filling any required field
    Then no success message is shown
    When I reload the page
    Then no error message is shown in the form region

