# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: explore journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    And the page title contains "spriteCloud - Penetration Testing"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: explore — deep-link to the terminal page renders correctly
    Given I open the page "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: explore — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/cybersecurity"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @kind:cross-journey
  Scenario: explore — switching to landing and back leaves no broken state
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate to cybersecurity and reload
    Given I open the landing page
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    When I reload the page
    Then I see the heading "Fully Tailored Cybersecurity."

  @journey:explore @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Navigate then go back
    Given I open the landing page
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    When I go back in the browser history
    Then I see the heading "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Direct navigation to cybersecurity page
    Given I am not signed in
    When I navigate directly to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Open cybersecurity page and scroll
    Given I open the landing page
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    When I scroll to the bottom of the page
    Then I remain on the same page

