# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: explore journey completes and lands on the contact page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/contact"
    Then I see the heading "Let's Chat"
    And the page title contains "spriteCloud — Meeting Booking Form"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: deep link to contact page loads successfully
    Given I open the page "/contact"
    Then I see the heading "Let's Chat"

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: back button from contact page returns to landing page
    Given I open the landing page
    When I click the link to "/contact"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @kind:cross-journey
  Scenario: navigating to home and returning preserves page integrity
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region
