# Generated by reviewqa.
#
# Gherkin contract for the research journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — research journey
  As a visitor of https://www.spritecloud.com
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: research journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"
    And the page title contains "Case Study - eCommerce Platform"

  @journey:research @priority:standard @kind:resume
  Scenario: research — deep-link to the terminal page renders correctly
    Given I open the page "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"

  @journey:research @priority:standard @kind:back-button
  Scenario: research — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/case-study-ecomm-platform"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

