# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: explore journey reaches its destination page
    Given I open the homepage
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to the contact page
    Then I see the heading "Let's Chat"
    And the page title contains "spriteCloud — Meeting Booking Form"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: explore — deep-linking to the destination page renders correctly
    Given I navigate directly to the contact page
    Then I see the heading "Let's Chat"

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: explore — using browser back button returns to the landing page
    Given I open the homepage
    When I click the link to the contact page
    When I go back in browser history
    Then the main heading reads "Test your software, not your reputation."
