# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: Spritecloud — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: explore journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/test-automation"
    Then I see the heading "Expert Test Automation Services"
    And the page title contains "Test Automation"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: explore — deep-link to the terminal page renders correctly
    Given I open the page "/test-automation"
    Then I see the heading "Expert Test Automation Services"

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: explore — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/test-automation"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @kind:cross-journey
  Scenario: explore — switching to landing and back leaves no broken state
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Reload after form submission
    Given I am on the landing page
    When I navigate directly to "/test-automation"
    Then the page title contains "Test Automation"
    Then the main heading reads "Expert Test Automation Services"
    When I reload the page
    Then the page title contains "Test Automation"
    Then the main heading reads "Expert Test Automation Services"

  @journey:explore @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Submit form twice rapidly
    Given I am on the landing page
    When I open the menu
    When I click the link to "/contact"
    Then the page title contains "Contact"
    When I submit the form twice in rapid succession
    Then the form is not double-submitted

