# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: SpriteCloud — read journey
  As a visitor of https://www.spritecloud.com
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: Read journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/book-performance-test"
    Then I see the heading "Performance Test"
    And the page title contains "Book - Performance Test"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:read @priority:nice-to-have @llm-composed @kind:happy @model:qwen3-coder-next-latest
  Scenario: View landing page successfully
    Given I open the landing page
    Then the page title contains "spriteCloud"
    Then the main heading reads "Test your software, not your reputation."

  @journey:read @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Navigate to Test Automation page from footer
    Given I open the landing page
    When I click the link to "/test-automation"
    Then the URL contains "/test-automation"
    Then the page title contains "Test Automation"

  @journey:read @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate to Guides via footer
    Given I open the landing page
    When I click the link to "/guides"
    Then the URL contains "/guides"
    Then the page title contains "Guides"
