# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — browse journey
  As a visitor of https://www.spritecloud.com
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/guides"
    And the page title contains "spriteCloud - Your Software Testing and QA partner"
    When I click the link to "/about-us"
    Then I see the heading "Testing is in our DNA."
    And the page title contains "About Us"

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/about-us"
    Then I see the heading "Testing is in our DNA."

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/about-us"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  @journey:browse @priority:standard @kind:cross-journey
  Scenario: browse — switching to landing and back leaves no broken state
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Double form submission
    Given I am on the landing page
    When I navigate directly to "/contact"
    When I submit the form twice in rapid succession
    Then the form is not double-submitted

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate to guides, then reload
    Given I open the landing page
    When I click the link to "/guides"
    Then the page title contains "spriteCloud - Your Software Testing and QA partner"
    When I reload the page
    Then the page title contains "spriteCloud - Your Software Testing and QA partner"

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate to about-us, go back
    Given I am on the landing page
    When I navigate directly to "/about-us"
    Then the main heading reads "Testing is in our DNA."
    When I go back in the browser history
    Then the page title contains "spriteCloud - Test your software, not your reputation!"

