# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — browse journey
  As a visitor of https://www.spritecloud.com
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: user completes the browse flow and lands on the about page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/guides"
    And the page title contains "spriteCloud - Your Software Testing and QA partner"
    When I click the link to "/about-us"
    Then I see the heading "Testing is in our DNA."
    And the page title contains "About Us"

  @journey:browse @priority:standard @kind:resume
  Scenario: deep-link to the about page loads correctly
    Given I open the page "/about-us"
    Then I see the heading "Testing is in our DNA."

  @journey:browse @priority:standard @kind:back-button
  Scenario: browser back button returns user to the landing page
    Given I open the landing page
    When I click the link to "/about-us"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: user scrolls to view all top navigation links
    Given I am on the landing page
    When I scroll to the bottom of the page
    Then the page has at least 10 items

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: user opens the navigation menu
    Given I am on the landing page
    When I open the menu
    Then the main heading reads "Test your software, not your reputation."

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: user closes the navigation menu
    Given I am on the landing page
    When I open the menu
    And I close the menu
    Then no error message is shown in the form region
