# Generated by reviewqa.
#
# Gherkin contract for the research journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — research journey
  As a visitor of https://www.spritecloud.com
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: research journey reaches its final page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I navigate directly to "/case-study-grandvision"
    Then I see the heading "GrandVision"
    And the page title contains "Case Study - GrandVision"

  @journey:research @priority:standard @kind:resume
  Scenario: research — deep-link to the final page renders correctly
    Given I open the page "/case-study-grandvision"
    Then I see the heading "GrandVision"

  @journey:research @priority:standard @kind:back-button
  Scenario: research — back button after navigation returns to landing page
    Given I open the landing page
    When I click the link to "/case-study-grandvision"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:research @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Verify contact link navigation works
    Given I am on the landing page
    When I click the link to "/contact"
    Then the URL contains "/contact"
    Then the page title contains "Contact"

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Check guides navigation from footer works
    Given I open the landing page
    When I click the link to "/guides"
    Then the URL contains "/guides"
    Then I see the heading "Guides"

  @journey:research @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Scroll to view case studies section
    Given I am on the landing page
    When I scroll to the bottom of the page
    Then I scroll into view of the "Case Studies" element
