# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: The explore journey successfully reaches its final page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."
    And the page title contains "spriteCloud - Penetration Testing"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: Deep-linking directly to the cybersecurity page displays it correctly
    Given I open the page "/cybersecurity"
    Then I see the heading "Fully Tailored Cybersecurity."

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: Using the browser back button after navigation returns to the landing page
    Given I open the landing page
    When I click the link to "/cybersecurity"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:explore @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Navigating to the Test Automation page works as expected
    Given I am on the landing page
    When I click the link to "/test-automation"
    Then the URL contains "/test-automation"
    Then the main heading reads "Test your software, not your reputation."

  @journey:explore @priority:nice-to-have @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Visiting the Case Studies page directly loads content correctly
    Given I open the page "/case-studies"
    Then the URL contains "/case-studies"
    Then the page has at least 1 items
