# Generated by reviewqa.
#
# Gherkin contract for the research journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:research
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — research journey
  As a visitor of https://www.spritecloud.com
  I want to complete the research flow
  So that the page delivers on its user goal

  @journey:research @priority:standard @smoke
  Scenario: research journey ends on the expected case study page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/case-study-ecomm-platform"
    Then I see the heading "Performance Testing for an eCommerce Platform"
    And the page title contains "Case Study - eCommerce Platform"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:research @priority:standard @llm-composed @kind:regression @model:qwen3-coder-next-latest
  Scenario: landing page opens with correct title and main heading
    Given I open the landing page
    Then the page title contains "spriteCloud - Test your software, not your reputation!"
    Then the main heading reads "Test your software, not your reputation."
