# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — browse journey
  As a visitor of https://www.spritecloud.com
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its final destination
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/guides"
    And the page title contains "spriteCloud - Your Software Testing and QA partner"
    When I click the link to "/about-us"
    Then I see the heading "Testing is in our DNA."
    And the page title contains "About Us"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: navigate to contact page from landing
    Given I open the landing page
    When I click the link to "/contact"
    Then the URL contains "/contact"

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: verify main heading on landing
    Given I open the landing page
    Then the main heading reads "Test your software, not your reputation."
