# Generated by reviewqa.
#
# Gherkin contract for the explore journey on https://www.spritecloud.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:explore
#   npx playwright test --grep @smoke

Feature: WwwSpritecloudCom — explore journey
  As a visitor of https://www.spritecloud.com
  I want to complete the explore flow
  So that the page delivers on its user goal

  @journey:explore @priority:nice-to-have @smoke
  Scenario: navigating to performance testing shows the expected terminal page
    Given I open the landing page
    And the page title contains "spriteCloud - Test your software, not your reputation!"
    And the main heading reads "Test your software, not your reputation."
    When I click the link to "/performance-testing"
    Then I see the heading "Your Software Put Through its Paces."
    And the page title contains "spriteCloud - Performance Testing"

  @journey:explore @priority:nice-to-have @kind:resume
  Scenario: directly visiting performance testing page displays correctly
    Given I open the page "/performance-testing"
    Then I see the heading "Your Software Put Through its Paces."

  @journey:explore @priority:nice-to-have @kind:back-button
  Scenario: using the back button after navigation returns to the homepage
    Given I open the landing page
    When I click the link to "/performance-testing"
    When I go back in the browser history
    Then the main heading reads "Test your software, not your reputation."
