/**
 * Generated by quail.
 *
 * Network-resilience baseline for https://www.ing.nl/private-banking. Asserts the page
 * survives the failure modes a real user encounters on a poor
 * connection: throttled bandwidth, offline reload, and 429 rate-limit
 * responses. These are common production regressions that pass a
 * happy-path suite — adding them deterministically closes the gap.
 *
 * Filter: `npx playwright test --grep @kind:network`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — network resilience @ https://www.ing.nl/private-banking', () => {
  test('@kind:network @slow-3g page renders under throttled network (1.5s delay)', async ({ page, context }) => {
    // Throttle every request by 1.5s before responding. Page must
    // still render the primary content (h1) within a generous budget.
    await context.route('**/*', async route => {
      await new Promise(r => setTimeout(r, 1500))
      await route.continue()
    })
    await page.goto('/private-banking', { timeout: 60_000 })
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible({ timeout: 30_000 })
  })

  test('@kind:network @offline-reload offline reload shows appropriate error state', async ({ page, context }) => {
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    await context.setOffline(true)
    // The browser raises a navigation error; we capture it and assert
    // the page didn't silently double-render with stale content.
    let errored = false
    try {
      await page.reload({ timeout: 5000 })
    } catch {
      errored = true
    }
    expect.soft(errored, 'expected reload to fail when offline').toBe(true)
    await context.setOffline(false)
  })

  test('@kind:network @rate-limit 429 response is handled without breaking the page', async ({ page, context }) => {
    let calls = 0
    await context.route('**/*', async route => {
      calls++
      if (calls === 1) return route.continue() // allow the initial doc
      // Stub all subsequent fetches as 429 with a Retry-After.
      await route.fulfill({ status: 429, headers: { 'Retry-After': '1' }, body: 'rate limited' })
    })
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    // Even with downstream 429s the initial document should render.
    await expect(page).toHaveURL(/.+/)
  })
})
