# Generated by quail.
#
# Gherkin contract for the browse journey on https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Ing — browse journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Hypotheek berekenen juni 2026 - ING"
    And the main heading reads "Hypotheek berekenen"
    When I click the link to "/particulier"
    And the page title contains "Particulier - ING"
    When I click the link to "/private-banking"
    Then I see the heading "Als je vermogen doorpakt"
    And the page title contains "ING Private Banking | Beste en meest klantgerichte bank van Nederland"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/private-banking"
    Then I see the heading "Als je vermogen doorpakt"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/private-banking"
    When I go back in the browser history
    Then the main heading reads "Hypotheek berekenen"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Click cookie policy link from footer
    Given I open the landing page
    When I click the link to "https://www.ing.nl/de-ing/over-ing/cookies"
    Then the page title contains "Cookies"
    Then the main heading reads "Cookies bij ING"

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Reload page after form interaction
    Given I open the landing page
    When I enter "30" into the "leeftijd" field
    When I reload the page
    Then the "leeftijd" field has the value ""

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Navigate to private banking directly
    Given I open the landing page
    When I navigate directly to "/private-banking"
    Then the page title contains "Private Banking"
    Then the main heading reads "Als je vermogen doorpakt"

  @journey:browse @priority:standard @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Check exit link to particulier page
    Given I open the landing page
    When I click the link to "/particulier"
    Then the page title contains "Particulier"
    Then the URL contains "particulier"
