# Generated by quail.
#
# Gherkin contract for the browse journey on https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Ing — browse journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Hypotheek berekenen juni 2026 - ING"
    And the main heading reads "Hypotheek berekenen"
    When I click the link to "/private-banking"
    Then I see the heading "Als je vermogen doorpakt"
    And the page title contains "ING Private Banking | Beste en meest klantgerichte bank van Nederland"
    When I click the link to "/de-ing/toegankelijkheid"
    Then I see the heading "Toegankelijkheid en hulp bij Bankieren"
    And the page title contains "Toegankelijkheid | ING"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/de-ing/toegankelijkheid"
    Then I see the heading "Toegankelijkheid en hulp bij Bankieren"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/de-ing/toegankelijkheid"
    When I go back in the browser history
    Then the main heading reads "Hypotheek berekenen"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: empty required field submission
    Given I open the landing page
    When I submit the form without filling any required field
    Then no success message is shown
    Then I remain on the same page
    Then no error message is shown in the form region

  @journey:browse @priority:standard @llm-composed @model:qwen3-coder-next-latest
  Scenario: navigate to privacy via link
    Given I open the landing page
    When I click the link to "/particulier/privacy"
    Then the page title contains " privacy"
    Then no error message is shown in the form region
