# Generated by quail.
#
# Gherkin contract for the browse journey on https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Ing — browse journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Hypotheek berekenen juni 2026 - ING"
    And the main heading reads "Hypotheek berekenen"
    When I click the link to "/particulier"
    Then I see the heading "Spaar € 500 of meer en maak kans op fantastische prijzen!"
    And the page title contains "Particulier - ING"
    When I click the link to "/zakelijk"
    Then I see the heading "Op naar je eerste miljoen. Dennis' groei ging in stappen"
    And the page title contains "ING Zakelijk voor ondernemers, bedrijven en organisaties - ING"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/zakelijk"
    Then I see the heading "Op naar je eerste miljoen. Dennis' groei ging in stappen"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/zakelijk"
    When I go back in the browser history
    Then the main heading reads "Hypotheek berekenen"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:browse @priority:standard @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Navigate to particulier, reload, assert heading
    Given I open the landing page
    When I click the link to "/particulier"
    Then the main heading reads "Spaar € 500 of meer en maak kans op fantastische prijzen!"
    When I reload the page
    Then the main heading reads "Spaar € 500 of meer en maak kans op fantastische prijzen!"
