# Generated by quail.
#
# Gherkin contract for the contact journey on https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:contact
#   npx playwright test --grep @smoke

Feature: Ing — contact journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the contact flow
  So that the page delivers on its user goal

  @journey:contact @priority:critical @smoke
  Scenario: contact journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Hypotheek berekenen juni 2026 - ING"
    And the main heading reads "Hypotheek berekenen"
    When I click the link to "/particulier/hypotheek/contact"
    Then I see the heading "Contact"
    And the page title contains "Een gratis oriënterend hypotheekgesprek? Voor nieuwe hypotheken en oversluiten"
    # Form fill + submit (positive path)
    And I submit the form
    Then no error message is shown in the form region

  @journey:contact @priority:critical @kind:empty-state
  Scenario: contact — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:contact @priority:critical @kind:resume
  Scenario: contact — deep-link to the terminal page renders correctly
    Given I open the page "/particulier/hypotheek/contact"
    Then I see the heading "Contact"

  @journey:contact @priority:critical @kind:back-button
  Scenario: contact — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/particulier/hypotheek/contact"
    When I go back in the browser history
    Then the main heading reads "Hypotheek berekenen"

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:contact @priority:critical @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: Double submit prevented
    Given I am on the landing page
    When I submit the form twice in rapid succession
    Then the form is not double-submitted
    Then I remain on the same page

  @journey:contact @priority:critical @llm-composed @kind:variant @model:qwen3-coder-next-latest
  Scenario: Empty submission shows field error
    Given I am on the landing page
    When I submit the form without filling any required field
    Then no success message is shown
    Then no error message is shown in the form region
