# Generated by quail.
#
# Gherkin contract for the  journey on /.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:
#   npx playwright test --grep @smoke

Feature: Pw_a11y_landmarks —  journey
  As a visitor of /
  I want to complete the  flow
  So that the page delivers on its user goal

  @journey: @priority:standard @smoke
  Scenario:  journey reaches its terminal page
    Given I open the landing page
