/**
 * Generated by reviewqa.
 *
 * Observability headers smoke for https://www.spritecloud.com. Asserts the origin
 * emits at least one of the headers that make production debugging
 * possible: x-request-id / x-correlation-id, server-timing, or
 * traceparent (W3C Trace Context).
 *
 * Filter: `npx playwright test --grep @kind:observability`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — checks for observability headers at https://www.spritecloud.com', () => {
  test('checks for at least one observability header in the response', async ({ request }) => {
    const response = await request.get('https://www.spritecloud.com')
    const headers = response.headers()
    const signals = {
      'x-request-id': headers['x-request-id'] || '',
      'x-correlation-id': headers['x-correlation-id'] || '',
      'server-timing': headers['server-timing'] || '',
      'traceparent': headers['traceparent'] || '',
      'x-amzn-trace-id': headers['x-amzn-trace-id'] || '',
    }
    console.log('observability headers seen:', signals)
    const any = Object.values(signals).some(v => v !== '')
    expect.soft(any, 'no observability headers found — consider emitting x-request-id or server-timing for ops').toBe(true)
  })
})
