// Generated by quail. Playwright configuration with sensible defaults
// for the suite quail just probed. `baseURL` defaults to the origin
// quail probed; override with `BASE_URL=...` to point the same suite
// at staging, a PR preview, or localhost.
//
// playwright-bdd is wired in: .feature files under tests/e2e/features/
// become the executable contract via step definitions in
// tests/e2e/steps/. Plain Playwright TS specs (api/*.api.spec.ts,
// *-fuzz.spec.ts, and the v0.22 quality specs under a11y/responsive/
// perf/security/health/observability/contract/i18n) still run alongside
// them as additional projects.
//
// QUAIL_BROWSERS env opts you in/out of cross-browser runs:
//   chromium-only (default in CI)   → QUAIL_BROWSERS=chromium
//   add firefox + webkit            → QUAIL_BROWSERS=chromium,firefox,webkit
//
// Edit freely — the next probe run will not overwrite this file.
import { defineConfig, devices } from '@playwright/test'
import { defineBddConfig } from 'playwright-bdd'

const BASE_URL = process.env.BASE_URL ?? 'https://www.ing.nl'

// Stealth parity with the probe. Three tiers via QUAIL_STEALTH:
//   off    → stock Playwright, no stealth.
//   on     → cheap-tier (default): UA override + the
//            --disable-blink-features=AutomationControlled launch flag.
//            Flips the two signals mid-tier bot detection trips on
//            (navigator.webdriver = true, "HeadlessChrome" in the UA).
//   heavy  → cheap-tier + playwright-extra/StealthPlugin in the worker
//            browser fixture (see tests/e2e/_fixtures.ts). Closes ~10
//            more fingerprint surfaces (codec list, plugin array,
//            WebGL vendor, chrome runtime…). Chromium-only.
//
// None of these defeat IP-level blocking; that needs a residential
// proxy.
const STEALTH_ON = (process.env.QUAIL_STEALTH || 'on').toLowerCase() !== 'off'

// Default baked at generation time from QUAIL_BROWSERS env (see
// quail-core/gen renderData.DefaultBrowsers). Override at run time
// with `QUAIL_BROWSERS=...` — useful when the probe picked firefox
// to slip past an Akamai-class WAF and you want to A/B chromium
// locally.
const BROWSERS = (process.env.QUAIL_BROWSERS ?? 'firefox')
  .split(',')
  .map(s => s.trim().toLowerCase())
  .filter(Boolean)

const bddTestDir = defineBddConfig({
  features: 'tests/e2e/features/*.feature',
  steps: 'tests/e2e/steps/*.ts',
})

const extrasTestMatch = /\.(api|fuzz|a11y|responsive|perf|security|health|observability|contract|i18n|visual|visual-states|keyboard|landmarks|zoom|prefs|network|storage|print|race|clipboard|http-chains|file-upload|iframe|date-edges|pwa|history-depth|touch|dragdrop|auth-expiry|locale-switch|graphql|webhook|mobile|deeplink|integration(-(db|broker|cache|storage|search|auth|obs))?)\.spec\.ts$/

function projectsForBrowser(browser: 'chromium' | 'firefox' | 'webkit') {
  const deviceProfile =
    browser === 'firefox' ? devices['Desktop Firefox'] :
    browser === 'webkit'  ? devices['Desktop Safari']  :
                            devices['Desktop Chrome']
  return [
    { name: `bdd-${browser}`,    testDir: bddTestDir, use: { ...deviceProfile } },
    { name: `extras-${browser}`, testDir: './tests/e2e', testMatch: extrasTestMatch, use: { ...deviceProfile } },
  ]
}

export default defineConfig({
  // v0.97.1 — bumped 30s default → 60s. With navigationTimeout at
  // 45s for image-heavy sites, a 30s test budget left no headroom
  // for any assertion past page.goto. 60s is safe; override via
  // QUAIL_TEST_TIMEOUT.
  timeout: Number(process.env.QUAIL_TEST_TIMEOUT ?? 60_000),
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI ? [['html', { open: 'never' }], ['list']] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    actionTimeout: 10_000,
    // v0.97.1 — bumped 20s → 45s. Webflow / image-heavy marketing
    // sites routinely take >20s for full `load` and spuriously trip
    // the assertions further down the spec. 45s leaves headroom for
    // first-paint and lazy-loaded fonts; tune via QUAIL_NAV_TIMEOUT
    // for projects with a different perf profile.
    navigationTimeout: Number(process.env.QUAIL_NAV_TIMEOUT ?? 45_000),
    // Cheap-tier stealth — see STEALTH_ON declaration above.
    ...(STEALTH_ON && {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      launchOptions: {
        args: ['--disable-blink-features=AutomationControlled'],
      },
    }),
  },
  projects: BROWSERS
    .filter((b): b is 'chromium' | 'firefox' | 'webkit' =>
      b === 'chromium' || b === 'firefox' || b === 'webkit')
    .flatMap(projectsForBrowser),
})
