// Generated by reviewqa. Playwright configuration with sensible defaults
// for the suite reviewqa just probed. `baseURL` defaults to the origin
// reviewqa probed; override with `BASE_URL=...` to point the same suite
// at staging, a PR preview, or localhost.
//
// Edit freely — the next probe-demo run will not overwrite this file.
import { defineConfig, devices } from '@playwright/test'

const BASE_URL = process.env.BASE_URL ?? 'https://www.spritecloud.com'

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI ? [['html', { open: 'never' }], ['list']] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 20_000,
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
})
