/**
 * Generated by reviewqa.
 *
 * Race-condition baseline for https://es.wikipedia.org/wiki/Especial:CambiosRecientes. When the page exposes a
 * form, asserts the form does not double-submit under a fast
 * double-click — a regression that costs real money on payment /
 * checkout flows and silently inflates contact form noise. Emitted
 * only when probe detected a <form>.
 *
 * Filter: `npx playwright test --grep @kind:race`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipediaOrg — race @ https://es.wikipedia.org/wiki/Especial:CambiosRecientes', () => {
  test('@kind:race @smoke form survives a rapid double-submit', async ({ page }) => {
    await page.goto('/wiki/Especial:CambiosRecientes')
    const form = page.locator('form').first()
    if (await form.count() === 0) test.skip()
    const submit = form.locator('button[type="submit"], input[type="submit"]').first()
    if (await submit.count() === 0) test.skip()
    // Fire two clicks back-to-back without waiting for navigation.
    await Promise.allSettled([
      submit.click({ noWaitAfter: true }),
      submit.click({ noWaitAfter: true }),
    ])
    await page.waitForLoadState('domcontentloaded').catch(() => {})
    // Heuristic: at most one success indicator visible after race.
    const indicators = page.locator('text=/success|thanks|received|submitted/i')
    const count = await indicators.count()
    expect.soft(count, `${count} success indicators after double-submit — likely a duplicate-submit bug`).toBeLessThanOrEqual(1)
  })
})

