/**
 * Generated by reviewqa.
 *
 * Steps API — higher-level helpers for the journey specs in this suite.
 * Each helper composes the underlying Playwright primitives (click,
 * fill, expect) into a single readable verb so the specs read at the
 * shape of the journey, not the shape of the DOM.
 *
 * Specs use these helpers by importing them from `./lib/steps`:
 *
 *   import { steps } from './lib/steps'
 *   await steps.visit(page, '/')
 *   await steps.fillForm(page, { email: 'me@example.com' })
 *   await steps.submit(page)
 *
 * The bodies stay deliberately small — the rationale lives in the
 * journey-kind doc comments at the top of each spec. Extend this file
 * when a new pattern repeats across more than two specs.
 */
import { expect, type Page, type Locator } from '@playwright/test'

/** Loose options for the higher-level helpers. */
export type FormValues = Record<string, string>

/**
 * Navigate to a relative path and wait for the DOM to settle. Use this
 * over `page.goto` when you want a single point of control for the
 * default settle behaviour across the suite.
 */
async function visit(page: Page, path: string): Promise<void> {
  await page.goto(path)
  await page.waitForLoadState('domcontentloaded')
}

/**
 * Fill a set of named form inputs by trying, in order:
 *   1. getByLabel(<key>)
 *   2. getByPlaceholder(<key>)
 *   3. locator('[name="<key>"]')
 * Whichever matches first wins. Silently skips unmatched keys so a
 * single helper handles forms whose field set varies across pages.
 */
async function fillForm(page: Page, values: FormValues): Promise<void> {
  for (const [key, value] of Object.entries(values)) {
    const candidates: Locator[] = [
      page.getByLabel(key, { exact: false }),
      page.getByPlaceholder(key),
      page.locator(`[name="${key}"]`),
    ]
    for (const loc of candidates) {
      if (await loc.first().count() > 0) {
        await loc.first().fill(value)
        break
      }
    }
  }
}

/**
 * Click the form's submit button. Looks for the role-based locator
 * first, falls back to `button[type=submit]` / `input[type=submit]`.
 */
async function submit(page: Page): Promise<void> {
  const byRole = page.getByRole('button', { name: /submit|send|sign in|sign up|subscribe|continue/i })
  if (await byRole.first().count() > 0) {
    await byRole.first().click()
    return
  }
  await page.locator('button[type="submit"], input[type="submit"]').first().click()
}

/** Click a nav link by visible text or href fragment. */
async function clickNav(page: Page, label: string | RegExp): Promise<void> {
  const link = page.getByRole('link', { name: label })
  if (await link.first().count() > 0) {
    await link.first().click()
    return
  }
  await page.locator(`a:has-text("${label}")`).first().click()
}

/**
 * Search the page for the search box and submit a query. Handles both
 * native input[type=search] and aria-labelled boxes.
 */
async function search(page: Page, query: string): Promise<void> {
  const box = page.locator('input[type="search"], [role="searchbox"]').first()
  await box.fill(query)
  await box.press('Enter')
}

/** Assert the URL changed to a path (or pattern). */
async function expectAt(page: Page, path: string | RegExp): Promise<void> {
  await expect(page).toHaveURL(typeof path === 'string' ? new RegExp(path + '$') : path)
}

/** Assert the page's h1 contains the given text. */
async function expectH1(page: Page, text: string | RegExp): Promise<void> {
  const name = typeof text === 'string' ? new RegExp(text, 'i') : text
  await expect(page.getByRole('heading', { level: 1, name })).toBeVisible()
}

/**
 * Convert-journey shorthand: visit a path, fill the form, submit, and
 * assert the page didn't surface an error region. Use for newsletter /
 * lead-gen forms where the success state is "no error" rather than a
 * redirect.
 */
async function convert(page: Page, path: string, values: FormValues): Promise<void> {
  await visit(page, path)
  await fillForm(page, values)
  await submit(page)
  const errors = page.locator('form, [role="form"]').first().locator('text=/error|failed/i')
  await expect(errors).toHaveCount(0)
}

/**
 * Authenticate shorthand: visit /login (or the given path), fill
 * email + password, submit, and assert URL changed away from the login
 * page. Tweak the post-submit assertion in the spec when the app
 * redirects to a known destination.
 */
async function authenticate(page: Page, path: string, email: string, password: string): Promise<void> {
  await visit(page, path)
  await fillForm(page, { email, password })
  await submit(page)
}

export const steps = {
  visit,
  fillForm,
  submit,
  clickNav,
  search,
  expectAt,
  expectH1,
  convert,
  authenticate,
}
