/**
 * Generated by reviewqa.
 *
 * API contract test — exercises the endpoint a form on the page submits
 * to, decoupled from the UI flow. Lives alongside the UI happy-flow
 * so a regression in either layer surfaces at the right altitude:
 *   - happy-flow (*.spec.ts): "the form on /contact still works end-to-end"
 *   - this file (*.api.spec.ts): "POST https://es.wikipedia.org/w/index.php still accepts our shape"
 *
 * Endpoint:     https://es.wikipedia.org/w/index.php
 * Method:       post
 * EncType:      application/x-www-form-urlencoded (default)
 *
 * Filter to API tests only: `npx playwright test --grep @kind:api`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipediaOrg — API contract @ https://es.wikipedia.org/w/index.php', () => {

  test('@kind:api @smoke happy: realistic body returns 2xx', async ({ request }) => {
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': '',
        'ui.dropdown-vector-appearance-dropdown': '',
        'ui.dropdown-vector-user-links-dropdown': '',
        'ui.dropdown-vector-page-titlebar-toc': '',
        'ui.dropdown-p-lang-btn': '',
        'ui.dropdown-vector-variants-dropdown': '',
        'ui.dropdown-vector-page-tools-dropdown': '',
        'ui.dropdown-vector-sticky-header-toc': '',
      },
    })
    // 2xx OR a 3xx redirect (post-redirect-get) is acceptable; many
    // marketing forms 302 to a thank-you page.
    expect(response.status()).toBeLessThan(400)
  })

  test('@kind:api @negative oversized payload does not 5xx', async ({ request }) => {
    const huge = 'a'.repeat(50_000)
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': '',
        'ui.dropdown-vector-appearance-dropdown': '',
        'ui.dropdown-vector-user-links-dropdown': '',
        'ui.dropdown-vector-page-titlebar-toc': '',
        'ui.dropdown-p-lang-btn': '',
        'ui.dropdown-vector-variants-dropdown': '',
        'ui.dropdown-vector-page-tools-dropdown': '',
        'ui.dropdown-vector-sticky-header-toc': '',
      },
    })
    // Truncated / 413 / 400 all acceptable; what we DON'T want is a 5xx.
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:api @negative wrong method returns 4xx', async ({ request }) => {
    // GET on a POST endpoint is the cheapest method-mismatch we can hit.
    const response = await request.get('https://es.wikipedia.org/w/index.php')
    // 405 Method Not Allowed is the textbook answer; 404 is also common
    // when the endpoint is method-specific.
    expect([400, 401, 403, 404, 405]).toContain(response.status())
  })

  // ─────────────────────────────────────────────────────────────
  // v0.50: extended form-negative coverage. The deck-cited "15-25
  // negatives per form" target needs more than 4 default cases —
  // each block below covers a value class an adversarial QA would
  // test by hand. None of these assert success; they each assert
  // the server doesn't 5xx and doesn't leak a stack trace.
  // ─────────────────────────────────────────────────────────────

  test('@kind:api @negative unicode payload does not 5xx', async ({ request }) => {
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-appearance-dropdown': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-user-links-dropdown': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-page-titlebar-toc': 'café-niño-用户-🎉-',
        'ui.dropdown-p-lang-btn': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-variants-dropdown': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-page-tools-dropdown': 'café-niño-用户-🎉-',
        'ui.dropdown-vector-sticky-header-toc': 'café-niño-用户-🎉-',
      },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:api @negative sql-injection-shaped input does not 5xx', async ({ request }) => {
    // Tests the server's input sanitization. The contract: MUST NOT
    // 5xx and MUST NOT echo back unescaped fragments.
    const payload = "'; DROP TABLE users; --"
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': payload,
        'ui.dropdown-vector-appearance-dropdown': payload,
        'ui.dropdown-vector-user-links-dropdown': payload,
        'ui.dropdown-vector-page-titlebar-toc': payload,
        'ui.dropdown-p-lang-btn': payload,
        'ui.dropdown-vector-variants-dropdown': payload,
        'ui.dropdown-vector-page-tools-dropdown': payload,
        'ui.dropdown-vector-sticky-header-toc': payload,
      },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('sqlstate')
    expect.soft(body.toLowerCase()).not.toContain('syntax error')
  })

  test('@kind:api @negative xss-shaped input is escaped or rejected', async ({ request }) => {
    const payload = '<script>window.__rqXSS=1</script>'
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': payload,
        'ui.dropdown-vector-appearance-dropdown': payload,
        'ui.dropdown-vector-user-links-dropdown': payload,
        'ui.dropdown-vector-page-titlebar-toc': payload,
        'ui.dropdown-p-lang-btn': payload,
        'ui.dropdown-vector-variants-dropdown': payload,
        'ui.dropdown-vector-page-tools-dropdown': payload,
        'ui.dropdown-vector-sticky-header-toc': payload,
      },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body).not.toContain('<script>window.__rqXSS=1</script>')
  })

  test('@kind:api @negative null-byte injection does not 5xx', async ({ request }) => {
    const response = await request.post('https://es.wikipedia.org/w/index.php', {
      form: {
        'ui.dropdown-vector-main-menu-dropdown': 'value\x00malicious',
        'ui.dropdown-vector-appearance-dropdown': 'value\x00malicious',
        'ui.dropdown-vector-user-links-dropdown': 'value\x00malicious',
        'ui.dropdown-vector-page-titlebar-toc': 'value\x00malicious',
        'ui.dropdown-p-lang-btn': 'value\x00malicious',
        'ui.dropdown-vector-variants-dropdown': 'value\x00malicious',
        'ui.dropdown-vector-page-tools-dropdown': 'value\x00malicious',
        'ui.dropdown-vector-sticky-header-toc': 'value\x00malicious',
      },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:api @negative rapid burst stays healthy or is rate-limited', async ({ request }) => {
    // 10 concurrent identical requests. Either the server rate-limits
    // (429) — fine — or it serves all 10 without 5xx-ing.
    const body = {
      'ui.dropdown-vector-main-menu-dropdown': '',
      'ui.dropdown-vector-appearance-dropdown': '',
      'ui.dropdown-vector-user-links-dropdown': '',
      'ui.dropdown-vector-page-titlebar-toc': '',
      'ui.dropdown-p-lang-btn': '',
      'ui.dropdown-vector-variants-dropdown': '',
      'ui.dropdown-vector-page-tools-dropdown': '',
      'ui.dropdown-vector-sticky-header-toc': '',
    }
    const responses = await Promise.all(
      Array.from({ length: 10 }, () => request.post('https://es.wikipedia.org/w/index.php', { form: body }))
    )
    for (const r of responses) {
      expect.soft(r.status(), `burst response status ${r.status()}`).toBeLessThan(500)
    }
  })
})

