# Generated by quail.
#
# Gherkin contract for the browse journey on https://playwright.dev/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Playwright — browse journey
  As a visitor of https://playwright.dev/
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Fast and reliable end-to-end testing for modern web apps | Playwright"
    And the main heading reads "Playwright enables reliable web automation for testing, scripting, and AI agents."
    When I click the link to "/mcp/introduction"
    Then I see the heading "Playwright MCP"
    And the page title contains "Introduction | Playwright"
    When I click the link to "/docs/intro"
    Then I see the heading "Installation"
    And the page title contains "Installation | Playwright"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/docs/intro"
    Then I see the heading "Installation"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/docs/intro"
    When I go back in the browser history
    Then the main heading reads "Playwright enables reliable web automation for testing, scripting, and AI agents."

