# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://playwright.dev.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: Playwright — read journey
  As a visitor of https://playwright.dev
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Fast and reliable end-to-end testing for modern web apps | Playwright"
    When I navigate directly to "/community/conference-videos"
    Then I see the heading "Conference Videos"
    And the page title contains "Conference Videos | Playwright"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: read — deep-link to the terminal page renders correctly
    Given I open the page "/community/conference-videos"
    Then I see the heading "Conference Videos"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: read — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/community/conference-videos"
    When I go back in the browser history

