# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://playwright.dev.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: PlaywrightDev — read journey
  As a visitor of https://playwright.dev
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey completes and lands on the expected terminal page
    Given I open the landing page
    And the page title contains "Fast and reliable end-to-end testing for modern web apps | Playwright"
    When I navigate directly to "/community/conference-videos"
    Then I see the heading "Conference Videos"
    And the page title contains "Conference Videos | Playwright"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: deep-linking to the terminal page loads and displays correctly
    Given I open the page "/community/conference-videos"
    Then I see the heading "Conference Videos"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: navigating and using the back button returns to the landing page
    Given I open the landing page
    When I click the link to "/community/conference-videos"
    When I go back in the browser history

  # ───────────────────────────────────────────────────────────────
  # LLM-composed scenarios (model: qwen3-coder-next:latest)
  # Filter out with `--grep-invert @llm-composed` for stricter CI runs.
  # ───────────────────────────────────────────────────────────────

  @journey:read @priority:nice-to-have @llm-composed @kind:edge @model:qwen3-coder-next-latest
  Scenario: reloading the conference videos page preserves its content and title
    Given I open the landing page
    When I click the link to "/community/conference-videos"
    Then the page title contains "Conference Videos | Playwright"
    Then the main heading reads "Conference Videos"
    When I reload the page
    Then the page title contains "Conference Videos | Playwright"
    Then the main heading reads "Conference Videos"

