/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (12 inputs, 0 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/**
 * Generated by reviewqa. Fuzz spec for https://es.wikipedia.org/wiki/Especial:CambiosRecientes.
 *
 * Bounded negative-coverage: each text input + interactive component on
 * this page gets exercised with edge-case payloads (empty, very long,
 * special chars) to surface input-handling bugs the happy-path specs
 * skip over. Capped at 5 emissions per page so triage stays tractable.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipediaOrg — fuzz / negative input', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/wiki/Especial:CambiosRecientes')
  })

  test('@fuzz @negative input "tagfilter" handles edge payloads', async ({ page }) => {
    const field = page.locator('[name="tagfilter"]').first()
    // Empty value: should be accepted by the field itself (validation
    // surfaces only on submit).
    await field.fill('')
    await expect(field).toHaveValue('')
    // Very long input (5000 chars): field should not crash or hang.
    const long = 'x'.repeat(5000)
    await field.fill(long)
    const persisted = await field.inputValue()
    expect(persisted.length).toBeGreaterThan(0)
    // Special-character payload: HTML-injection shape. Must not execute
    // (handled by the pageErrors fixture in _fixtures.ts).
    await field.fill('\'><script>alert(1)</script>')
    await expect(field).toBeAttached()
  })

  test('@fuzz @keyboard details (Lista de abreviaturas:) responds to Tab + Enter', async ({ page }) => {
    // Tab through the page looking for the trigger, then activate via
    // keyboard. Catches focus-trap and missing-keyboard-handler bugs
    // that mouse-only tests miss.
    const target = page.locator('details', { has: page.locator('summary', { hasText: 'Lista de abreviaturas:' }) }).first()
    await target.focus()
    await page.keyboard.press('Enter')
    // No assertion on resulting state — interactions vary by kind.
    // The pageErrors fixture catches any uncaught JS the keyboard
    // path triggered.
    await expect(target).toBeAttached()
  })
})
