/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (14 inputs, 0 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/**
 * Generated by reviewqa. Fuzz spec for https://es.wikipedia.org/wiki/Especial:P%C3%A1ginasNuevas.
 *
 * Bounded negative-coverage: each text input + interactive component on
 * this page gets exercised with edge-case payloads (empty, very long,
 * special chars) to surface input-handling bugs the happy-path specs
 * skip over. Capped at 5 emissions per page so triage stays tractable.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipedia — fuzz / negative input', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/wiki/Especial:PáginasNuevas')
  })

  test('@fuzz @negative input "tagfilter" handles edge payloads', async ({ page }) => {
    const field = page.locator('[name="tagfilter"]').first()
    // Empty value: should be accepted by the field itself (validation
    // surfaces only on submit).
    await field.fill('')
    await expect(field).toHaveValue('')
    // Very long input (5000 chars): field should not crash or hang.
    const long = 'x'.repeat(5000)
    await field.fill(long)
    const persisted = await field.inputValue()
    expect(persisted.length).toBeGreaterThan(0)
    // Special-character payload: HTML-injection shape. Must not execute
    // (handled by the pageErrors fixture in _fixtures.ts).
    await field.fill('\'><script>alert(1)</script>')
    await expect(field).toBeAttached()
  })

  test('@fuzz @negative input "username" handles edge payloads', async ({ page }) => {
    const field = page.getByLabel('Nombre de usuario:').first()
    // Empty value: should be accepted by the field itself (validation
    // surfaces only on submit).
    await field.fill('')
    await expect(field).toHaveValue('')
    // Very long input (5000 chars): field should not crash or hang.
    const long = 'x'.repeat(5000)
    await field.fill(long)
    const persisted = await field.inputValue()
    expect(persisted.length).toBeGreaterThan(0)
    // Special-character payload: HTML-injection shape. Must not execute
    // (handled by the pageErrors fixture in _fixtures.ts).
    await field.fill('\'><script>alert(1)</script>')
    await expect(field).toBeAttached()
  })

  test('@fuzz @negative input "size" handles edge payloads', async ({ page }) => {
    const field = page.locator('[name="size"]').first()
    // Empty value: should be accepted by the field itself (validation
    // surfaces only on submit).
    await field.fill('')
    await expect(field).toHaveValue('')
    // Very long input (5000 chars): field should not crash or hang.
    const long = 'x'.repeat(5000)
    await field.fill(long)
    const persisted = await field.inputValue()
    expect(persisted.length).toBeGreaterThan(0)
    // Special-character payload: HTML-injection shape. Must not execute
    // (handled by the pageErrors fixture in _fixtures.ts).
    await field.fill('\'><script>alert(1)</script>')
    await expect(field).toBeAttached()
  })
})

