// Generated by quail. Shared Playwright fixtures for the generated
// e2e suite. All `*.spec.ts` files in this directory import `test` and
// `expect` from here instead of from `@playwright/test` directly, so
// every spec inherits the page-error tracking + baseline assertions
// without re-declaring them.
import { test as base, expect, chromium as chrStock } from '@playwright/test'

// QUAIL_STEALTH posture (parity with the probe in
// quail-core/probe/browser/probe.mjs):
//   off    → stock Playwright, no stealth.
//   on     → cheap stealth from playwright.config.ts only (default):
//            UA override + --disable-blink-features=AutomationControlled.
//   heavy  → cheap stealth + playwright-extra/StealthPlugin via a
//            worker-scoped browser override (probe parity; masks
//            navigator.webdriver, codec list, plugin array, WebGL
//            vendor, chrome runtime, etc.). Chromium-only —
//            StealthPlugin's puppeteer-extra plugins assume CDP. IP
//            blocks (residential vs datacenter) are NOT addressed here.
const STEALTH_HEAVY = (process.env.QUAIL_STEALTH || 'on').toLowerCase() === 'heavy'

type Fixtures = {
  pageErrors: string[]
}

export const test = base.extend<Fixtures>({
  // Worker-scoped browser override. Only swaps in playwright-extra
  // when STEALTH_HEAVY && chromium; otherwise the early return keeps
  // Playwright's stock browser fixture so projects/devices/firefox/
  // webkit all keep working untouched.
  browser: [async ({ browserName, playwright }, use) => {
    if (!STEALTH_HEAVY || browserName !== 'chromium') {
      const b = await playwright[browserName].launch()
      await use(b)
      await b.close()
      return
    }
    // Dynamic import so non-heavy runs don't pay the load cost and
    // don't fail if the dep was pruned. ponytail: dynamic import is
    // the cheapest gate — no top-level dep wiring, no babel hoist.
    const { addExtra } = await import('playwright-extra')
    const StealthMod: any = await import('puppeteer-extra-plugin-stealth')
    const StealthPlugin = StealthMod.default ?? StealthMod
    const wrapped: any = addExtra(chrStock as any).use(StealthPlugin())
    const b = await wrapped.launch()
    await use(b)
    await b.close()
  }, { scope: 'worker' }],

  // pageErrors fixture wraps `page`. It installs a `pageerror` listener
  // at the start of each test and asserts the captured list is empty
  // at the end. `expect.soft` so an uncaught JS error is reported but
  // doesn't cascade-fail other soft assertions emitted earlier.
  pageErrors: [async ({ page }, use) => {
    const errors: string[] = []
    page.on('pageerror', (e) => errors.push(String(e)))
    await use(errors)
    expect.soft(errors, 'no uncaught JS errors during the test').toHaveLength(0)
  }, { auto: true }],
})

export { expect }
