// Generated by reviewqa. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('Counter', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('Counter: counter-root is visible', async ({ page }) => {
    await expect(page.getByTestId('counter-root').first()).toBeVisible()
  })

  test('Counter: Counter widget is visible', async ({ page }) => {
    await expect(page.getByLabel('Counter widget').first()).toBeVisible()
  })

  test('Counter: region is visible', async ({ page }) => {
    await expect(page.getByRole('region').first()).toBeVisible()
  })

  test('Counter: counter-display is visible', async ({ page }) => {
    await expect(page.getByTestId('counter-display').first()).toBeVisible()
  })

  test('Counter: counter-inc is visible', async ({ page }) => {
    await expect(page.getByTestId('counter-inc').first()).toBeVisible()
  })

  test('Counter: clicks button counter-inc', async ({ page }) => {
    const target = page.getByTestId('counter-inc').first()
    await target.click()
    await expect(target).toBeVisible()
  })

  test('Counter: click toggles aria-expanded on button', async ({ page }) => {
    const target = page.getByTestId('counter-inc').first()
    const before = await target.getAttribute('aria-expanded')
    await target.click()
    const after = await target.getAttribute('aria-expanded')
    expect(after).not.toBe(before)
  })
})
