// Generated by reviewqa. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('Dashboard', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('Dashboard: dashboard-page is visible', async ({ page }) => {
    await expect(page.getByTestId('dashboard-page').first()).toBeVisible()
  })

  test('Dashboard: Customer dashboard is visible', async ({ page }) => {
    await expect(page.getByLabel('Customer dashboard').first()).toBeVisible()
  })

  test('Dashboard: main is visible', async ({ page }) => {
    await expect(page.getByRole('main').first()).toBeVisible()
  })

  test('Dashboard: dashboard-heading is visible', async ({ page }) => {
    await expect(page.getByTestId('dashboard-heading').first()).toBeVisible()
  })

  test('Dashboard: dashboard-summary is visible', async ({ page }) => {
    await expect(page.getByTestId('dashboard-summary').first()).toBeVisible()
  })

  test('Dashboard: dashboard-home-link is visible', async ({ page }) => {
    await expect(page.getByTestId('dashboard-home-link').first()).toBeVisible()
  })

  test('Dashboard: navigates to /', async ({ page }) => {
    const link = page.locator('a[href="/"], [href="/"]').first()
    await link.click()
    await expect(page).toHaveURL(new RegExp('/$'))
  })
})
