// Generated by reviewqa. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

test('renders the FAQ component', async ({ page }) => {
  await page.goto(process.env.BASE_URL ?? 'http://localhost:3000')
  await expect(page.getByRole('main')).toBeVisible()
  // TODO: assert FAQ-specific elements once a stable locator is chosen.
})
