/**
 * Generated by reviewqa.
 *
 * Journey kind: page-happy-flow
 * Entry page:   /
 * Steps:        1
 *
 * Filter to this kind with: `npx playwright test --grep @journey:`
 * Filter to all smokes: `npx playwright test --grep @smoke`
 *
 * Stable signals (hard assertions) drive the journey: URL changes,
 * h1 visibility, form submit. Nice-to-have signals (h2 sub-headings,
 * image alt, meta tags) are `expect.soft` so a copy edit doesn't
 * cascade-fail the whole test.
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('Index page happy flow', () => {
  // Page-error tracking is automatic via the `pageErrors` fixture in
  // _fixtures.ts (auto:true). Each test still needs to navigate to
  // the landing page itself — the path is baseURL-relative so the
  // same suite can run against staging / a PR preview / localhost by
  // setting BASE_URL.
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })
  test('full user journey (1 step(s))', async ({ page }) => {
    // Step 1 — visit landing (intent: content) — handled by beforeEach
    await expect(page.getByTestId('wordmark').first()).toBeVisible()
    await expect(page.getByTestId('nav-cta').first()).toBeVisible()
    await expect(page.getByTestId('hero-title').first()).toBeVisible()
    await expect(page.getByTestId('cta-install').first()).toBeVisible()
    await expect(page.getByTestId('cta-github').first()).toBeVisible()
    await expect(page.getByTestId('feature-grid').first()).toBeVisible()
    await expect(page.getByTestId('examples-grid').first()).toBeVisible()
    await expect(page.getByTestId('coverage-snippet').first()).toBeVisible()
  })
})
