// Generated by reviewqa. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('Login', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('Login: login-page is visible', async ({ page }) => {
    await expect(page.getByTestId('login-page').first()).toBeVisible()
  })

  test('Login: main is visible', async ({ page }) => {
    await expect(page.getByRole('main').first()).toBeVisible()
  })

  test('Login: login-dashboard-link is visible', async ({ page }) => {
    await expect(page.getByTestId('login-dashboard-link').first()).toBeVisible()
  })

  test('Login: navigates to /dashboard', async ({ page }) => {
    const link = page.locator('a[href="/dashboard"], [href="/dashboard"]').first()
    await link.click()
    await expect(page).toHaveURL(new RegExp('/dashboard$'))
  })
})
