// Generated by reviewqa. Review and extend with edge cases.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('LoginForm', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE) })

  test('LoginForm: login-form is visible', async ({ page }) => {
    await expect(page.getByTestId('login-form').first()).toBeVisible()
  })

  test('LoginForm: login-email is visible', async ({ page }) => {
    await expect(page.getByTestId('login-email').first()).toBeVisible()
  })

  test('LoginForm: login-password is visible', async ({ page }) => {
    await expect(page.getByTestId('login-password').first()).toBeVisible()
  })

  test('LoginForm: login-submit is visible', async ({ page }) => {
    await expect(page.getByTestId('login-submit').first()).toBeVisible()
  })

  test('LoginForm: login-forgot is visible', async ({ page }) => {
    await expect(page.getByTestId('login-forgot').first()).toBeVisible()
  })

  test('LoginForm: fills the form and submits', async ({ page }) => {
    await page.locator('input').first().fill('test')
    await page.getByTestId('login-email').first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })

  test('LoginForm: navigates to /forgot', async ({ page }) => {
    const link = page.locator('a[href="/forgot"], [href="/forgot"]').first()
    await link.click()
    await expect(page).toHaveURL(new RegExp('/forgot$'))
  })
})
