/* quail quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (2 inputs, 0 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/**
 * Generated by quail. Fuzz spec for https://www.ing.nl/private-banking.
 *
 * Bounded negative-coverage: each text input + interactive component on
 * this page gets exercised with edge-case payloads (empty, very long,
 * special chars) to surface input-handling bugs the happy-path specs
 * skip over. Capped at 5 emissions per page so triage stays tractable.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — Field validation with edge-case inputs', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
  })
})
