// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com/contact'

test.describe('WwwSpritecloudCom page happy flow', () => {
  test.beforeEach(async ({ page }) => { await page.goto(TARGET) })

  test('walks 1 component(s) on https://www.spritecloud.com/contact', async ({ page }) => {
    // --- WwwSpritecloudCom (intent: nav) ---
    await expect(page).toHaveTitle(/spriteCloud — Meeting Booking Form/i)
    await expect(page.getByRole('banner').first()).toBeVisible()
    // Navigate via ranked link /case-studies (Test Automation)
    {
      const link = page.locator('a[href="/case-studies"], [href="/case-studies"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/case-studies$'))
      await page.goto(TARGET)
    }
    // Navigate via ranked link /contact (Test Automation)
    {
      const link = page.locator('a[href="/contact"], [href="/contact"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/contact$'))
      await page.goto(TARGET)
    }
  })
})
