// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'

const BASE = process.env.BASE_URL ?? 'http://localhost:3000'

test.describe('WwwSpritecloudCom page happy flow', () => {
  test.beforeEach(async ({ page }) => { await page.goto(BASE + 'https://www.spritecloud.com') })

  test('walks 1 component(s) on https://www.spritecloud.com', async ({ page }) => {
    // --- WwwSpritecloudCom ---
    await expect(page.getByRole('banner').first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()
    // Fill form
    await page.locator('[name="email-2"]').first().fill('test@example.com')
    await page.locator('input').first().fill('test')
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
    {
      const link = page.locator('a[href="/contact"], [href="/contact"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/contact$'))
    }
  })
})
