/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - note: using <placeholder> as locator — no data-testid on the input
 *   - SKIP: input on line 24 has no stable locator — add data-testid
 * Add data-testid to these elements for stable tests.
 */
// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom page happy flow', () => {
  test('full user journey (1 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: form)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('banner').first()).toBeVisible()
    await expect(page.getByRole('button', { name: 'Submit' }).first()).toBeVisible()
    // Fill form
    // note: using <placeholder> as locator — no data-testid on the input
    await page.getByPlaceholder('Your email address').first().fill('test@example.com')
    // SKIP: input on line 24 has no stable locator — add data-testid
    await page.getByRole('button', { name: 'Submit' }).first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
