// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from './_fixtures'

test.describe('WwwSpritecloudCom — browse journey', () => {
  // Page-error tracking is automatic via the `pageErrors` fixture in
  // _fixtures.ts (auto:true). Each test still needs to navigate to
  // the landing page itself — the path is baseURL-relative so the
  // same suite can run against staging / a PR preview / localhost by
  // setting BASE_URL.
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })
  test('browse: full user journey (3 step(s))', async ({ page }) => {
    // Step 1 — visit landing (intent: nav) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect(page.getByRole('banner').first()).toBeVisible()

    await test.step('Step 2 — click "/guides"', async () => {
      const link = page.locator('a[href="/guides"], [href="/guides"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('/guides')
      }
      await expect(page).toHaveURL(new RegExp('/guides$'))
    })
    await expect(page).toHaveTitle(/spriteCloud - Your Software Testing and QA partner/i)
    await expect.soft(page.locator('h2', { hasText: /Guides/i }).first()).toBeAttached()
    await expect(page.getByRole('list').first()).toBeVisible()

    await test.step('Step 3 — click "/about-us"', async () => {
      const link = page.locator('a[href="/about-us"], [href="/about-us"]').first()
      try {
        await link.click({ timeout: 3000 })
      } catch {
        // Link is in the DOM but not directly clickable (often a hover-only
        // dropdown menu item). Navigate by URL so the destination still gets
        // exercised instead of the whole spec hard-failing on the menu.
        await page.goto('/about-us')
      }
      await expect(page).toHaveURL(new RegExp('/about-us$'))
    })
    await expect(page).toHaveTitle(/About Us/i)
    await expect(page.getByRole('heading', { level: 1, name: /Testing is in our DNA\./i }).first()).toBeVisible()
  })
})
