// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — browse journey', () => {
  test('browse: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/blog" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/blog"], [href="/blog"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/blog$'))
    }
    await expect(page).toHaveTitle(/Blog/i)
    await expect(page.getByRole('list').first()).toBeVisible()

    // Step 3 — outbound click "/contact" (Test Automation)
    {
      const link = page.locator('a[href="/contact"], [href="/contact"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/contact$'))
    }
  })
})
