// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — research journey', () => {
  test('research: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/case-study-grandvision" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/case-study-grandvision"], [href="/case-study-grandvision"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/case-study-grandvision$'))
    }
    await expect(page).toHaveTitle(/Case Study - GrandVision/i)
    await expect(page.getByRole('heading', { level: 1, name: /GrandVision/i }).first()).toBeVisible()

    // Step 3 — outbound click "/" (Test Automation)
    {
      const link = page.locator('a[href="/"], [href="/"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/$'))
    }
  })
})
