/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - note: using <placeholder> as locator — no data-testid on the input
 *   - SKIP: input on line 24 has no stable locator — add data-testid
 * Add data-testid to these elements for stable tests.
 */
// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from './_fixtures'

test.describe('WwwSpritecloudCom — convert journey', () => {
  // Page-error tracking is automatic via the `pageErrors` fixture in
  // _fixtures.ts (auto:true). Each test still needs to navigate to
  // the landing page itself — the path is baseURL-relative so the
  // same suite can run against staging / a PR preview / localhost by
  // setting BASE_URL.
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })
  // Marked test.fail() because reviewqa detected a known-broken pattern
  // on this page: the submit element carries a `data-wait` attribute,
  // indicating a Webflow / similar form whose Submit button stays
  // disabled until client-side JS validates the input. Playwright's
  // .fill() doesn't trigger the same blur/change events a real user
  // would, so the click() will time out on the disabled submit. Remove
  // this annotation once the underlying form handling is sorted.
  test.fail('convert: full user journey (1 step(s))', async ({ page }) => {
    // Step 1 — visit landing (intent: form) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect(page.getByRole('banner').first()).toBeVisible()
    await expect(page.getByRole('button', { name: 'Submit' }).first()).toBeVisible()
    // Fill form
    // note: using <placeholder> as locator — no data-testid on the input
    await page.getByPlaceholder('Your email address').first().fill('test@example.com')
    // SKIP: input on line 24 has no stable locator — add data-testid
    await page.getByRole('button', { name: 'Submit' }).first().click()
    await expect(page.locator('text=/error|failed/i')).toHaveCount(0)
  })
})
