// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from './_fixtures'

test.describe('WwwSpritecloudCom — research journey', () => {
  // Page-error tracking is automatic via the `pageErrors` fixture in
  // _fixtures.ts (auto:true). Each test still needs to navigate to
  // the landing page itself — the path is baseURL-relative so the
  // same suite can run against staging / a PR preview / localhost by
  // setting BASE_URL.
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })
  test('research: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit landing (intent: nav) — handled by beforeEach
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect.soft(page.getByAltText(/Company logo Ahold Dhaize/i).first()).toBeAttached()
    await expect.soft(page.getByAltText(/Company logo Heineken/i).first()).toBeAttached()
    await expect.soft(page.locator('meta[name="description"]')).toHaveAttribute('content', /spriteCloud is a software testing company based in Amsterdam, Netherlands\. We help companies and organisations ship robust and safe software\. We work as long term partners, or as interim solutions\./i)
    await expect.soft(page.locator('meta[property="og:title"]')).toHaveAttribute('content', /spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('banner').first()).toBeVisible()

    await test.step('Step 2 — direct goto "/case-study-grandvision"', async () => {
      await page.goto('/case-study-grandvision')
      await expect(page).toHaveURL(new RegExp('/case-study-grandvision$'))
    })
    await expect(page).toHaveTitle(/Case Study - GrandVision/i)
    await expect(page.getByRole('heading', { level: 1, name: /GrandVision/i }).first()).toBeVisible()
  })
})
