// Generated by reviewqa. Single-page happy flow: navigate, walk, fill, submit, advance.
import { test, expect } from '@playwright/test'
const TARGET = 'https://www.spritecloud.com'

test.describe('WwwSpritecloudCom — read journey', () => {
  test('read: full user journey (2 step(s))', async ({ page }) => {
    // Step 1 — visit https://www.spritecloud.com (intent: nav)
    await page.goto(TARGET)
    await expect(page).toHaveTitle(/spriteCloud - Test your software, not your reputation!/i)
    await expect(page.getByRole('heading', { level: 1, name: /Test your software, not your reputation\./i }).first()).toBeVisible()
    await expect(page.getByRole('banner').first()).toBeVisible()

    // Step 2 — click "/style-guide" and land on the next page (intent: nav)
    {
      const link = page.locator('a[href="/style-guide"], [href="/style-guide"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/style-guide$'))
    }
    await expect(page).toHaveTitle(/Style Guide - Healix Webflow website HTML template/i)
    await expect(page.getByRole('heading', { level: 1, name: /Aa/i }).first()).toBeVisible()

    // Step 3 — outbound click "/cybersecurity" (Primary Button)
    {
      const link = page.locator('a[href="/cybersecurity"], [href="/cybersecurity"]').first()
      await link.click()
      await expect(page).toHaveURL(new RegExp('/cybersecurity$'))
    }
  })
})
