/**
 * Generated by reviewqa.
 *
 * Responsive smoke for https://www.spritecloud.com/on-demand. Visits the page at mobile (375px),
 * tablet (768px), and desktop (1280px) viewports and asserts the page
 * still renders a visible h1. Catches catastrophic responsive
 * breakdowns without taking screenshots (no baseline storage required).
 *
 * Filter: `npx playwright test --grep @kind:responsive`
 */
import { test, expect } from '@playwright/test'

const VIEWPORTS = [
  { name: 'mobile',  width: 375,  height: 667 },
  { name: 'tablet',  width: 768,  height: 1024 },
  { name: 'desktop', width: 1280, height: 720 },
] as const

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — responsive @ https://www.spritecloud.com/on-demand', () => {
  for (const vp of VIEWPORTS) {
    test(`@kind:responsive @smoke renders at ${vp.name} (${vp.width}x${vp.height})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height })
      await page.goto('/on-demand')
      await expect(page.locator('h1').first()).toBeVisible()
      // Hard-fail signals: no body content rendered, document overflow.
      const bodyHasText = await page.evaluate(() => (document.body.innerText || '').trim().length > 0)
      expect(bodyHasText, 'body should have text at this viewport').toBe(true)
    })
  }
})

