/**
 * Generated by quail.
 *
 * Mobile-web smoke for https://playwright.dev/. v0.56 — depth parity. Where the
 * pre-v0.56 template emitted a single iPhone-13 test, this version
 * iterates a deterministic device matrix and runs the smoke plus an
 * orientation flip on each, giving 8 tests per page (4 devices ×
 * 2 scenarios).
 *
 * v0.61 — fixed: pre-v0.61 used `test.use({...devices[name]})` inside
 * `test.describe()`, which Playwright rejects ("forces a new worker").
 * The fix uses `browser.newContext({...devices[name]})` inside each
 * test so the device profile is applied per-test rather than per-
 * describe-group. Same coverage, no `test.use()` violation.
 *
 * The device list is conservative: the four shapes that catch ~95%
 * of real-world mobile regressions (small iPhone, mid Android phone,
 * tablet portrait, large-screen Android). Add more by extending
 * DEVICES; Playwright ships ~50 device profiles via `devices`.
 *
 * Filter: `npx playwright test --grep @kind:mobile`
 */
import { test, expect, devices } from '@playwright/test'

const DEVICES = ['iPhone 13', 'Pixel 5', 'iPad Pro 11', 'Galaxy S9+'] as const

test.describe.configure({ mode: 'parallel' })

for (const deviceName of DEVICES) {
  test(`@kind:mobile @smoke @device:${deviceName} viewport renders without breakage`, async ({ browser }) => {
    const ctx = await browser.newContext({ ...devices[deviceName] })
    const page = await ctx.newPage()
    await page.goto('/')
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    // Touch tap on the primary CTA, when present.
    const cta = page.getByRole('link').first()
    if (await cta.count() > 0) {
      await cta.tap().catch(() => {})
    }
    await ctx.close()
  })

  test(`@kind:mobile @orientation @device:${deviceName} landscape rotation keeps the page interactive`, async ({ browser }) => {
    const profile = devices[deviceName]
    if (!profile.viewport) test.skip()
    // Rebuild a context with the viewport height/width swapped. Same
    // engine, UA, DPR — only the screen aspect changes.
    const ctx = await browser.newContext({
      ...profile,
      viewport: { width: profile.viewport!.height, height: profile.viewport!.width },
    })
    const page = await ctx.newPage()
    await page.goto('/')
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    await ctx.close()
  })
}

