/**
 * Generated by reviewqa.
 *
 * Responsive smoke for https://playwright.dev/community/conference-videos. Visits the page at mobile (375px),
 * tablet (768px), and desktop (1280px) viewports and asserts the page
 * still renders a visible h1. Catches catastrophic responsive
 * breakdowns without taking screenshots (no baseline storage required).
 *
 * Filter: `npx playwright test --grep @kind:responsive`
 */
import { test, expect } from '@playwright/test'

const VIEWPORTS = [
  { name: 'mobile',  width: 375,  height: 667 },
  { name: 'tablet',  width: 768,  height: 1024 },
  { name: 'desktop', width: 1280, height: 720 },
] as const

test.describe.configure({ mode: 'parallel' })
test.describe('PlaywrightDev responsive layout smoke test', () => {
  for (const vp of VIEWPORTS) {
    test(`@kind:responsive @smoke renders correctly on ${vp.name} viewport (${vp.width}x${vp.height})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height })
      await page.goto('/community/conference-videos')
      await expect(page.locator('h1').first()).toBeVisible()
      // Verify page renders content: checks for visible body text (no blank pages or layout crashes)
    })
  }
})

