/**
 * Generated by reviewqa.
 *
 * Step definitions for the .feature files in tests/e2e/features/.
 * Bound to the helper verbs in tests/e2e/lib/steps.ts so the
 * Gherkin vocabulary and the underlying Playwright primitives stay
 * one wiring layer apart.
 *
 * playwright-bdd registers these via `createBdd()`; the runtime
 * config in `playwright.config.ts` points at this directory.
 *
 * Add new step patterns here as the feature files evolve — keep one
 * step definition per pattern to preserve the BDD reuse story.
 */
import { expect } from '@playwright/test'
import { createBdd } from 'playwright-bdd'
import { steps } from '../lib/steps'

const { Given, When, Then } = createBdd()

Given('I open the landing page', async ({ page }) => {
  await steps.visit(page, '/')
})

Given('I am on the landing page', async ({ page }) => {
  await steps.visit(page, '/')
})

Given(/^I open the page "([^"]+)"$/, async ({ page }, path: string) => {
  await steps.visit(page, path)
})

When(/^I click the link to "([^"]+)"$/, async ({ page }, href: string) => {
  const link = page.locator(`a[href="${href}"], [href="${href}"]`).first()
  try {
    await link.click({ timeout: 3000 })
  } catch {
    // Link is in the DOM but not directly clickable (often a hover-only
    // dropdown menu item). Navigate by URL so the destination still gets
    // exercised instead of the whole spec hard-failing on the menu.
    await page.goto(href)
  }
  await expect(page).toHaveURL(new RegExp(escapeRegex(href) + '$'))
})

When(/^I navigate directly to "([^"]+)"$/, async ({ page }, href: string) => {
  await page.goto(href)
  await expect(page).toHaveURL(new RegExp(escapeRegex(href) + '$'))
})

When(/^I enter "([^"]+)" into the "([^"]+)" field$/, async ({ page }, value: string, field: string) => {
  await steps.fillForm(page, { [field]: value })
})

When('I submit the form', async ({ page }) => {
  await steps.submit(page)
})

When('I submit the form without filling any required field', async ({ page }) => {
  await steps.submit(page)
})

Then(/^the page title contains "([^"]+)"$/, async ({ page }, title: string) => {
  await expect(page).toHaveTitle(new RegExp(escapeRegex(title), 'i'))
})

Then(/^the main heading reads "([^"]+)"$/, async ({ page }, text: string) => {
  await steps.expectH1(page, text)
})

Then(/^I see the heading "([^"]+)"$/, async ({ page }, text: string) => {
  await steps.expectH1(page, text)
})

Then('no error message is shown in the form region', async ({ page }) => {
  const region = page.locator('form, [role="form"]').first()
  const errors = region.locator('text=/error|failed/i')
  await expect(errors).toHaveCount(0)
})

Then('I remain on the same page', async ({ page }) => {
  // Implicit: the previous step (submit) didn't redirect. If a future
  // step needs a stricter assertion (URL hash unchanged, etc.) add it
  // here. The fallthrough "no success message" check below is the
  // primary signal.
  await page.waitForLoadState('domcontentloaded')
})

Then('no success message is shown', async ({ page }) => {
  await expect(page.locator('text=/success|welcome|signed in/i')).toHaveCount(0)
})

// ─────────────────────────────────────────────────────────────
// v0.32: expanded step vocabulary so the LLM composer has more
// expressive room without inventing patterns. Each is backed by a
// matching regex in internal/composer/composer.go::registeredPatterns.
// ─────────────────────────────────────────────────────────────

Then(/^the URL contains "([^"]+)"$/, async ({ page }, fragment: string) => {
  await expect(page).toHaveURL(new RegExp(escapeRegex(fragment)))
})

Then(/^the page has at least (\d+) items$/, async ({ page }, n: string) => {
  const count = await page.locator('li, [role="listitem"], article').count()
  expect(count).toBeGreaterThanOrEqual(parseInt(n, 10))
})

When('I scroll to the bottom of the page', async ({ page }) => {
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
})

When('I open the menu', async ({ page }) => {
  // Try common menu-trigger patterns: aria-label, button text, hamburger icon.
  const triggers = [
    page.getByRole('button', { name: /menu|navigation/i }),
    page.locator('[aria-label*="menu" i]'),
    page.locator('[data-testid*="menu" i]'),
  ]
  for (const t of triggers) {
    if (await t.first().count() > 0) {
      await t.first().click()
      return
    }
  }
})

When('I close the menu', async ({ page }) => {
  await page.keyboard.press('Escape')
})

When(/^I focus the "([^"]+)" field$/, async ({ page }, field: string) => {
  await page.getByLabel(field, { exact: false }).first().focus()
})

Then(/^the "([^"]+)" field has the value "([^"]*)"$/, async ({ page }, field: string, value: string) => {
  const loc = page.getByLabel(field, { exact: false }).first()
  await expect(loc).toHaveValue(value)
})

When(/^I select "([^"]+)" from the "([^"]+)" dropdown$/, async ({ page }, option: string, dropdown: string) => {
  const sel = page.getByLabel(dropdown, { exact: false }).first()
  await sel.selectOption({ label: option })
})

When(/^I press the "([^"]+)" key$/, async ({ page }, key: string) => {
  await page.keyboard.press(key)
})

When(/^I wait for (\d+) milliseconds$/, async ({ page }, ms: string) => {
  await page.waitForTimeout(parseInt(ms, 10))
})

Then(/^the response status is (\d+)$/, async ({ page }, code: string) => {
  // Asserts the LAST navigation's status. Stored via a small fixture
  // hook; in the absence of one, falls back to a no-op.
  const status = (page as any).__lastStatus
  if (typeof status === 'number') {
    expect(status).toBe(parseInt(code, 10))
  }
})

Then(/^I scroll into view of the "([^"]+)" element$/, async ({ page }, text: string) => {
  await page.getByText(text, { exact: false }).first().scrollIntoViewIfNeeded()
})

function escapeRegex(s: string): string {
  return s.replace(/[\\^$.*+?()[\]{}|/]/g, '\\$&')
}
