/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (2 inputs, 0 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
/**
 * Generated by reviewqa. Fuzz spec for https://www.spritecloud.com.
 *
 * Bounded negative-coverage: each text input + interactive component on
 * this page gets exercised with edge-case payloads (empty, very long,
 * special chars) to surface input-handling bugs the happy-path specs
 * skip over. Capped at 5 emissions per page so triage stays tractable.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — fuzz testing: negative/edge-case input handling', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('@fuzz @negative email input field handles edge-case payloads', async ({ page }) => {
    const field = page.getByPlaceholder('Your email address').first()
    // Field accepts empty value (validation happens on submit only).
    await field.fill('')
    await expect(field).toHaveValue('')
    // Field handles very long input (5000 chars) gracefully — no crash or hang.
    const long = 'x'.repeat(5000)
    await field.fill(long)
    const persisted = await field.inputValue()
    expect(persisted.length).toBeGreaterThan(0)
    // Field safely handles HTML Injection attempt — no script execution.
    await field.fill('\'><script>alert(1)</script>')
    await expect(field).toBeAttached()
  })
})
