# Generated by quail.
#
# Gherkin contract for the browse journey on https://gohugo.io/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: Gohugo — browse journey
  As a visitor of https://gohugo.io/
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "The world's fastest framework for building websites"
    And the main heading reads "The world’s fastest framework for building websites"
    When I navigate directly to "/commands/"
    And the page title contains "Command line interface"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/commands/"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/commands/"
    When I go back in the browser history
    Then the main heading reads "The world’s fastest framework for building websites"

