/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 5 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://gohugo.io.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: GohugoIo — read journey
  As a visitor of https://gohugo.io
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey reaches its terminal page
    Given I open the landing page
    And the page title contains "The world's fastest framework for building websites"
    And the main heading reads "The world’s fastest framework for building websites"
    When I navigate directly to "/templates/new-templatesystem-overview"
    Then I see the heading "New template system in Hugo v0.146.0"
    And the page title contains "New template system in Hugo v0.146.0"

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: read — deep-link to the terminal page renders correctly
    Given I open the page "/templates/new-templatesystem-overview"
    Then I see the heading "New template system in Hugo v0.146.0"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: read — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/templates/new-templatesystem-overview"
    When I go back in the browser history
    Then the main heading reads "The world’s fastest framework for building websites"

