# Generated by quail.
#
# Gherkin contract for the read journey on https://gohugo.io/.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:read
#   npx playwright test --grep @smoke

Feature: Gohugo — read journey
  As a visitor of https://gohugo.io/
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey reaches its terminal page
    Given I open the landing page
    And the page title contains "The world's fastest framework for building websites"
    And the main heading reads "The world’s fastest framework for building websites"
    When I click the link to "/documentation/"
    And the page title contains "Hugo Documentation"

  @journey:read @priority:nice-to-have @kind:empty-state
  Scenario: read — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:read @priority:nice-to-have @kind:resume
  Scenario: read — deep-link to the terminal page renders correctly
    Given I open the page "/documentation/"

  @journey:read @priority:nice-to-have @kind:back-button
  Scenario: read — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/documentation/"
    When I go back in the browser history
    Then the main heading reads "The world’s fastest framework for building websites"

