/**
 * Generated by reviewqa.
 *
 * Print-stylesheet baseline for https://playwright.dev/community/conference-videos. Asserts the page renders
 * cleanly under media: 'print' — content visible, no overlapping
 * fixed elements, no off-screen layout. Print regressions go
 * undetected because no other test layer exercises print CSS.
 *
 * Filter: `npx playwright test --grep @kind:print`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('PlaywrightDev print layout — https://playwright.dev/community/conference-videos', () => {
  test('prints page correctly and hides non-print elements', async ({ page }) => {
    await page.goto('/community/conference-videos')
    await page.emulateMedia({ media: 'print' })
    // h1 remains visible (content preserved in print)
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeAttached()
    // Fixed banners (e.g., cookie banners) are hidden in print
    const fixedBanners = page.locator('[class*="cookie"], [class*="banner"]').filter({ visible: true })
    const cnt = await fixedBanners.count()
    expect.soft(cnt, `${cnt} fixed banners still visible under print media — likely missing @media print { display: none } rule`).toBeLessThanOrEqual(1)
  })
})

