# Generated by quail.
#
# Gherkin contract for the browse journey on https://es.wikipedia.org/wiki/Madrid.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: EsWikipedia — browse journey
  As a visitor of https://es.wikipedia.org/wiki/Madrid
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Madrid - Wikipedia, la enciclopedia libre"
    And the main heading reads "Madrid"
    When I click the link to "/wiki/Portal:Comunidad"
    Then I see the heading "Portal:Comunidad"
    And the page title contains "Portal:Comunidad - Wikipedia, la enciclopedia libre"
    When I click the link to "/wiki/Wikipedia:Portada"
    Then I see the heading "Wikipedia:Portada"
    And the page title contains "Wikipedia, la enciclopedia libre"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/wiki/Wikipedia:Portada"
    Then I see the heading "Wikipedia:Portada"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/wiki/Wikipedia:Portada"
    When I go back in the browser history
    Then the main heading reads "Madrid"

  @journey:browse @priority:standard @kind:cross-journey
  Scenario: browse — switching to landing and back leaves no broken state
    Given I open the landing page
    When I navigate directly to "/"
    And I go back in the browser history
    Then no error message is shown in the form region

