# Generated by quail.
#
# Gherkin contract for the convert journey on https://es.wikipedia.org/wiki/Madrid.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/quail.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:convert
#   npx playwright test --grep @smoke

Feature: EsWikipedia — convert journey
  As a visitor of https://es.wikipedia.org/wiki/Madrid
  I want to complete the convert flow
  So that the page delivers on its user goal

  @journey:convert @priority:critical @smoke
  Scenario: convert journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Madrid - Wikipedia, la enciclopedia libre"
    And the main heading reads "Madrid"
    When I navigate directly to "/wiki/Especial:LoQueEnlazaAqu%C3%AD/Wikipedia:Portada"
    Then I see the heading "Páginas que enlazan con «Wikipedia:Portada»"
    And the page title contains "Páginas que enlazan con «Wikipedia:Portada» - Wikipedia, la enciclopedia libre"
    # Form fill + submit (positive path)
    And I submit the form
    Then no error message is shown in the form region

  @journey:convert @priority:critical @kind:param
  Scenario Outline: convert — search accepts <variant> values
    Given I open the landing page
    When I enter "<value>" into the "search" field
    When I submit the form
    Then no error message is shown in the form region

    Examples:
      | variant   | value                                |
      | short | sample |
      | with-spaces | sample text with spaces |
      | unicode | café-niño-ümlaut |
      | emoji | hello 🎉 world 🌍 |
      | rtl-mark | test ‏rtl‎ content |
      | zero-width | sample​‌‍text |
      | with-quotes | she said "hello" & 'goodbye' |

  @journey:convert @priority:critical @kind:boundary
  Scenario: convert — long input does not break the form
    Given I open the landing page
    When I enter "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" into the "search" field
    Then no error message is shown in the form region

  @journey:convert @priority:critical @kind:tab-order
  Scenario: convert — tab order reaches the search field
    Given I open the landing page
    When I focus the "search" field
    When I enter "query" into the "search" field
    Then the "search" field has the value "query"

  @journey:convert @priority:critical @kind:empty-state
  Scenario: convert — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:convert @priority:critical @kind:resume
  Scenario: convert — deep-link to the terminal page renders correctly
    Given I open the page "/wiki/Especial:LoQueEnlazaAqu%C3%AD/Wikipedia:Portada"
    Then I see the heading "Páginas que enlazan con «Wikipedia:Portada»"

  @journey:convert @priority:critical @kind:back-button
  Scenario: convert — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/wiki/Especial:LoQueEnlazaAqu%C3%AD/Wikipedia:Portada"
    When I go back in the browser history
    Then the main heading reads "Madrid"

