# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://es.wikipedia.org/wiki/Madrid.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: EsWikipediaOrg — browse journey
  As a visitor of https://es.wikipedia.org/wiki/Madrid
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Madrid - Wikipedia, la enciclopedia libre"
    When I click the link to "/wiki/Wikipedia:Portada"
    And the page title contains "Wikipedia, la enciclopedia libre"
    When I click the link to "/wiki/Especial:P%C3%A1ginasEspeciales"
    Then I see the heading "Páginas especiales"
    And the page title contains "Páginas especiales - Wikipedia, la enciclopedia libre"

  @journey:browse @priority:standard @kind:empty-state
  Scenario: browse — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

  @journey:browse @priority:standard @kind:resume
  Scenario: browse — deep-link to the terminal page renders correctly
    Given I open the page "/wiki/Especial:P%C3%A1ginasEspeciales"
    Then I see the heading "Páginas especiales"

  @journey:browse @priority:standard @kind:back-button
  Scenario: browse — back button after navigation returns to landing
    Given I open the landing page
    When I click the link to "/wiki/Especial:P%C3%A1ginasEspeciales"
    When I go back in the browser history

