# Generated by reviewqa.
#
# Gherkin contract for the exercise journey on https://es.wikipedia.org/wiki/Wikipedia:Portada.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: EsWikipediaOrg — exercise journey
  As a visitor of https://es.wikipedia.org/wiki/Wikipedia:Portada
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Wikipedia, la enciclopedia libre"

