/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 8 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
# Generated by reviewqa.
#
# Gherkin contract for the exercise journey on https://es.wikipedia.org/wiki/Madrid.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:exercise
#   npx playwright test --grep @smoke

Feature: EsWikipediaOrg — exercise journey
  As a visitor of https://es.wikipedia.org/wiki/Madrid
  I want to complete the exercise flow
  So that the page delivers on its user goal

  @journey:exercise @priority:standard @smoke
  Scenario: exercise journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Madrid - Wikipedia, la enciclopedia libre"

  @journey:exercise @priority:standard @kind:empty-state
  Scenario: exercise — page renders the landing list
    Given I open the landing page
    Then the page has at least 1 items

