/* reviewqa quality report
 * Weak / missing locators on this page:
 *   - no data-testid attributes found on this page (0 inputs, 8 anchors). Tests rely on text/role and break under copy edits.
 * Add data-testid to these elements for stable tests.
 */
# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://es.wikipedia.org/wiki/Madrid.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: EsWikipediaOrg — browse journey
  As a visitor of https://es.wikipedia.org/wiki/Madrid
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "Madrid - Wikipedia, la enciclopedia libre"
    When I click the link to "/wiki/Wikipedia:Portada"
    And the page title contains "Wikipedia, la enciclopedia libre"
    When I click the link to "/wiki/Especial:P%C3%A1ginasEspeciales"
    Then I see the heading "Páginas especiales"
    And the page title contains "Páginas especiales - Wikipedia, la enciclopedia libre"
