/**
 * Generated by reviewqa from the live OpenAPI / Swagger document at
 * https://petstore3.swagger.io/pet/{petId}. Asserts the endpoint responds with a status code
 * declared in its `responses` block — catches the most common contract
 * violation (a 200 turns into a 500 silently, or a 400 turns into a 204).
 *
 * Schema validation of the response body is intentionally NOT included
 * — that requires a JSON Schema validator and a settled story for
 * `$ref` resolution. Add `ajv` and per-endpoint schema assertions when
 * the contract surface stabilises.
 *
 * Filter: `npx playwright test --grep @kind:contract`
 */
import { test, expect } from '@playwright/test'

const ALLOWED_STATUSES: number[] = [
  200,
  400,
]

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3SwaggerIo — contract @ https://petstore3.swagger.io/pet/{petId}', () => {
  test('@kind:contract @smoke response status is one of the declared codes', async ({ request }) => {
    let response
    switch ('post'.toLowerCase()) {
      case 'post':   response = await request.post('https://petstore3.swagger.io/pet/{petId}'); break
      case 'put':    response = await request.put('https://petstore3.swagger.io/pet/{petId}'); break
      case 'patch':  response = await request.patch('https://petstore3.swagger.io/pet/{petId}'); break
      case 'delete': response = await request.delete('https://petstore3.swagger.io/pet/{petId}'); break
      case 'head':   response = await request.head('https://petstore3.swagger.io/pet/{petId}'); break
      default:       response = await request.get('https://petstore3.swagger.io/pet/{petId}')
    }
    const status = response.status()
    console.log(`post https://petstore3.swagger.io/pet/{petId} → ${status} (allowed: ${ALLOWED_STATUSES.join(', ')})`)
    // Accept the declared statuses; tolerate sandbox-only authentication
    // gates (401/403) since contract specs run unauthenticated.
    const acceptable = ALLOWED_STATUSES.length === 0
      ? [200, 201, 204, 401, 403]
      : [...ALLOWED_STATUSES, 401, 403]
    expect(acceptable).toContain(status)
  })
})

