/**
 * Generated by quail.
 *
 * Accessibility-preferences baseline for https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen. Asserts the
 * page respects user-agent preferences for reduced motion, forced
 * colors, and elevated contrast. These media queries are mandated by
 * WCAG 2.1 SC 2.3.3 and OS-level user preferences — pages that
 * silently ignore them violate user trust and accessibility norms.
 *
 * Filter: `npx playwright test --grep @kind:a11y-prefs`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — accessibility preferences for mortgage calculator page', () => {
  test('respects OS-level reduced motion preference', async ({ browser }) => {
    const context = await browser.newContext({ reducedMotion: 'reduce' })
    const page = await context.newPage()
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    // Soft check: any element with a CSS animation should have a
    // reduced or zero duration. We snapshot one animated element if
    // it exists; absence is fine.
    const sample = page.locator('[class*="anim"], [class*="transition"]').first()
    if (await sample.count() > 0) {
      const duration = await sample.evaluate(el => getComputedStyle(el).animationDuration)
      expect.soft(duration === '0s' || duration === '' || duration.startsWith('0'), `expected reduced animation; got ${duration}`).toBeTruthy()
    }
    await context.close()
  })

  test('respects forced-colors mode (e.g., high-contrast themes)', async ({ browser }) => {
    const context = await browser.newContext({ forcedColors: 'active' })
    const page = await context.newPage()
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    await context.close()
  })

  test('respects user preference for enhanced contrast', async ({ browser }) => {
    const context = await browser.newContext({ contrast: 'more' })
    const page = await context.newPage()
    await page.goto('/particulier/hypotheek/hypotheek-berekenen', { waitUntil: 'domcontentloaded' })
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    await context.close()
  })
})
