/**
 * Generated by quail.
 *
 * Accessibility check for https://www.ing.nl/private-banking. v0.59 — depth parity: five
 * tests, each targeting a distinct accessibility concern, so the
 * report surfaces where the failure lives rather than collapsing
 * everything into one axe result.
 *
 *   smoke         — axe-core WCAG 2a/2aa/21a/21aa, serious/critical = 0
 *   wcag-aa       — WCAG 2.1 AA tags only — targeted CI gate
 *   color-contrast — most-violated WCAG rule deserves its own assertion
 *   aria-attrs    — aria-* rules standalone (valid attr, required children)
 *   form-labels   — every form input has a programmatic label
 *
 * Each block uses expect.soft() so the report surfaces all five
 * rather than short-circuiting on the first failure.
 *
 * Filter: `npx playwright test --grep @kind:a11y`
 */
import { test, expect } from '@playwright/test'
import { AxeBuilder } from '@axe-core/playwright'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — accessibility for private banking site', () => {
  test('smoke test: no serious or critical axe violations', async ({ page }) => {
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    const results = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze()
    const serious = results.violations.filter(v => v.impact === 'serious' || v.impact === 'critical')
    expect.soft(results.violations, `axe found ${results.violations.length} violation(s) total`).toEqual(results.violations)
    if (serious.length > 0) {
      console.log('serious/critical violations:', JSON.stringify(serious.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.length })), null, 2))
    }
    expect(serious).toHaveLength(0)
  })

  test('WCAG 2.1 AA compliance check', async ({ page }) => {
    // Targeted gate: many teams require AA compliance specifically.
    // Running with just the wcag21aa tag lets the report distinguish
    // AA-required failures from A-required ones in a single grep.
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    const results = await new AxeBuilder({ page })
      .withTags(['wcag21aa'])
      .analyze()
    const serious = results.violations.filter(v => v.impact === 'serious' || v.impact === 'critical')
    if (serious.length > 0) {
      console.log('AA serious/critical:', JSON.stringify(serious.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.length })), null, 2))
    }
    expect.soft(serious, `${serious.length} serious/critical WCAG 2.1 AA violations`).toHaveLength(0)
  })

  test('color contrast passes AA requirements', async ({ page }) => {
    // The single most-violated WCAG rule in production. Worth its own
    // assertion so the report surfaces contrast separately from the
    // rest of the axe bag.
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    const results = await new AxeBuilder({ page })
      .options({ runOnly: { type: 'rule', values: ['color-contrast'] } })
      .analyze()
    if (results.violations.length > 0) {
      console.log('color-contrast violations:', JSON.stringify(results.violations.map(v => ({
        nodes: v.nodes.length,
        firstSample: v.nodes[0]?.html?.slice(0, 120),
      })), null, 2))
    }
    expect.soft(results.violations, `${results.violations.length} color-contrast violation(s)`).toHaveLength(0)
  })

  test('ARIA attributes are used correctly', async ({ page }) => {
    // Catch the common ARIA mis-uses (invalid attr names, required
    // children missing, valid roles for elements). Separate gate so
    // teams can distinguish a wiring bug from a visual issue.
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    const results = await new AxeBuilder({ page })
      .options({ runOnly: { type: 'tag', values: ['cat.aria'] } })
      .analyze()
    if (results.violations.length > 0) {
      console.log('ARIA violations:', JSON.stringify(results.violations.map(v => ({
        id: v.id,
        impact: v.impact,
        nodes: v.nodes.length,
      })), null, 2))
    }
    expect.soft(results.violations, `${results.violations.length} ARIA violation(s)`).toHaveLength(0)
  })

  test('all form inputs have proper labels', async ({ page }) => {
    // Cheaper signal than axe for form-heavy pages: walk every input
    // and confirm it has <label for>, aria-label, aria-labelledby, OR
    // a placeholder (placeholder is the weakest acceptable fallback).
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    const unlabeled = await page.evaluate(() => {
      const inputs = Array.from(document.querySelectorAll('input:not([type=hidden]):not([type=submit]):not([type=button]), select, textarea')) as HTMLElement[]
      return inputs
        .filter(el => {
          const id = el.id
          if (id && document.querySelector(`label[for="${id}"]`)) return false
          if (el.closest('label')) return false
          if (el.getAttribute('aria-label')?.trim()) return false
          if (el.getAttribute('aria-labelledby')?.trim()) return false
          return true
        })
        .map(el => ({
          tag: el.tagName.toLowerCase(),
          type: (el as HTMLInputElement).type || '',
          name: (el as HTMLInputElement).name || '',
        }))
    })
    if (unlabeled.length > 0) {
      console.log('unlabeled inputs:', JSON.stringify(unlabeled, null, 2))
    }
    expect.soft(unlabeled, `${unlabeled.length} unlabeled form input(s)`).toHaveLength(0)
  })
})
