/**
 * Generated by quail.
 *
 * Browser-zoom baseline for https://www.ing.nl/private-banking. WCAG 2.1 SC 1.4.4 requires
 * pages to remain functional at 200% zoom; we test 200% and 400% as
 * a stronger guarantee. Layout breakage at zoom is the leading
 * accessibility complaint from low-vision users — catching it
 * deterministically closes a real-world gap.
 *
 * Filter: `npx playwright test --grep @kind:zoom`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — Zoom test at https://www.ing.nl/private-banking', () => {
  for (const zoom of [2.0, 4.0] as const) {
    test(`@kind:zoom @smoke @zoom:${zoom * 100}% H1 remains visible`, async ({ page }) => {
      await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
      // Playwright doesn't expose a true browser-zoom API; emulate via
      // CSS transform on the body. Real ratio differs slightly but the
      // layout-overflow signal we want is identical.
      await page.evaluate(z => {
        const b = document.body
        if (b) {
          b.style.transformOrigin = '0 0'
          b.style.transform = `scale(${z})`
          b.style.width = `${100 / z}%`
        }
      }, zoom)
      await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
    })
  }
})
