/**
 * Generated by reviewqa.
 *
 * GraphQL discovery stub for https://playwright.dev. Always emitted per origin.
 * Issues a benign introspection query against the conventional
 * endpoint (`/graphql`). When the endpoint exists, asserts the
 * `data.__schema` shape; when it 404s or 405s, the test skips
 * gracefully.
 *
 * v0.55 — depth parity with pw_api.tmpl. Six tests now: introspection
 * plus five adversarial blocks (empty-query, malformed, type-mismatch,
 * deep-nested, bare-get). Each skips when /graphql is absent so the
 * stub stays non-disruptive on sites without GraphQL.
 *
 * Activate richer schema-compat assertions by setting
 * REVIEWQA_GRAPHQL_ENDPOINT=/path/to/graphql and re-running
 * `reviewqa generate` — the deterministic OpenAPI-style contract
 * template will replace this stub.
 *
 * Filter: `npx playwright test --grep @kind:graphql-stub`
 */
import { test, expect } from '@playwright/test'

const ENDPOINT = process.env.REVIEWQA_GRAPHQL_ENDPOINT || '/graphql'
const INTROSPECTION = { query: '{ __schema { types { name } } }' }

// Probe once at module scope — every test in this file shares the
// same "is GraphQL even here?" verdict to avoid hammering the
// endpoint with 6 separate probes.
async function endpointExists(request: any): Promise<boolean> {
  const r = await request.post(ENDPOINT, {
    data: INTROSPECTION,
    headers: { 'content-type': 'application/json' },
    failOnStatusCode: false,
  })
  return !(r.status() === 404 || r.status() === 405)
}

test.describe.configure({ mode: 'parallel' })
test.describe('Playwright — GraphQL discovery @ https://playwright.dev', () => {
  test('@kind:graphql-stub @smoke introspection succeeds OR endpoint is absent', async ({ request }) => {
    const r = await request.post(ENDPOINT, {
      data: INTROSPECTION,
      headers: { 'content-type': 'application/json' },
      failOnStatusCode: false,
    })
    if (r.status() === 404 || r.status() === 405) {
      test.skip(true, `no GraphQL endpoint at ${ENDPOINT} (status ${r.status()}) — set REVIEWQA_GRAPHQL_ENDPOINT to override`)
      return
    }
    expect(r.ok(), `GraphQL endpoint ${ENDPOINT} responded ${r.status()}`).toBeTruthy()
    const body = await r.json()
    expect.soft(body.data?.__schema, 'introspection should return data.__schema').toBeTruthy()
    expect.soft(Array.isArray(body.data?.__schema?.types), 'data.__schema.types[] should be an array').toBe(true)
  })

  // ─────────────────────────────────────────────────────────────
  // v0.55: five adversarial blocks. Each skips when the endpoint
  // is absent so the stub doesn't fail on sites without GraphQL.
  // ─────────────────────────────────────────────────────────────

  test('@kind:graphql-stub @negative empty-query returns 4xx not 5xx', async ({ request }) => {
    if (!(await endpointExists(request))) { test.skip(); return }
    const r = await request.post(ENDPOINT, {
      data: { query: '' },
      headers: { 'content-type': 'application/json' },
      failOnStatusCode: false,
    })
    expect(r.status()).toBeLessThan(500)
    expect.soft(r.status(), `empty query → ${r.status()}`).toBeGreaterThanOrEqual(400)
  })

  test('@kind:graphql-stub @negative malformed-query returns 4xx not 5xx', async ({ request }) => {
    if (!(await endpointExists(request))) { test.skip(); return }
    const r = await request.post(ENDPOINT, {
      data: { query: '{ __schema { types { name' }, // unbalanced braces
      headers: { 'content-type': 'application/json' },
      failOnStatusCode: false,
    })
    expect(r.status()).toBeLessThan(500)
  })

  test('@kind:graphql-stub @negative type-mismatch in variables does not 5xx', async ({ request }) => {
    if (!(await endpointExists(request))) { test.skip(); return }
    const r = await request.post(ENDPOINT, {
      data: {
        query: 'query($depth: Int) { __schema { types { name } } }',
        variables: { depth: 'not-a-number' },
      },
      headers: { 'content-type': 'application/json' },
      failOnStatusCode: false,
    })
    expect(r.status()).toBeLessThan(500)
  })

  test('@kind:graphql-stub @negative deep-nested-query is bounded (depth-limit DoS protection)', async ({ request }) => {
    if (!(await endpointExists(request))) { test.skip(); return }
    // 12 levels deep. A server with no depth limit might cooperate
    // and serve it; one with a configured limit should 4xx; either
    // way it MUST NOT 5xx and MUST NOT hang past the test timeout.
    const deep = '{ __schema { ' + 'types { fields { type { '.repeat(12) +
                 'name' + ' } }'.repeat(12) + ' } }'
    const r = await request.post(ENDPOINT, {
      data: { query: deep },
      headers: { 'content-type': 'application/json' },
      timeout: 10_000,
      failOnStatusCode: false,
    })
    expect(r.status()).toBeLessThan(500)
  })

  test('@kind:graphql-stub @negative bare GET on /graphql is method-disciplined', async ({ request }) => {
    if (!(await endpointExists(request))) { test.skip(); return }
    // Many GraphQL servers accept GET for queries via ?query=, but
    // a bare GET with no query should 4xx (400 or 405).
    const r = await request.get(ENDPOINT, { failOnStatusCode: false })
    expect(r.status()).toBeLessThan(500)
  })
})

