/**
 * Generated by reviewqa.
 *
 * Webhook signature-verification stub for https://www.spritecloud.com. Always
 * emitted per origin. Documents the common webhook-signature
 * conventions (Stripe, GitHub, generic HMAC) and skips until the
 * consumer wires a real signing secret via env.
 *
 * Activate by:
 *   1. Set REVIEWQA_WEBHOOK_ENDPOINT=/path/to/webhook
 *   2. Set REVIEWQA_WEBHOOK_SECRET=<your-signing-secret>
 *   3. Re-run the suite
 *
 * Filter: `npx playwright test --grep @kind:webhook-stub`
 */
import { test, expect } from '@playwright/test'
import { createHmac } from 'node:crypto'

const ENDPOINT = process.env.REVIEWQA_WEBHOOK_ENDPOINT || ''
const SECRET = process.env.REVIEWQA_WEBHOOK_SECRET || ''

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — webhook signing @ https://www.spritecloud.com', () => {
  test('@kind:webhook-stub @smoke signed POST is accepted; unsigned is rejected', async ({ request }) => {
    if (!ENDPOINT || !SECRET) {
      test.skip(true, 'set REVIEWQA_WEBHOOK_ENDPOINT + REVIEWQA_WEBHOOK_SECRET to activate signature verification')
      return
    }
    const body = JSON.stringify({ ping: 'reviewqa' })
    const signature = createHmac('sha256', SECRET).update(body).digest('hex')
    // Try common signature header names; assert ≥1 succeeds.
    const headerNames = ['X-Hub-Signature-256', 'Stripe-Signature', 'X-Signature']
    let signedAccepted = false
    for (const name of headerNames) {
      const r = await request.post(ENDPOINT, {
        data: body,
        headers: { 'content-type': 'application/json', [name]: signature },
        failOnStatusCode: false,
      })
      if (r.ok()) {
        signedAccepted = true
        break
      }
    }
    expect.soft(signedAccepted, 'one of the common signature header names should be accepted with a valid HMAC').toBe(true)

    // Unsigned post should NOT be accepted.
    const unsigned = await request.post(ENDPOINT, { data: body, failOnStatusCode: false })
    expect.soft(unsigned.status(), 'unsigned webhook POST should be rejected').toBeGreaterThanOrEqual(400)
  })
})

