package main

import (
	"strings"
	"testing"
)

// A pre-v0.10.6 .feature file with the old title + Outline shape +
// component-tagged Outline must come out the other side with:
//   - URL-path-anchored Feature title
//   - "fill the X field with <example>" Outline title
//   - "<example>" placeholder in the component step
//   - "| case | example |" Examples header
//
// Non-component scenarios (legacy @kind:param Outlines) keep their
// "<value>" placeholder and "| variant | value |" header — those
// rows are filled by the existing paramRowsFor pipeline and the
// platform UI's tag filter, untouched by the migration.
func TestMigrateFeatureContent_RewritesV010_5Shape(t *testing.T) {
	in := `# Generated by quail.
Feature: test3 — browse journey
  As a visitor of https://www.ing.nl/particulier/hypotheek/hypotheek-berekenen
  I want to complete the browse flow

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page

  @journey:browse @priority:standard @kind:component @field:applicant
  Scenario Outline: ing-app-open-page — applicant accepts <variant>
    Given I open the landing page
    When I enter "<value>" into the "applicant" field

    Examples:
      | variant | value |
      | short | sample |
`
	out := string(migrateFeatureContent([]byte(in)))
	checks := []string{
		"Feature: test3 — browse · /particulier/hypotheek/hypotheek-berekenen",
		`Scenario Outline: fill the "applicant" field with <example>`,
		`When I enter "<example>" into the "applicant" field`,
		"| case | example |",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("expected %q in migrated output\n--- output ---\n%s", want, out)
		}
	}
	// The non-component scenario must NOT pick up "<example>".
	if strings.Contains(out, `Scenario: browse journey reaches its terminal page`) == false {
		t.Errorf("non-component scenario should be preserved verbatim")
	}
}

// A file already in the v0.10.7 shape should round-trip unchanged.
// The migrator is idempotent.
func TestMigrateFeatureContent_Idempotent(t *testing.T) {
	in := `Feature: test3 — browse · /particulier
  As a visitor of https://www.ing.nl/particulier

  @journey:browse @kind:component @field:bruto
  Scenario Outline: fill the "Bruto jaarinkomen" field with <example>
    When I enter "<example>" into the "Bruto jaarinkomen" field

    Examples:
      | case | example |
      | typical | 50000 |
`
	out := string(migrateFeatureContent([]byte(in)))
	if out != in {
		t.Errorf("migrator should be idempotent on already-migrated content\nin:\n%s\nout:\n%s", in, out)
	}
}

// Step-text rewrite must be scoped — a legacy @kind:param Outline
// keeps its "<value>" placeholder so the existing paramRowsFor
// machinery (which still emits "<value>" in the live template path)
// stays consistent across files.
func TestMigrateFeatureContent_LeavesParamOutlinesAlone(t *testing.T) {
	in := `Feature: x — convert journey
  As a visitor of https://x.test/

  @journey:convert @priority:critical @kind:param
  Scenario Outline: convert — Email accepts <variant> values
    When I enter "<value>" into the "Email" field

    Examples:
      | variant | value |
      | typical | jane@example.com |
`
	out := string(migrateFeatureContent([]byte(in)))
	// @kind:param step must keep <value>.
	if !strings.Contains(out, `When I enter "<value>" into the "Email" field`) {
		t.Errorf("@kind:param step should keep <value>; got:\n%s", out)
	}
	// Header stays as variant|value.
	if !strings.Contains(out, "| variant | value |") {
		t.Errorf("@kind:param Examples header should stay; got:\n%s", out)
	}
	// Feature line still gets the path treatment.
	if !strings.Contains(out, "Feature: x — convert · /") {
		t.Errorf("Feature line should get URL path; got:\n%s", out)
	}
}
