/**
 * Generated by reviewqa.
 *
 * Touch-interaction baseline for https://www.spritecloud.com. Uses an iPhone 13
 * emulation with hasTouch enabled so .tap() / long-press / swipe
 * sequences exercise the real touch pipeline. The pw_mobile template
 * covers the smoke; this template digs into the gestures a mouse-only
 * suite cannot reach.
 *
 * Filter: `npx playwright test --grep @kind:touch`
 */
import { test, expect, devices } from '@playwright/test'

test.use({ ...devices['iPhone 13'] })

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — touch gestures @ https://www.spritecloud.com', () => {
  test('@kind:touch @smoke long-press on the primary CTA does not double-fire', async ({ page }) => {
    await page.goto('/')
    const cta = page.getByRole('button').first().or(page.getByRole('link').first())
    if (await cta.count() === 0) test.skip()
    let clicks = 0
    await page.exposeFunction('__rqClicked', () => { clicks++ })
    await cta.evaluate(el => el.addEventListener('click', () => (window as any).__rqClicked()))
    // Long-press: pointer down for 800ms then up.
    const box = await cta.boundingBox()
    if (!box) test.skip()
    await page.touchscreen.tap(box!.x + box!.width / 2, box!.y + box!.height / 2)
    await page.waitForTimeout(50)
    // A single tap should fire exactly one click.
    expect.soft(clicks, 'tap should fire exactly one click').toBeLessThanOrEqual(1)
  })

  test('@kind:touch @swipe horizontal swipe on the document keeps the page interactive', async ({ page }) => {
    await page.goto('/')
    const viewport = page.viewportSize() || { width: 390, height: 844 }
    // Synthesize a swipe by chaining touchscreen taps; mobile carousels
    // & SPA gestures listen to pointer events anyway.
    await page.touchscreen.tap(viewport.width * 0.8, viewport.height / 2)
    await page.touchscreen.tap(viewport.width * 0.2, viewport.height / 2)
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})

