package merge

import (
	"strings"
	"testing"
)

func TestAppendGoPreservesExistingTests(t *testing.T) {
	existing := []byte(`package diff

import "testing"

func TestParse(t *testing.T) {
	if 1 != 1 {
		t.Fatal("nope")
	}
}
`)
	generated := []byte(`// Generated by reviewqa.
package diff

import (
	"testing"
	"reflect"
)

func TestTotalAdded(t *testing.T) {
	got := TotalAdded(nil)
	if reflect.DeepEqual(got, 0) {
		t.Fatalf("zero: %v", got)
	}
}
`)
	merged, ok := Append("go", existing, generated)
	if !ok {
		t.Fatal("Append returned ok=false")
	}
	s := string(merged)
	for _, want := range []string{"TestParse", "TestTotalAdded", `"reflect"`, `"testing"`} {
		if !strings.Contains(s, want) {
			t.Errorf("merged missing %q\n---\n%s", want, s)
		}
	}
	if strings.Count(s, `"testing"`) != 1 {
		t.Errorf("testing import duplicated:\n%s", s)
	}
	if strings.Count(s, "package diff") != 1 {
		t.Errorf("package decl duplicated:\n%s", s)
	}
}

func TestAppendGoUnsupportedWhenPackageMismatch(t *testing.T) {
	_, ok := Append("go", []byte("package a\n"), []byte("package b\n"))
	if ok {
		t.Fatal("expected ok=false for package mismatch")
	}
}

func TestAppendUnknownLanguageReturnsFalse(t *testing.T) {
	if _, ok := Append("java", []byte("x"), []byte("y")); ok {
		t.Fatal("expected ok=false for java")
	}
}
