package merge

import "regexp"

// stripQuailHeader removes the leading `/** Generated by quail. ... */`
// (TS / JS) or `# Generated by quail. ...` (Python) block from `rest`
// when it appears at the start, along with any trailing blank lines.
//
// Used by appendTS / appendPython so a second scenario inlined into an
// existing test file doesn't carry the file-level provenance block
// down with it — the existing file's header already covers that.
//
// v0.96.1.
func stripQuailHeader(rest []byte) []byte {
	if loc := reTSQuailHeader.FindIndex(rest); loc != nil && loc[0] == 0 {
		return rest[loc[1]:]
	}
	if loc := rePyQuailHeader.FindIndex(rest); loc != nil && loc[0] == 0 {
		return rest[loc[1]:]
	}
	return rest
}

// reTSQuailHeader matches a /** ... Generated by quail. ... */ block
// that starts at the very beginning of the chunk, including any
// trailing blank lines so the surviving content begins with the next
// real statement (typically `import` already stripped, or
// `test.describe(`).
var reTSQuailHeader = regexp.MustCompile(`(?s)\A\s*/\*\*.*?Generated by quail\..*?\*/\s*\n+`)

// rePyQuailHeader matches a contiguous block of `#`-comment lines at
// the start that mentions "Generated by quail." anywhere within it,
// plus trailing blank lines.
var rePyQuailHeader = regexp.MustCompile(`(?m)\A(?:#[^\n]*\n)*?#[^\n]*Generated by quail\.[^\n]*\n(?:#[^\n]*\n)*\s*\n+`)

// reSymbolInDescribe captures `test.describe('SYMBOL — ...'` so the
// dedup layer can compare describes by everything-except-the-symbol-name.
// Two `Spritecloud` and `spriteCloud` describes are otherwise byte
// identical; without this normalization they're not detectable as dups.
var reSymbolInDescribe = regexp.MustCompile(`(?m)test\.describe\(\s*['"][^—'"\n]+\s+—\s+`)

// normalizeForDedup strips Generated-by-quail headers and lowercases
// the symbol prefix in `test.describe('SYMBOL — …')` so byte-equal
// comparison catches duplicates that differ only by symbol casing
// (e.g. probe emits both 'spriteCloud' and 'Spritecloud' for the same
// page from the static + browser passes).
func normalizeForDedup(b []byte) string {
	stripped := stripQuailHeader(b)
	out := reSymbolInDescribe.ReplaceAllFunc(stripped, func(m []byte) []byte {
		// Find the closing of the SYMBOL portion (before the em-dash)
		// and lowercase that slice in place.
		dashIdx := -1
		for i := 0; i+3 < len(m); i++ {
			if m[i] == 0xE2 && m[i+1] == 0x80 && m[i+2] == 0x94 { // em-dash UTF-8
				dashIdx = i
				break
			}
		}
		if dashIdx < 0 {
			return m
		}
		out := make([]byte, len(m))
		copy(out, m)
		for i := 0; i < dashIdx; i++ {
			c := out[i]
			if c >= 'A' && c <= 'Z' {
				out[i] = c + ('a' - 'A')
			}
		}
		return out
	})
	// Collapse all runs of whitespace too — duplicate emits sometimes
	// differ by an indentation / blank-line count.
	collapsed := make([]byte, 0, len(out))
	prevSpace := false
	for _, c := range out {
		if c == ' ' || c == '\t' || c == '\n' || c == '\r' {
			if !prevSpace {
				collapsed = append(collapsed, ' ')
				prevSpace = true
			}
			continue
		}
		collapsed = append(collapsed, c)
		prevSpace = false
	}
	return string(collapsed)
}
