package merge

import (
	"strings"
	"testing"
)

const tsHeader = `/**
 * Generated by quail.
 *
 * Race-condition baseline for https://example.com/.
 *
 * Filter: ` + "`npx playwright test --grep @kind:race`" + `
 */
`

const pyHeader = `# Generated by quail.
#
# Race-condition baseline for https://example.com/.
#
`

func TestStripQuailHeaderTS(t *testing.T) {
	in := []byte(tsHeader + "\ntest.describe('x', () => {})\n")
	out := stripQuailHeader(in)
	if strings.Contains(string(out), "Generated by quail") {
		t.Errorf("header should be stripped, got: %q", out)
	}
	if !strings.HasPrefix(string(out), "test.describe(") {
		t.Errorf("expected test.describe at start, got: %q", out[:min(40, len(out))])
	}
}

func TestStripQuailHeaderPy(t *testing.T) {
	in := []byte(pyHeader + "\ndef test_x():\n    pass\n")
	out := stripQuailHeader(in)
	if strings.Contains(string(out), "Generated by quail") {
		t.Errorf("header should be stripped, got: %q", out)
	}
	if !strings.HasPrefix(string(out), "def test_x") {
		t.Errorf("expected def at start, got: %q", out[:min(40, len(out))])
	}
}

func TestStripQuailHeaderNoMatch(t *testing.T) {
	// No header — should be unchanged.
	in := []byte("import { test } from '@playwright/test'\ntest('x', () => {})\n")
	out := stripQuailHeader(in)
	if string(out) != string(in) {
		t.Errorf("expected unchanged; got %q", out)
	}
}

func TestAppendTSStripsHeaderAtSeam(t *testing.T) {
	existing := []byte(tsHeader + `import { test, expect } from '@playwright/test'

test.describe('first', () => {
  test('a', async () => {})
})
`)
	// generated has its OWN header + a new describe block.
	generated := []byte(tsHeader + `import { test, expect } from '@playwright/test'

test.describe('second', () => {
  test('b', async () => {})
})
`)
	out, _ := appendTS(existing, generated)
	// Should contain "Generated by quail" exactly once.
	if got := strings.Count(string(out), "Generated by quail"); got != 1 {
		t.Errorf("expected 1 occurrence of header, got %d in:\n%s", got, out)
	}
	// Both describes should be present.
	if !strings.Contains(string(out), `test.describe('first'`) {
		t.Errorf("first describe missing")
	}
	if !strings.Contains(string(out), `test.describe('second'`) {
		t.Errorf("second describe missing")
	}
}

func TestAppendPythonStripsHeaderAtSeam(t *testing.T) {
	existing := []byte(pyHeader + `import pytest

def test_a():
    pass
`)
	generated := []byte(pyHeader + `import pytest

def test_b():
    pass
`)
	out, _ := appendPython(existing, generated)
	if got := strings.Count(string(out), "Generated by quail"); got != 1 {
		t.Errorf("expected 1 occurrence of header, got %d in:\n%s", got, out)
	}
	if !strings.Contains(string(out), "def test_a") || !strings.Contains(string(out), "def test_b") {
		t.Errorf("both defs should be present")
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
