package merge

import "regexp"

// stripQuailHeader removes the leading `/** Generated by quail. ... */`
// (TS / JS) or `# Generated by quail. ...` (Python) block from `rest`
// when it appears at the start, along with any trailing blank lines.
//
// Used by appendTS / appendPython so a second scenario inlined into an
// existing test file doesn't carry the file-level provenance block
// down with it — the existing file's header already covers that.
//
// v0.96.1.
func stripQuailHeader(rest []byte) []byte {
	if loc := reTSQuailHeader.FindIndex(rest); loc != nil && loc[0] == 0 {
		return rest[loc[1]:]
	}
	if loc := rePyQuailHeader.FindIndex(rest); loc != nil && loc[0] == 0 {
		return rest[loc[1]:]
	}
	return rest
}

// reTSQuailHeader matches a /** ... Generated by quail. ... */ block
// that starts at the very beginning of the chunk, including any
// trailing blank lines so the surviving content begins with the next
// real statement (typically `import` already stripped, or
// `test.describe(`).
var reTSQuailHeader = regexp.MustCompile(`(?s)\A\s*/\*\*.*?Generated by quail\..*?\*/\s*\n+`)

// rePyQuailHeader matches a contiguous block of `#`-comment lines at
// the start that mentions "Generated by quail." anywhere within it,
// plus trailing blank lines.
var rePyQuailHeader = regexp.MustCompile(`(?m)\A(?:#[^\n]*\n)*?#[^\n]*Generated by quail\.[^\n]*\n(?:#[^\n]*\n)*\s*\n+`)
