/**
 * Generated by quail.
 *
 * Integration-layer OBSERVABILITY SCAFFOLD for https://books.toscrape.com. Emitted
 * when the probe observed X-Request-Id, traceparent, X-Trace-Id, or
 * Server-Timing headers — strong signals that the origin is wired to
 * a tracing pipeline. Skipped until the consumer declares a tracing
 * backend.
 *
 * To activate:
 *   1. Declare a `tracing:` block in quail.yml (backend: jaeger /
 *      tempo / honeycomb; collector endpoint).
 *   2. Re-run `quail generate`.
 *
 * Filter: `npx playwright test --grep @kind:integration-obs`
 */
import { test, expect } from '@playwright/test'

test.describe('BooksToscrape — integration: observability scaffold (skipped)', () => {
  test.skip('@kind:integration-obs @wireable @trace-propagation traceparent header propagates downstream', async ({ request }) => {
    // When wired:
    //   1. Issue a request with traceparent: 00-<traceId>-<spanId>-01
    //   2. Confirm the downstream service receives the same trace-id
    //   3. Confirm a child span was emitted to the tracing backend
    const r = await request.get('/', {
      headers: { traceparent: '00-' + 'a'.repeat(32) + '-' + 'b'.repeat(16) + '-01' },
    })
    expect(r.ok()).toBeTruthy()
  })

  test.skip('@kind:integration-obs @wireable @request-id every response carries an X-Request-Id', async ({ request }) => {
    // When wired:
    //   1. Issue 10 requests with no X-Request-Id
    //   2. Confirm every response.headers['x-request-id'] is set + unique
    //   3. Confirm log lines for each request reference that id
    const r = await request.get('/')
    expect(r.headers()['x-request-id']).toBeTruthy()
  })

  test.skip('@kind:integration-obs @wireable @server-timing critical-path metrics are reported', async ({ request }) => {
    // When wired:
    //   1. Issue request; parse Server-Timing header
    //   2. Confirm db, cache, render phases are reported
    //   3. Confirm sum-of-phases ≈ total request duration
    const r = await request.get('/')
    expect(r.headers()['server-timing']).toBeTruthy()
  })
})

