package serve

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func init() {
	// Deterministic backup timestamp for the edit suite — keeps the
	// per-edit history directory predictable.
	backupTimestamp = func() string { return "20260618-000000" }
}

const editableFeature = `# Generated by quail.

Feature: Example — read journey

  @journey:read @smoke
  Scenario: lands on the terminal page
    Given I open the landing page
    Then I see the heading "About"

  @journey:read @kind:resume
  Scenario: deep-link to the terminal page
    Given I open the page "/about"
    Then I see the heading "About"
`

func writeFixture(t *testing.T, body string) (root, featurePath string) {
	t.Helper()
	root = t.TempDir()
	featurePath = filepath.Join(root, "tests", "e2e", "features", "demo.feature")
	mustWrite(t, featurePath, body)
	return
}

func TestFindScenarioRange_TagBlockIncluded(t *testing.T) {
	lines := strings.Split(editableFeature, "\n")
	rng, ok := findScenarioRange(lines, "lands on the terminal page")
	if !ok {
		t.Fatal("scenario not found")
	}
	// The @journey:read @smoke line must be the start.
	if !strings.HasPrefix(strings.TrimSpace(lines[rng.Start]), "@") {
		t.Errorf("expected range to start at the @tag line; got %q", lines[rng.Start])
	}
}

func TestDeleteScenario_RemovesBlockAndBacksUp(t *testing.T) {
	root, path := writeFixture(t, editableFeature)
	history := filepath.Join(root, "tests", "e2e", ".quail-history")
	n, err := DeleteScenario(path, "lands on the terminal page", history)
	if err != nil {
		t.Fatalf("delete: %v", err)
	}
	if n != 1 {
		t.Errorf("expected 1 deleted, got %d", n)
	}
	b, _ := os.ReadFile(path)
	if strings.Contains(string(b), "lands on the terminal page") {
		t.Errorf("scenario name still present after delete:\n%s", b)
	}
	if !strings.Contains(string(b), "deep-link to the terminal page") {
		t.Errorf("the other scenario was removed unintentionally")
	}
	// Backup must exist.
	backupPath := filepath.Join(history, "20260618-000000", "demo.feature")
	if _, err := os.Stat(backupPath); err != nil {
		t.Errorf("expected backup at %s, got err %v", backupPath, err)
	}
}

func TestDeleteScenario_ScenarioMissing(t *testing.T) {
	_, path := writeFixture(t, editableFeature)
	if _, err := DeleteScenario(path, "nonexistent", t.TempDir()); err == nil {
		t.Errorf("expected error for missing scenario")
	}
}

func TestReplaceScenario_KeepsRestUntouched(t *testing.T) {
	root, path := writeFixture(t, editableFeature)
	history := filepath.Join(root, "tests", "e2e", ".quail-history")
	newBlock := `  @journey:read @smoke @edited
  Scenario: lands on the terminal page (renamed)
    Given I open the landing page
    When I navigate directly to "/about"
    Then I see the heading "About"`
	newName, err := ReplaceScenario(path, "lands on the terminal page", newBlock, history)
	if err != nil {
		t.Fatalf("replace: %v", err)
	}
	if newName != "lands on the terminal page (renamed)" {
		t.Errorf("rename: got %q", newName)
	}
	b, _ := os.ReadFile(path)
	src := string(b)
	if !strings.Contains(src, "lands on the terminal page (renamed)") {
		t.Errorf("renamed scenario not in output:\n%s", src)
	}
	if strings.Contains(src, "lands on the terminal page\n    Given I open the landing page\n    Then I see the heading \"About\"\n") {
		t.Errorf("old scenario block still present:\n%s", src)
	}
	if !strings.Contains(src, "deep-link to the terminal page") {
		t.Errorf("other scenario lost:\n%s", src)
	}
}

func TestReplaceScenario_RejectsInvalidBlock(t *testing.T) {
	root, path := writeFixture(t, editableFeature)
	history := filepath.Join(root, ".history")
	if _, err := ReplaceScenario(path, "lands on the terminal page", "not even close", history); err == nil {
		t.Errorf("expected error for non-Gherkin block")
	}
}

func TestReplaceScenario_RejectsMultipleScenarios(t *testing.T) {
	root, path := writeFixture(t, editableFeature)
	history := filepath.Join(root, ".history")
	multi := `Scenario: A
    Given x

Scenario: B
    Given y`
	if _, err := ReplaceScenario(path, "lands on the terminal page", multi, history); err == nil {
		t.Errorf("expected error for multi-scenario block")
	}
}

func TestAppendScenario_AddsAtEnd(t *testing.T) {
	root, path := writeFixture(t, editableFeature)
	history := filepath.Join(root, ".history")
	newBlock := `  @new
  Scenario: brand new path
    Given I open the landing page
    Then I see the heading "Welcome"`
	name, err := AppendScenario(path, newBlock, history)
	if err != nil {
		t.Fatalf("append: %v", err)
	}
	if name != "brand new path" {
		t.Errorf("name: got %q", name)
	}
	b, _ := os.ReadFile(path)
	src := string(b)
	if !strings.Contains(src, "brand new path") {
		t.Errorf("new scenario missing:\n%s", src)
	}
	if !strings.HasSuffix(strings.TrimRight(src, "\n"), `Then I see the heading "Welcome"`) {
		t.Errorf("expected new scenario at EOF; got tail:\n%s", src[len(src)-200:])
	}
}

func TestHandler_ScenarioDelete(t *testing.T) {
	root := fixtureProject(t)
	srv := httptest.NewServer(Handler(root))
	defer srv.Close()
	req, _ := http.NewRequest(http.MethodDelete, srv.URL+"/api/scenario?feature=tests/e2e/features/demo.feature&name=read+journey+lands+on+the+terminal+page", nil)
	resp, err := srv.Client().Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		buf := make([]byte, 1024)
		n, _ := resp.Body.Read(buf)
		t.Fatalf("delete status: got %d body=%s", resp.StatusCode, buf[:n])
	}
	var got map[string]int
	if err := json.NewDecoder(resp.Body).Decode(&got); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if got["deleted"] != 1 {
		t.Errorf("expected deleted=1, got %v", got)
	}
}

func TestHandler_ScenarioPatchValidatesBlock(t *testing.T) {
	root := fixtureProject(t)
	srv := httptest.NewServer(Handler(root))
	defer srv.Close()
	body, _ := json.Marshal(map[string]string{"gherkin": "not a scenario"})
	req, _ := http.NewRequest(http.MethodPatch, srv.URL+"/api/scenario?feature=tests/e2e/features/demo.feature&name=read+journey+lands+on+the+terminal+page", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	resp, err := srv.Client().Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", resp.StatusCode)
	}
}

func TestHandler_ScenarioAppend(t *testing.T) {
	root := fixtureProject(t)
	srv := httptest.NewServer(Handler(root))
	defer srv.Close()
	newBlock := "Scenario: appended\n  Given I open the landing page\n"
	body, _ := json.Marshal(map[string]string{"gherkin": newBlock})
	resp, err := http.Post(srv.URL+"/api/scenario?feature=tests/e2e/features/demo.feature", "application/json", bytes.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		buf := make([]byte, 1024)
		n, _ := resp.Body.Read(buf)
		t.Fatalf("status: %d body=%s", resp.StatusCode, buf[:n])
	}
	// Re-fetch and confirm the appended Scenario lives.
	got, err := http.Get(srv.URL + "/api/feature?path=tests/e2e/features/demo.feature")
	if err != nil {
		t.Fatal(err)
	}
	defer got.Body.Close()
	var pulled struct {
		Feature Feature `json:"feature"`
	}
	json.NewDecoder(got.Body).Decode(&pulled)
	found := false
	for _, s := range pulled.Feature.Scenarios {
		if s.Name == "appended" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("appended scenario not visible after refetch: %+v", pulled.Feature.Scenarios)
	}
}
