package serve

import "testing"

const sampleFeature = `# Generated by reviewqa.
#
# Gherkin contract for the read journey on https://example.com.

Feature: Example — read journey
  As a visitor of https://example.com
  I want to complete the read flow
  So that the page delivers on its user goal

  @journey:read @priority:nice-to-have @smoke
  Scenario: read journey lands on the terminal page
    Given I open the landing page
    And the page title contains "Welcome"
    When I navigate directly to "/about"
    Then I see the heading "About"

  @journey:read @kind:resume
  Scenario: deep-linking to the terminal page loads correctly
    Given I open the page "/about"
    Then I see the heading "About"
`

func TestParseFeatureBytes_FeatureNameAndTags(t *testing.T) {
	f, err := ParseFeatureBytes([]byte(sampleFeature))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if f.Name != "Example — read journey" {
		t.Errorf("feature name mismatch: %q", f.Name)
	}
	if len(f.Scenarios) != 2 {
		t.Fatalf("expected 2 scenarios, got %d", len(f.Scenarios))
	}
}

func TestParseFeatureBytes_ScenarioTags(t *testing.T) {
	f, _ := ParseFeatureBytes([]byte(sampleFeature))
	got := f.Scenarios[0].Tags
	want := []string{"@journey:read", "@priority:nice-to-have", "@smoke"}
	if len(got) != len(want) {
		t.Fatalf("scenario 0 tags: got %v want %v", got, want)
	}
	for i, w := range want {
		if got[i] != w {
			t.Errorf("scenario 0 tag[%d]: got %q want %q", i, got[i], w)
		}
	}
}

func TestParseFeatureBytes_StepKeywordsAndText(t *testing.T) {
	f, _ := ParseFeatureBytes([]byte(sampleFeature))
	steps := f.Scenarios[0].Steps
	if len(steps) != 4 {
		t.Fatalf("expected 4 steps, got %d", len(steps))
	}
	cases := []struct{ kw, text string }{
		{"Given", "I open the landing page"},
		{"And", `the page title contains "Welcome"`},
		{"When", `I navigate directly to "/about"`},
		{"Then", `I see the heading "About"`},
	}
	for i, c := range cases {
		if steps[i].Keyword != c.kw {
			t.Errorf("step[%d] keyword: got %q want %q", i, steps[i].Keyword, c.kw)
		}
		if steps[i].Text != c.text {
			t.Errorf("step[%d] text: got %q want %q", i, steps[i].Text, c.text)
		}
	}
}

func TestParseFeatureBytes_NarrativeCaptured(t *testing.T) {
	f, _ := ParseFeatureBytes([]byte(sampleFeature))
	if f.Narrative == "" {
		t.Errorf("expected narrative to be populated")
	}
}

func TestParseFeatureBytes_StepValidity(t *testing.T) {
	src := `Feature: validity demo

  Scenario: mixed validity
    Given I open the landing page
    Then the form contains an email address field
`
	f, _ := ParseFeatureBytes([]byte(src))
	if len(f.Scenarios) != 1 || len(f.Scenarios[0].Steps) != 2 {
		t.Fatalf("unexpected shape: %+v", f)
	}
	steps := f.Scenarios[0].Steps
	if !steps[0].Valid {
		t.Errorf("step 0 (Given I open the landing page) should be Valid=true")
	}
	if steps[1].Valid {
		t.Errorf("step 1 (hallucinated 'the form contains an email address field') should be Valid=false")
	}
}

func TestParseFeatureBytes_EmptyDocument(t *testing.T) {
	f, err := ParseFeatureBytes([]byte("# only a comment\n\n"))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if f.Name != "" || len(f.Scenarios) != 0 {
		t.Errorf("expected empty feature for comment-only doc, got %+v", f)
	}
}
