/**
 * Generated by reviewqa.
 *
 * GraphQL discovery stub for https://petstore3.swagger.io. Always emitted per origin.
 * Issues a benign introspection query against the conventional
 * endpoint (`/graphql`). When the endpoint exists, asserts the
 * `data.__schema` shape; when it 404s or 405s, the test skips
 * gracefully.
 *
 * Activate richer schema-compat assertions by setting
 * REVIEWQA_GRAPHQL_ENDPOINT=/path/to/graphql and re-running
 * `reviewqa generate` — the deterministic OpenAPI-style contract
 * template will replace this stub.
 *
 * Filter: `npx playwright test --grep @kind:graphql-stub`
 */
import { test, expect } from '@playwright/test'

const ENDPOINT = process.env.REVIEWQA_GRAPHQL_ENDPOINT || '/graphql'
const INTROSPECTION = { query: '{ __schema { types { name } } }' }

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3SwaggerIo — GraphQL discovery @ https://petstore3.swagger.io', () => {
  test('@kind:graphql-stub @smoke introspection succeeds OR endpoint is absent', async ({ request }) => {
    const r = await request.post(ENDPOINT, {
      data: INTROSPECTION,
      headers: { 'content-type': 'application/json' },
      failOnStatusCode: false,
    })
    if (r.status() === 404 || r.status() === 405) {
      test.skip(true, `no GraphQL endpoint at ${ENDPOINT} (status ${r.status()}) — set REVIEWQA_GRAPHQL_ENDPOINT to override`)
      return
    }
    expect(r.ok(), `GraphQL endpoint ${ENDPOINT} responded ${r.status()}`).toBeTruthy()
    const body = await r.json()
    expect.soft(body.data?.__schema, 'introspection should return data.__schema').toBeTruthy()
    expect.soft(Array.isArray(body.data?.__schema?.types), 'data.__schema.types[] should be an array').toBe(true)
  })
})

