/**
 * Generated by reviewqa.
 *
 * API contract test — exercises the endpoint a form on the page submits
 * to, decoupled from the UI flow. Lives alongside the UI happy-flow
 * so a regression in either layer surfaces at the right altitude:
 *   - happy-flow (*.spec.ts): "the form on /contact still works end-to-end"
 *   - this file (*.api.spec.ts): "POST https://playwright.dev/search still accepts our shape"
 *
 * Endpoint:     https://playwright.dev/search
 * Method:       post
 * EncType:      application/x-www-form-urlencoded (default)
 *
 * Filter to API tests only: `npx playwright test --grep @kind:api`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('PlaywrightDev API contract — POST /search endpoint', () => {

  test('API smoke test — valid form payload returns success status', async ({ request }) => {
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': 'test',
        '': '',
      },
    })
    // 2xx OR a 3xx redirect (post-redirect-get) is acceptable; many
    // marketing forms 302 to a thank-you page.
    expect(response.status()).toBeLessThan(400)
  })

  test('API negative test — large payload is rejected gracefully (no 5xx)', async ({ request }) => {
    const huge = 'a'.repeat(50_000)
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': huge,
        '': '',
      },
    })
    // Truncated / 413 / 400 all acceptable; what we DON'T want is a 5xx.
    expect(response.status()).toBeLessThan(500)
  })

  test('API negative test — wrong HTTP method returns client error', async ({ request }) => {
    // GET on a POST endpoint is the cheapest method-mismatch we can hit.
    const response = await request.get('https://playwright.dev/search')
    // 405 Method Not Allowed is the textbook answer; 404 is also common
    // when the endpoint is method-specific.
    expect([400, 401, 403, 404, 405]).toContain(response.status())
  })

  // ─────────────────────────────────────────────────────────────
  // v0.50: extended form-negative coverage. The deck-cited "15-25
  // negatives per form" target needs more than 4 default cases —
  // each block below covers a value class an adversarial QA would
  // test by hand. None of these assert success; they each assert
  // the server doesn't 5xx and doesn't leak a stack trace.
  // ─────────────────────────────────────────────────────────────

  test('API negative test — unicode characters handled safely (no 5xx)', async ({ request }) => {
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': 'café-niño-用户-🎉-test',
        '': 'café-niño-用户-🎉-',
      },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('API negative test — SQL-like input is sanitized (no 5xx or leaked errors)', async ({ request }) => {
    // Tests the server's input sanitization. The contract: MUST NOT
    // 5xx and MUST NOT echo back unescaped fragments.
    const payload = "'; DROP TABLE users; --"
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': payload,
        '': payload,
      },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('sqlstate')
    expect.soft(body.toLowerCase()).not.toContain('syntax error')
  })

  test('API negative test — XSS-like input is escaped or blocked', async ({ request }) => {
    const payload = '<script>window.__rqXSS=1</script>'
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': payload,
        '': payload,
      },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body).not.toContain('<script>window.__rqXSS=1</script>')
  })

  test('API negative test — null-byte payloads handled safely (no 5xx)', async ({ request }) => {
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': 'value\x00malicious',
        '': 'value\x00malicious',
      },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('API negative test — burst requests are either rate-limited or handled without crashes', async ({ request }) => {
    // 10 concurrent identical requests. Either the server rate-limits
    // (429) — fine — or it serves all 10 without 5xx-ing.
    const body = {
      '': 'test',
      '': '',
    }
    const responses = await Promise.all(
      Array.from({ length: 10 }, () => request.post('https://playwright.dev/search', { form: body }))
    )
    for (const r of responses) {
      expect.soft(r.status(), `burst response status ${r.status()}`).toBeLessThan(500)
    }
  })
})

