/**
 * Generated by reviewqa.
 *
 * API contract test — exercises the endpoint a form on the page submits
 * to, decoupled from the UI flow. Lives alongside the UI happy-flow
 * so a regression in either layer surfaces at the right altitude:
 *   - happy-flow (*.spec.ts): "the form on /contact still works end-to-end"
 *   - this file (*.api.spec.ts): "POST https://playwright.dev/search still accepts our shape"
 *
 * Endpoint:     https://playwright.dev/search
 * Method:       post
 * EncType:      application/x-www-form-urlencoded (default)
 *
 * Filter to API tests only: `npx playwright test --grep @kind:api`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('PlaywrightDev — API contract @ https://playwright.dev/search', () => {

  test('@kind:api @smoke happy: realistic body returns 2xx', async ({ request }) => {
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': 'test',
        '': '',
      },
    })
    // 2xx OR a 3xx redirect (post-redirect-get) is acceptable; many
    // marketing forms 302 to a thank-you page.
    expect(response.status()).toBeLessThan(400)
  })

  test('@kind:api @negative oversized payload does not 5xx', async ({ request }) => {
    const huge = 'a'.repeat(50_000)
    const response = await request.post('https://playwright.dev/search', {
      form: {
        '': huge,
        '': '',
      },
    })
    // Truncated / 413 / 400 all acceptable; what we DON'T want is a 5xx.
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:api @negative wrong method returns 4xx', async ({ request }) => {
    // GET on a POST endpoint is the cheapest method-mismatch we can hit.
    const response = await request.get('https://playwright.dev/search')
    // 405 Method Not Allowed is the textbook answer; 404 is also common
    // when the endpoint is method-specific.
    expect([400, 401, 403, 404, 405]).toContain(response.status())
  })
})
