/**
 * Generated by reviewqa.
 *
 * Mobile-web smoke for https://www.spritecloud.com. Re-runs the journey under iPhone 13
 * emulation with touch enabled. Catches breakage that only appears at
 * mobile breakpoints + interaction modes (tap vs click, no hover).
 *
 * Filter: `npx playwright test --grep @kind:mobile`
 */
import { test, expect, devices } from '@playwright/test'

test.use({ ...devices['iPhone 13'] })

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — mobile-web @ https://www.spritecloud.com', () => {
  test('@kind:mobile @smoke iPhone 13 viewport renders without breakage', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('h1').first()).toBeVisible()
    // Touch tap on the primary CTA, when present.
    const cta = page.getByRole('link').first()
    if (await cta.count() > 0) {
      await cta.tap().catch(() => {})
    }
  })
})

