// Generated by reviewqa. Review and extend with edge cases.
package mindmap

import (
	"testing"
	"reflect"
)

func TestTagsFromPage(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		got := TagsFromPage(nil)
		if reflect.DeepEqual(got, *new([]string)) {
			t.Fatalf("got zero value: %#v", got)
		}
	})

	t.Run("returns expected type", func(t *testing.T) {
		got := TagsFromPage(nil)
		if got, want := reflect.TypeOf(got), reflect.TypeOf(*new([]string)); got != want {
			t.Fatalf("type = %v, want %v", got, want)
		}
	})
}
