/**
 * Generated by reviewqa.
 *
 * Performance baseline for https://books.toscrape.com/index.html. Asserts the page loads under
 * the configured SLO (default 3000ms; override via PERF_SLO_MS env).
 * Single-request latency check — NOT load testing.
 *
 * Filter: `npx playwright test --grep @kind:perf`
 */
import { test, expect } from '@playwright/test'

const SLO_MS = Number(process.env.PERF_SLO_MS ?? 3000)

test.describe.configure({ mode: 'parallel' })
test.describe('BooksToscrape — performance @ https://books.toscrape.com/index.html', () => {
  test(`@kind:perf @smoke loads under ${SLO_MS}ms`, async ({ page }) => {
    const start = Date.now()
    await page.goto('/index.html', { waitUntil: 'load' })
    const elapsed = Date.now() - start
    console.log(`load time: ${elapsed}ms (SLO ${SLO_MS}ms)`)
    expect.soft(elapsed, `load took ${elapsed}ms — over SLO ${SLO_MS}ms`).toBeLessThan(SLO_MS)
    // Hard fail at 2x SLO so a deeply broken site still surfaces.
    expect(elapsed).toBeLessThan(SLO_MS * 2)
  })
})

