/**
 * Generated by quail.
 *
 * Visual baselines for interaction states (default, hover, focus) of primary interactive elements on https://www.ing.nl/private-banking. Screenshots are captured and compared against committed PNGs to catch subtle visual regressions not visible at the viewport level.
 *
 * First run captures baselines; subsequent runs diff:
 *   npm run test:visual-update  # capture / refresh
 *   npx playwright test --grep @kind:visual-state
 *
 * Filter: `npx playwright test --grep @kind:visual-state`
 */
import { test, expect } from '@playwright/test'

const STATES = ['default', 'hover', 'focus'] as const

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — interaction-state visual @ https://www.ing.nl/private-banking', () => {
  test('Smoke test: primary CTA visuals across default, hover, and focus states', async ({ page }) => {
    await page.goto('/private-banking')
    await page.waitForLoadState('networkidle').catch(() => {})
    const target = page.getByRole('link').first()
    if (await target.count() === 0) {
      test.skip(true, 'No primary CTA found on this page')
      return
    }

    for (const state of STATES) {
      switch (state) {
        case 'hover':
          await target.hover().catch(() => {})
          break
        case 'focus':
          await target.focus().catch(() => {})
          break
        default:
          // default state — no interaction
          break
      }
      await expect(target).toHaveScreenshot(`ing-cta-${state}.png`, {
        maxDiffPixelRatio: 0.02,
        animations: 'disabled',
      })
    }
  })
})
