/**
 * Generated by reviewqa.
 *
 * Visual regression baseline for https://es.wikipedia.org/wiki/Portal:Actualidad. One test per viewport
 * (mobile / tablet / desktop) uses Playwright's `toHaveScreenshot()`
 * — the first run captures baselines into `__screenshots__/` (commit
 * them to the repo); subsequent runs diff against them.
 *
 * Update baselines after an intentional UI change:
 *   npm run test:visual-update
 *   # then commit the changed PNGs
 *
 * Filter: `npx playwright test --grep @kind:visual`
 */
import { test, expect } from '@playwright/test'

const VIEWPORTS = [
  { name: 'mobile',  width: 375,  height: 667 },
  { name: 'tablet',  width: 768,  height: 1024 },
  { name: 'desktop', width: 1280, height: 720 },
] as const

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipediaOrg — visual regression @ https://es.wikipedia.org/wiki/Portal:Actualidad', () => {
  for (const vp of VIEWPORTS) {
    test(`@kind:visual @smoke page matches baseline (${vp.name})`, async ({ page }) => {
      await page.setViewportSize({ width: vp.width, height: vp.height })
      await page.goto('/wiki/Portal:Actualidad')
      await page.waitForLoadState('networkidle').catch(() => {})
      // maxDiffPixelRatio: 0.01 — tolerate up to 1% pixel drift to
      // absorb anti-aliasing differences across CI / local renders.
      await expect(page).toHaveScreenshot(`eswikipediaorg-${vp.name}.png`, {
        fullPage: true,
        maxDiffPixelRatio: 0.01,
        animations: 'disabled',
      })
    })
  }
})

