/**
 * Generated by reviewqa.
 *
 * Mobile-web smoke for https://es.wikipedia.org/wiki/Especial:CambiosRecientes. v0.56 — depth parity. Where the
 * pre-v0.56 template emitted a single iPhone-13 test, this version
 * iterates a deterministic device matrix and runs the smoke plus an
 * orientation flip on each, giving 8 tests per page (4 devices ×
 * 2 scenarios).
 *
 * The device list is conservative: the four shapes that catch ~95%
 * of real-world mobile regressions (small iPhone, mid Android phone,
 * tablet portrait, large-screen Android). Add more by extending
 * DEVICES; Playwright ships ~50 device profiles via `devices`.
 *
 * Filter: `npx playwright test --grep @kind:mobile`
 */
import { test, expect, devices } from '@playwright/test'

const DEVICES = ['iPhone 13', 'Pixel 5', 'iPad Pro 11', 'Galaxy S9+'] as const

test.describe.configure({ mode: 'parallel' })

for (const deviceName of DEVICES) {
  test.describe(`EsWikipediaOrg — mobile-web @ ${deviceName} @ https://es.wikipedia.org/wiki/Especial:CambiosRecientes`, () => {
    test.use({ ...devices[deviceName] })

    test(`@kind:mobile @smoke @device:${deviceName} viewport renders without breakage`, async ({ page }) => {
      await page.goto('/wiki/Especial:CambiosRecientes')
      await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
      // Touch tap on the primary CTA, when present.
      const cta = page.getByRole('link').first()
      if (await cta.count() > 0) {
        await cta.tap().catch(() => {})
      }
    })

    test(`@kind:mobile @orientation @device:${deviceName} landscape rotation keeps the page interactive`, async ({ browser }) => {
      // Playwright doesn't expose a runtime `setViewportSize` for the
      // *emulated* device's orientation, so we rebuild a context with
      // the height/width swapped. Same engine, same UA, same DPR.
      const profile = devices[deviceName]
      const portrait = profile.viewport
      if (!portrait) test.skip()
      const ctx = await browser.newContext({
        ...profile,
        viewport: { width: portrait!.height, height: portrait!.width },
      })
      const page = await ctx.newPage()
      await page.goto('/wiki/Especial:CambiosRecientes')
      await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
      await ctx.close()
    })
  })
}

