# Generated by reviewqa.
#
# Gherkin contract for the browse journey on https://books.toscrape.com.
#
# This .feature file is EXECUTED by playwright-bdd at test time.
# Step definitions live in `tests/e2e/steps/reviewqa.steps.ts` and bind
# each Given/When/Then to the helper verbs in `tests/e2e/lib/steps.ts`.
#
# Tag filtering:
#   npx playwright test --grep @priority:critical
#   npx playwright test --grep @journey:browse
#   npx playwright test --grep @smoke

Feature: BooksToscrapeCom — browse journey
  As a visitor of https://books.toscrape.com
  I want to complete the browse flow
  So that the page delivers on its user goal

  @journey:browse @priority:standard @smoke
  Scenario: browse journey reaches its terminal page
    Given I open the landing page
    And the page title contains "All products | Books to Scrape - Sandbox"
    And the main heading reads "All products"
    When I click the link to "/catalogue/category/books_1/index.html"
    Then I see the heading "Books"
    And the page title contains "Books | 
     Books to Scrape - Sandbox"
