/**
 * Generated by quail.
 *
 * Print-stylesheet baseline for https://www.ing.nl/private-banking: ensures the page renders cleanly in print mode — content is visible, no overlapping fixed elements, no off-screen layout. Print regressions would otherwise go undetected.
 *
 * Filter: `npx playwright test --grep @kind:print`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — print @ www.ing.nl/private-banking', () => {
  test('@kind:print @smoke renders in print mode', async ({ page }) => {
    await page.goto('/private-banking', { waitUntil: 'domcontentloaded' })
    await page.emulateMedia({ media: 'print' })
    // h1 must still be in the document. Some sites hide the entire
    // chrome under @media print — that's fine — but the content has
    // to remain.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeAttached()
    // Fixed-position elements shouldn't overlap content in print.
    // Soft check that any fixed banners (eg. cookie banners) are not
    // visible under print media — a frequent regression.
    const fixedBanners = page.locator('[class*="cookie"], [class*="banner"]').filter({ visible: true })
    const cnt = await fixedBanners.count()
    expect.soft(cnt, `${cnt} fixed banners still visible under print media — likely missing @media print { display: none } rule`).toBeLessThanOrEqual(1)
  })
})
