/**
 * Generated by quail.
 *
 * Print-stylesheet baseline for https://www.ing.nl/zakelijk. Asserts the page renders
 * cleanly under media: 'print' — content visible, no overlapping
 * fixed elements, no off-screen layout. Print regressions go
 * undetected because no other test layer exercises print CSS.
 *
 * Filter: `npx playwright test --grep @kind:print`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('ING — print style test for https://www.ing.nl/zakelijk', () => {
  test('renders cleanly under print media', async ({ page }) => {
    await page.goto('/zakelijk', { waitUntil: 'domcontentloaded' })
    await page.emulateMedia({ media: 'print' })
    // H1 heading must still be visible — no blank pages
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeAttached()
    // Ensure no fixed banners (e.g., cookies) overlap content in print
    const fixedBanners = page.locator('[class*="cookie"], [class*="banner"]').filter({ visible: true })
    const cnt = await fixedBanners.count()
    expect.soft(cnt, `${cnt} fixed banners still visible under print media — likely missing @media print { display: none } rule`).toBeLessThanOrEqual(1)
  })
})
