/**
 * Generated by reviewqa.
 *
 * Print-stylesheet baseline for https://es.wikipedia.org/wiki/Madrid. Asserts the page renders
 * cleanly under media: 'print' — content visible, no overlapping
 * fixed elements, no off-screen layout. Print regressions go
 * undetected because no other test layer exercises print CSS.
 *
 * Filter: `npx playwright test --grep @kind:print`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipediaOrg — print @ https://es.wikipedia.org/wiki/Madrid', () => {
  test('@kind:print @smoke renders under media: print', async ({ page }) => {
    await page.goto('/wiki/Madrid')
    await page.emulateMedia({ media: 'print' })
    // h1 must still be in the document. Some sites hide the entire
    // chrome under @media print — that's fine — but the content has
    // to remain.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeAttached()
    // Fixed-position elements shouldn't overlap content in print.
    // Soft check that any fixed banners (eg. cookie banners) are not
    // visible under print media — a frequent regression.
    const fixedBanners = page.locator('[class*="cookie"], [class*="banner"]').filter({ visible: true })
    const cnt = await fixedBanners.count()
    expect.soft(cnt, `${cnt} fixed banners still visible under print media — likely missing @media print { display: none } rule`).toBeLessThanOrEqual(1)
  })
})

