/**
 * Generated by quail.
 *
 * Performance baseline for https://www.ing.nl/particulier. Asserts the page loads under
 * the configured SLO (default 5000ms; override via PERF_SLO_MS env).
 * Single-request latency check — NOT load testing.
 *
 * v0.97.1 — default SLO bumped 3000ms → 5000ms. The 3s default was
 * tight for image-heavy marketing sites (Webflow, Wix). 5s is the
 * "good" Web Vitals LCP threshold; under that you're not blocking
 * users. Apps with strict perf budgets should override via
 * PERF_SLO_MS=2000 etc.
 *
 * Filter: `npx playwright test --grep @kind:perf`
 */
import { test, expect } from '@playwright/test'

const SLO_MS = Number(process.env.PERF_SLO_MS ?? 5000)

test.describe.configure({ mode: 'parallel' })
test.describe('Ing — performance test for https://www.ing.nl/particulier', () => {
  test(`@kind:perf @smoke — loads under ${SLO_MS}ms`, async ({ page }) => {
    const start = Date.now()
    await page.goto('/particulier', { waitUntil: 'load' })
    const elapsed = Date.now() - start
    console.log(`load time: ${elapsed}ms (SLO ${SLO_MS}ms)`)
    expect.soft(elapsed, `load took ${elapsed}ms — over SLO ${SLO_MS}ms`).toBeLessThan(SLO_MS)
    // Hard fail at 2x SLO so a deeply broken site still surfaces.
    expect(elapsed).toBeLessThan(SLO_MS * 2)
  })
})
