/**
 * Generated by reviewqa.
 *
 * Keyboard-only navigation for https://gohugo.io/configuration. v0.59 — depth parity:
 * five tests covering the keyboard-accessibility concerns axe-core
 * cannot enforce statically:
 *
 *   smoke           — Tab cycles through the first 10 focusables
 *   focus-indicator — every focusable has a visible focus indicator
 *   escape-dismiss  — Escape closes a modal/dialog and returns focus
 *   enter-space     — Enter activates links/buttons; Space activates buttons
 *   no-trap         — Tab from the last focusable wraps or exits (no trap)
 *
 * Filter: `npx playwright test --grep @kind:keyboard`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('GohugoIo — keyboard navigation @ https://gohugo.io/configuration', () => {
  test('@kind:keyboard @smoke tab through the first 10 focusables', async ({ page }) => {
    await page.goto('/configuration')

    const focusables = await page.locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])').all()
    const max = Math.min(focusables.length, 10)
    let reached = 0

    for (let i = 0; i < max; i++) {
      await page.keyboard.press('Tab')
      const active = await page.evaluate(() => document.activeElement?.tagName.toLowerCase() ?? '')
      if (active && active !== 'body') {
        reached++
      }
    }

    expect.soft(reached, `tab reached only ${reached} of ${max} focusables`).toBeGreaterThanOrEqual(Math.floor(max * 0.7))
  })

  test('@kind:keyboard @focus-indicator first focused element has a visible focus indicator', async ({ page }) => {
    await page.goto('/configuration')
    await page.keyboard.press('Tab')

    const hasIndicator = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement | null
      if (!el || el === document.body) return false
      const cs = getComputedStyle(el)
      return cs.outlineStyle !== 'none' || cs.boxShadow !== 'none'
    })
    expect.soft(hasIndicator, 'first tab-focused element has no visible focus indicator').toBe(true)
  })

  test('@kind:keyboard @escape-dismiss Escape closes a visible dialog and returns focus', async ({ page }) => {
    await page.goto('/configuration')
    // Find a candidate dialog or modal trigger; skip if absent.
    const trigger = page.locator('[aria-haspopup="dialog"], [data-modal-trigger], [aria-controls][aria-expanded]').first()
    if (await trigger.count() === 0) test.skip()
    await trigger.focus()
    await trigger.press('Enter')
    const dialog = page.locator('[role="dialog"], dialog[open], [aria-modal="true"]').first()
    if (await dialog.count() === 0) test.skip()
    await expect(dialog).toBeVisible({ timeout: 3000 }).catch(() => {})
    // Press Escape; the dialog should close AND focus should return
    // (somewhere visible) to the trigger.
    await page.keyboard.press('Escape')
    const stillOpen = await dialog.isVisible().catch(() => false)
    expect.soft(stillOpen, 'dialog should close on Escape').toBe(false)
  })

  test('@kind:keyboard @enter-space Enter activates focused links/buttons', async ({ page }) => {
    await page.goto('/configuration')
    // Find the first interactive control of each type.
    const link = page.locator('a[href]:not([href^="#"]):not([href^="mailto:"]):not([href^="tel:"])').first()
    if (await link.count() === 0) test.skip()
    let activated = false
    page.on('framenavigated', () => { activated = true })
    await link.focus()
    await page.keyboard.press('Enter')
    await page.waitForLoadState('domcontentloaded', { timeout: 5000 }).catch(() => {})
    // Either the navigation happened (activated=true) OR the link
    // explicitly prevented default. What we forbid is "nothing".
    if (!activated) {
      // soft so SPAs that consume the click via JS don't fail —
      // a real navigation would have flipped the flag.
      expect.soft(activated, 'Enter on a focused link produced no observable effect').toBe(true)
    }
  })

  test('@kind:keyboard @no-trap Tab from the last focusable wraps or exits the page', async ({ page }) => {
    // Find the last focusable; Tab once more; confirm focus moved
    // OR landed back on the first focusable (wrap). What we forbid
    // is staying on the same element (a focus trap outside a modal).
    await page.goto('/configuration')
    const focusables = page.locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])')
    const count = await focusables.count()
    if (count < 2) test.skip()
    // Focus the last one explicitly.
    await focusables.nth(count - 1).focus()
    const firstActiveTag = await page.evaluate(() => document.activeElement?.tagName.toLowerCase() ?? '')
    await page.keyboard.press('Tab')
    const secondActiveTag = await page.evaluate(() => document.activeElement?.tagName.toLowerCase() ?? '')
    // A trap means the same exact element stays focused after Tab AND
    // we're not inside aria-modal=true. body=body is fine (exited the
    // focusable set entirely).
    const trapped = await page.evaluate(() => {
      const el = document.activeElement as HTMLElement | null
      if (!el) return false
      const modalAncestor = el.closest('[aria-modal="true"], dialog[open]')
      return !!modalAncestor
    })
    expect.soft(trapped, `Tab past the last focusable should wrap or exit; observed ${firstActiveTag}→${secondActiveTag}`).toBe(false)
  })
})

