/**
 * Generated by reviewqa.
 *
 * Verifies the feature videos page loads within the target time (default 3 seconds, adjustable via PERF_SLO_MS).
 * Measures single-page load latency — not stress testing.
 *
 * Filter: `npx playwright test --grep @kind:perf`
 */
import { test, expect } from '@playwright/test'

const SLO_MS = Number(process.env.PERF_SLO_MS ?? 3000)

test.describe.configure({ mode: 'parallel' })
test.describe('PlaywrightDev — performance @ https://playwright.dev/community/feature-videos', () => {
  test(`@kind:perf @smoke loads under ${SLO_MS}ms`, async ({ page }) => {
    const start = Date.now()
    await page.goto('/community/feature-videos', { waitUntil: 'load' })
    const elapsed = Date.now() - start
    console.log(`load time: ${elapsed}ms (SLO ${SLO_MS}ms)`)
    expect.soft(elapsed, `load took ${elapsed}ms — over SLO ${SLO_MS}ms`).toBeLessThan(SLO_MS)
    // Fails hard at 2x SLO to surface severe failures.
    expect(elapsed).toBeLessThan(SLO_MS * 2)
  })
})

