/**
 * Generated by reviewqa.
 *
 * Progressive Web App smoke for https://gohugo.io/commands. Emitted when probe
 * detected a <link rel="manifest"> reference. Asserts the manifest
 * is reachable, parses as JSON, and contains the required PWA fields
 * (name, start_url, display, icons[]).
 *
 * Filter: `npx playwright test --grep @kind:pwa`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('GohugoIo — PWA manifest @ https://gohugo.io/commands', () => {
  test('@kind:pwa @smoke manifest is reachable and well-formed', async ({ page, request }) => {
    await page.goto('/commands')
    const href = await page.locator('link[rel="manifest"]').first().getAttribute('href')
    if (!href) test.skip()
    const manifestURL = new URL(href!, page.url()).toString()
    const r = await request.get(manifestURL)
    expect(r.ok(), `manifest ${manifestURL} returned ${r.status()}`).toBeTruthy()
    const manifest = await r.json()
    expect.soft(manifest.name || manifest.short_name, 'manifest must declare name or short_name').toBeTruthy()
    expect.soft(manifest.start_url, 'manifest.start_url').toBeTruthy()
    expect.soft(manifest.display, 'manifest.display').toBeTruthy()
    expect.soft(Array.isArray(manifest.icons) && manifest.icons.length > 0, 'manifest.icons[] non-empty').toBe(true)
  })
})

