/**
 * Generated by reviewqa from the live OpenAPI / Swagger document at
 * https://petstore3.swagger.io/user/login. Asserts the endpoint responds with a status code
 * declared in its `responses` block — catches the most common contract
 * violation (a 200 turns into a 500 silently, or a 400 turns into a 204).
 *
 * v0.55 — depth parity with pw_api.tmpl. Today this template emitted
 * one test (status-code match); now it ships 9 — one happy plus eight
 * adversarial blocks (wrong-method, oversized-query, invalid-json,
 * unicode, sqli, xss, null-byte, rapid-burst). Each new block uses
 * `expect.soft()` on body inspection and `expect()` on status-class
 * guarantees, so info-leakage surfaces in the report without failing
 * the whole spec.
 *
 * Schema validation of the response body is intentionally NOT included
 * — that requires a JSON Schema validator and a settled story for
 * `$ref` resolution. Add `ajv` and per-endpoint schema assertions when
 * the contract surface stabilises.
 *
 * Filter: `npx playwright test --grep @kind:contract`
 */
import { test, expect } from '@playwright/test'

const ENDPOINT = 'https://petstore3.swagger.io/user/login'
const METHOD = 'get'.toLowerCase()

const ALLOWED_STATUSES: number[] = [
  200,
  400,
]

// Centralised request helper so every negative block targets the same
// endpoint with the same method, varying only the payload / verb.
async function call(request: any, method: string, opts: any = {}) {
  switch (method.toLowerCase()) {
    case 'post':   return request.post(ENDPOINT,   { failOnStatusCode: false, ...opts })
    case 'put':    return request.put(ENDPOINT,    { failOnStatusCode: false, ...opts })
    case 'patch':  return request.patch(ENDPOINT,  { failOnStatusCode: false, ...opts })
    case 'delete': return request.delete(ENDPOINT, { failOnStatusCode: false, ...opts })
    case 'head':   return request.head(ENDPOINT,   { failOnStatusCode: false, ...opts })
    default:       return request.get(ENDPOINT,    { failOnStatusCode: false, ...opts })
  }
}

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3Swagger — contract @ https://petstore3.swagger.io/user/login', () => {
  test('@kind:contract @smoke response status is one of the declared codes', async ({ request }) => {
    const response = await call(request, METHOD)
    const status = response.status()
    console.log(`${METHOD} ${ENDPOINT} → ${status} (allowed: ${ALLOWED_STATUSES.join(', ')})`)
    // Accept the declared statuses; tolerate sandbox-only authentication
    // gates (401/403) since contract specs run unauthenticated.
    const acceptable = ALLOWED_STATUSES.length === 0
      ? [200, 201, 204, 401, 403]
      : [...ALLOWED_STATUSES, 401, 403]
    expect(acceptable).toContain(status)
  })

  // ─────────────────────────────────────────────────────────────
  // v0.55: 8 adversarial blocks. Path-only — no request-schema is
  // threaded through, so each negative targets the URL plus a
  // generic adversarial payload. The contract: MUST NOT 5xx and
  // MUST NOT leak SQLState / stack traces / verbatim script tags.
  // ─────────────────────────────────────────────────────────────

  test('@kind:contract @negative wrong-method does not 5xx', async ({ request }) => {
    // Substitute an unrelated verb. POST endpoints get probed with
    // DELETE; GET endpoints get probed with POST. Either an explicit
    // 405 (method not allowed) or a 4xx is acceptable — what we
    // forbid is the server crashing on a verb mismatch.
    const alt = METHOD === 'get' ? 'post' : METHOD === 'post' ? 'delete' : 'get'
    const response = await call(request, alt)
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:contract @negative oversized-query does not 5xx', async ({ request }) => {
    // 4000-char query parameter. Server should reject (4xx / 414
    // URI Too Long) or accept; never crash.
    const huge = 'a'.repeat(4000)
    const sep = ENDPOINT.includes('?') ? '&' : '?'
    const response = await call(request, METHOD, { params: { __rq: huge } as any }).catch(async () =>
      // Some request implementations append params via the URL; fall
      // back to manual concatenation.
      await call(request, METHOD, { url: ENDPOINT + sep + '__rq=' + huge } as any)
    )
    if (response) {
      expect.soft(response.status(), `oversized-query → ${response.status()}`).toBeLessThan(500)
    }
  })

  test('@kind:contract @negative invalid-json body does not 5xx', async ({ request }) => {
    // Malformed JSON body. Only meaningful for body-accepting verbs.
    if (METHOD === 'get' || METHOD === 'head' || METHOD === 'delete') test.skip()
    const response = await call(request, METHOD, {
      data: '{ "not_closed":',
      headers: { 'content-type': 'application/json' },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('traceback')
    expect.soft(body.toLowerCase()).not.toContain('stack trace')
  })

  test('@kind:contract @negative unicode body does not 5xx', async ({ request }) => {
    const response = await call(request, METHOD, {
      data: { payload: 'café-niño-用户-🎉' },
      headers: { 'content-type': 'application/json' },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:contract @negative sql-injection-shaped does not 5xx', async ({ request }) => {
    const payload = "'; DROP TABLE users; --"
    const response = await call(request, METHOD, {
      data: { payload },
      headers: { 'content-type': 'application/json' },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body.toLowerCase()).not.toContain('sqlstate')
    expect.soft(body.toLowerCase()).not.toContain('syntax error')
  })

  test('@kind:contract @negative xss-shaped is escaped or rejected', async ({ request }) => {
    const payload = '<script>window.__rqXSS=1</script>'
    const response = await call(request, METHOD, {
      data: { payload },
      headers: { 'content-type': 'application/json' },
    })
    expect(response.status()).toBeLessThan(500)
    const body = await response.text().catch(() => '')
    expect.soft(body).not.toContain('<script>window.__rqXSS=1</script>')
  })

  test('@kind:contract @negative null-byte injection does not 5xx', async ({ request }) => {
    const response = await call(request, METHOD, {
      data: { payload: 'value\x00malicious' },
      headers: { 'content-type': 'application/json' },
    })
    expect(response.status()).toBeLessThan(500)
  })

  test('@kind:contract @negative rapid burst stays healthy or is rate-limited', async ({ request }) => {
    // 10 concurrent identical requests. Either the server rate-limits
    // (429 — fine) or it serves all 10 without 5xx-ing.
    const responses = await Promise.all(
      Array.from({ length: 10 }, () => call(request, METHOD))
    )
    for (const r of responses) {
      expect.soft(r.status(), `burst response status ${r.status()}`).toBeLessThan(500)
    }
  })
})
