/**
 * Generated by reviewqa.
 *
 * Security header smoke for https://www.spritecloud.com. Hits the origin and checks
 * presence of the headers most browsers rely on to enforce baseline
 * web security: HSTS, CSP, X-Frame-Options (or CSP frame-ancestors),
 * X-Content-Type-Options, Referrer-Policy.
 *
 * Soft assertions — a missing header surfaces in the report without
 * cascading the rest of the suite. The hard assertion is "we got SOME
 * response at all".
 *
 * Filter: `npx playwright test --grep @kind:security`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Security headers for www.spritecloud.com', () => {
  test('Baseline security headers are present', async ({ request }) => {
    const response = await request.get('https://www.spritecloud.com')
    expect(response.status(), origin should respond).toBeLessThan(500)
    const headers = response.headers()

    expect.soft(headers['strict-transport-security'], HSTS header is missing).toBeTruthy()
    const csp = headers['content-security-policy'] || ''
    expect.soft(csp, Content-Security-Policy header is missing).toBeTruthy()
    const xfo = headers['x-frame-options']
    const cspFrameAncestors = /frame-ancestors/i.test(csp)
    expect.soft(xfo || cspFrameAncestors, Missing clickjacking protection (X-Frame-Options or CSP frame-ancestors)).toBeTruthy()
    expect.soft(headers['x-content-type-options'], X-Content-Type-Options header is missing or incorrect).toBe('nosniff')
    expect.soft(headers['referrer-policy'], Referrer-Policy header is missing).toBeTruthy()
  })
})
