/**
 * Generated by reviewqa.
 *
 * HTTP error / redirect chains baseline for https://petstore3.swagger.io. Asserts the
 * site handles long redirect chains (3xx → 3xx → 200), 4xx 'gone'
 * responses, and 5xx with Retry-After without blowing up. These
 * shapes appear in production and rarely have direct test coverage.
 *
 * Filter: `npx playwright test --grep @kind:http-chain`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3SwaggerIo — http chains @ https://petstore3.swagger.io', () => {
  test('@kind:http-chain @redirect-chain follows multi-hop redirects', async ({ request }) => {
    // 301 + 302 + 200 — the common cdn → canonical → asset chain.
    const resp = await request.get('/', { maxRedirects: 10 })
    expect(resp.ok()).toBeTruthy()
    // At most we tolerate 5 hops; more usually signals a loop.
    const hops = resp.request().redirectedFrom() ? 1 : 0 // crude
    expect.soft(hops, `unexpectedly many redirect hops`).toBeLessThanOrEqual(5)
  })

  test('@kind:http-chain @410 nonexistent paths return a friendly error', async ({ request }) => {
    const resp = await request.get('/__reviewqa_does_not_exist__', { failOnStatusCode: false })
    expect(resp.status()).toBeGreaterThanOrEqual(400)
    expect(resp.status()).toBeLessThan(600)
    // The body should not be a stack trace or framework default.
    const body = await resp.text()
    expect.soft(body.toLowerCase()).not.toContain('traceback')
    expect.soft(body.toLowerCase()).not.toContain('stack trace')
  })

  test('@kind:http-chain @429 server-side rate-limit response shape', async ({ context, page }) => {
    let firstCall = true
    await context.route('**/*', async route => {
      if (firstCall && route.request().url().endsWith('/'.replace(/^\//, ''))) {
        firstCall = false
        return route.continue()
      }
      // Stub: 429 with Retry-After.
      await route.fulfill({ status: 429, headers: { 'Retry-After': '2' }, body: '' })
    })
    await page.goto('/', { waitUntil: 'domcontentloaded' })
    // The initial document loaded; downstream rate-limits did NOT
    // crash the page.
    await expect(page).toHaveURL(/.+/)
  })
})

