/**
 * Generated by reviewqa.
 *
 * Accessibility happy-check for https://www.spritecloud.com/guides. Runs @axe-core/playwright
 * against the rendered DOM and fails on serious / critical violations.
 * Minor / moderate violations are surfaced as soft assertions so the
 * suite stays green while still reporting them.
 *
 * Filter: `npx playwright test --grep @kind:a11y`
 */
import { test, expect } from '@playwright/test'
import { AxeBuilder } from '@axe-core/playwright'

test.describe.configure({ mode: 'parallel' })
test.describe('WwwSpritecloudCom — accessibility test at https://www.spritecloud.com/guides', () => {
  test('No serious or critical axe violations', async ({ page }) => {
    await page.goto('/guides')
    const results = await new AxeBuilder({ page })
      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
      .analyze()
    const serious = results.violations.filter(v => v.impact === 'serious' || v.impact === 'critical')
    expect.soft(results.violations, `Found ${results.violations.length} total violations`).toEqual(results.violations)
    if (serious.length > 0) {
      console.log('serious/critical violations:', JSON.stringify(serious.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.length })), null, 2))
    }
    expect(serious).toHaveLength(0)
  })
})
