/**
 * Generated by reviewqa.
 *
 * Accessibility landmark structure for https://www.spritecloud.com/cybersecurity. v0.59 — depth
 * parity. Five tests covering the structural a11y concerns the
 * baseline axe scan does NOT enforce:
 *
 *   smoke               — single <main>, single <h1>, ≥1 <nav>
 *   no-aria-hidden      — no focusables inside aria-hidden subtrees
 *   heading-hierarchy   — heading order is sequential (no h1→h3 jumps)
 *   landmark-names      — duplicate landmarks carry accessible names
 *   skip-link           — "skip to content" link present (WCAG 2.4.1)
 *
 * Filter: `npx playwright test --grep @kind:a11y-landmarks`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Spritecloud — a11y landmarks @ https://www.spritecloud.com/cybersecurity', () => {
  test('@kind:a11y-landmarks @smoke single main + h1 + nav', async ({ page }) => {
    await page.goto('/cybersecurity')

    const mains = await page.locator('main, [role="main"]').count()
    expect.soft(mains, `expected exactly one <main> region`).toBe(1)

    const h1s = await page.locator('h1').count()
    expect.soft(h1s, `expected exactly one <h1>`).toBe(1)

    const navs = await page.locator('nav, [role="navigation"]').count()
    expect.soft(navs, `expected at least one <nav> region`).toBeGreaterThanOrEqual(1)
  })

  test('@kind:a11y-landmarks @negative no focusables inside aria-hidden', async ({ page }) => {
    await page.goto('/cybersecurity')
    const hiddenFocusables = await page.locator('[aria-hidden="true"]').locator('a, button, input, select, textarea, [tabindex]:not([tabindex="-1"])').count()
    expect.soft(hiddenFocusables, `${hiddenFocusables} focusable elements inside aria-hidden — confusing for screen readers`).toBe(0)
  })

  test('@kind:a11y-landmarks @heading-hierarchy heading order is sequential', async ({ page }) => {
    // Walk every heading in source order. A jump from h1 to h3 (skipping
    // h2) breaks screen-reader navigation. h2 to h4 is the same bug at
    // the next level.
    await page.goto('/cybersecurity')
    const jumps = await page.evaluate(() => {
      const headings = Array.from(document.querySelectorAll('h1,h2,h3,h4,h5,h6'))
      const levels = headings.map(h => parseInt(h.tagName.slice(1), 10))
      const issues: string[] = []
      let prev = 0
      for (let i = 0; i < levels.length; i++) {
        const cur = levels[i]
        if (prev > 0 && cur > prev + 1) {
          issues.push(`h${prev} → h${cur} skip at index ${i}: "${headings[i].textContent?.slice(0, 60) ?? ''}"`)
        }
        prev = cur
      }
      return issues
    })
    if (jumps.length > 0) {
      console.log('heading hierarchy jumps:', jumps)
    }
    expect.soft(jumps, `${jumps.length} heading-hierarchy jump(s)`).toEqual([])
  })

  test('@kind:a11y-landmarks @landmark-names duplicate landmarks have accessible names', async ({ page }) => {
    // When ≥2 navs / asides / sections exist, each must carry an
    // accessible name (aria-label, aria-labelledby, or an inner
    // <h2-6>) so screen-reader users can distinguish them.
    await page.goto('/cybersecurity')
    const unnamed = await page.evaluate(() => {
      const kinds = ['nav', 'aside', 'section']
      const issues: string[] = []
      for (const kind of kinds) {
        const els = Array.from(document.querySelectorAll(kind))
        if (els.length < 2) continue
        els.forEach((el, idx) => {
          const hasAriaLabel = !!el.getAttribute('aria-label')?.trim()
          const hasAriaLabelledBy = !!el.getAttribute('aria-labelledby')?.trim()
          const hasInnerHeading = !!el.querySelector('h1, h2, h3, h4, h5, h6')
          if (!hasAriaLabel && !hasAriaLabelledBy && !hasInnerHeading) {
            issues.push(`${kind}[${idx}] has no accessible name`)
          }
        })
      }
      return issues
    })
    if (unnamed.length > 0) {
      console.log('unnamed-landmark issues:', unnamed)
    }
    expect.soft(unnamed, `${unnamed.length} duplicate landmark(s) without an accessible name`).toEqual([])
  })

  test('@kind:a11y-landmarks @skip-link "skip to content" affordance present (WCAG 2.4.1)', async ({ page }) => {
    // The first focusable should either be a skip link OR there must
    // be an in-page anchor to #main / #content / [role=main]. WCAG
    // 2.4.1 ("Bypass Blocks") requires it for keyboard / SR users.
    await page.goto('/cybersecurity')
    const hasSkipLink = await page.evaluate(() => {
      const candidates = Array.from(document.querySelectorAll('a[href^="#"]'))
      return candidates.some(a => {
        const text = (a.textContent || '').toLowerCase()
        const href = a.getAttribute('href') || ''
        return /skip|jump|main content/.test(text) ||
               href === '#main' || href === '#content' ||
               !!document.querySelector(`${href}[role="main"], ${href}#main, main${href}`)
      })
    })
    expect.soft(hasSkipLink, 'no "skip to content" link found — WCAG 2.4.1 violation').toBe(true)
  })
})

