// Generated by reviewqa. Review and extend with edge cases.
package plan

import (
	"testing"
	"reflect"
)

func TestPageTitle(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		got := PageTitle(nil)
		if reflect.DeepEqual(got, *new(string)) {
			t.Fatalf("got zero value: %#v", got)
		}
	})

	t.Run("returns expected type", func(t *testing.T) {
		got := PageTitle(nil)
		if got, want := reflect.TypeOf(got), reflect.TypeOf(*new(string)); got != want {
			t.Fatalf("type = %v, want %v", got, want)
		}
	})
}
