/**
 * Generated by quail. Fuzz spec for https://playwright.dev/docs/intro.
 *
 * Bounded negative-coverage: each text input + interactive component on
 * this page gets exercised with edge-case payloads (empty, very long,
 * special chars) to surface input-handling bugs the happy-path specs
 * skip over. Capped at 5 emissions per page so triage stays tractable.
 *
 * Filter: `npx playwright test --grep @fuzz`
 */
import { test, expect } from './_fixtures'

test.describe.configure({ mode: 'parallel' })
test.describe('Playwright — fuzz / negative input', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/docs/intro')
  })

  test('@fuzz @keyboard tab (npm) responds to Tab + Enter', async ({ page }) => {
    // Tab through the page looking for the trigger, then activate via
    // keyboard. Catches focus-trap and missing-keyboard-handler bugs
    // that mouse-only tests miss.
    const target = page.getByRole('tab', { name: /npm/i }).first()
    await target.focus()
    await page.keyboard.press('Enter')
    // No assertion on resulting state — interactions vary by kind.
    // The pageErrors fixture catches any uncaught JS the keyboard
    // path triggered.
    await expect(target).toBeAttached()
  })

  test('@fuzz @keyboard tab (yarn) responds to Tab + Enter', async ({ page }) => {
    // Tab through the page looking for the trigger, then activate via
    // keyboard. Catches focus-trap and missing-keyboard-handler bugs
    // that mouse-only tests miss.
    const target = page.getByRole('tab', { name: /yarn/i }).first()
    await target.focus()
    await page.keyboard.press('Enter')
    // No assertion on resulting state — interactions vary by kind.
    // The pageErrors fixture catches any uncaught JS the keyboard
    // path triggered.
    await expect(target).toBeAttached()
  })
})

