/**
 * Generated by reviewqa.
 *
 * Idempotency contract for PUT https://petstore3.swagger.io/pet.
 * Calls the endpoint twice with the same payload and asserts the second
 * call returns a 2xx or 204 — the textbook behaviour for an idempotent
 * verb. A 4xx on the second call signals the endpoint isn't actually
 * idempotent.
 *
 * Filter: `npx playwright test --grep @kind:api-idempotency`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3SwaggerIo — idempotency @ https://petstore3.swagger.io/pet', () => {
  test('@kind:api-idempotency @smoke same PUT twice → second call still succeeds', async ({ request }) => {
    const body = {
      '404': '404-value',
      '422': '422-value',
      '200': '200-value',
      '400': '400-value',
    }
    const first = await request.put('https://petstore3.swagger.io/pet', { form: body })
    expect(first.status(), 'first call should succeed').toBeLessThan(400)

    const second = await request.put('https://petstore3.swagger.io/pet', { form: body })
    // Acceptable on the second call: 2xx (same response), 204 (no
    // content), or 304 (not modified). NOT acceptable: 4xx, 5xx.
    expect.soft(second.status(), `second call ${second.status()} — endpoint may not be idempotent`).toBeLessThan(400)
  })
})

