// Generated by quail. Playwright configuration with sensible defaults
// for the suite quail just probed. `baseURL` defaults to the origin
// quail probed; override with `BASE_URL=...` to point the same suite
// at staging, a PR preview, or localhost.
//
// playwright-bdd is wired in: .feature files under tests/e2e/features/
// become the executable contract via step definitions in
// tests/e2e/steps/. Plain Playwright TS specs (api/*.api.spec.ts,
// *-fuzz.spec.ts, and the v0.22 quality specs under a11y/responsive/
// perf/security/health/observability/contract/i18n) still run alongside
// them as additional projects.
//
// QUAIL_BROWSERS env opts you in/out of cross-browser runs:
//   chromium-only (default in CI)   → QUAIL_BROWSERS=chromium
//   add firefox + webkit            → QUAIL_BROWSERS=chromium,firefox,webkit
//
// Edit freely — the next probe run will not overwrite this file.
import { defineConfig, devices } from '@playwright/test'
import { defineBddConfig } from 'playwright-bdd'

const BASE_URL = process.env.BASE_URL ?? 'https://playwright.dev'

const BROWSERS = (process.env.QUAIL_BROWSERS ?? 'chromium')
  .split(',')
  .map(s => s.trim().toLowerCase())
  .filter(Boolean)

const bddTestDir = defineBddConfig({
  features: 'tests/e2e/features/*.feature',
  steps: 'tests/e2e/steps/*.ts',
})

const extrasTestMatch = /\.(api|fuzz|a11y|responsive|perf|security|health|observability|contract|i18n|visual|visual-states|keyboard|landmarks|zoom|prefs|network|storage|print|race|clipboard|http-chains|file-upload|iframe|date-edges|pwa|history-depth|touch|dragdrop|auth-expiry|locale-switch|graphql|webhook|mobile|deeplink|integration(-(db|broker|cache|storage|search|auth|obs))?)\.spec\.ts$/

function projectsForBrowser(browser: 'chromium' | 'firefox' | 'webkit') {
  const deviceProfile =
    browser === 'firefox' ? devices['Desktop Firefox'] :
    browser === 'webkit'  ? devices['Desktop Safari']  :
                            devices['Desktop Chrome']
  return [
    { name: `bdd-${browser}`,    testDir: bddTestDir, use: { ...deviceProfile } },
    { name: `extras-${browser}`, testDir: './tests/e2e', testMatch: extrasTestMatch, use: { ...deviceProfile } },
  ]
}

export default defineConfig({
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: process.env.CI ? [['html', { open: 'never' }], ['list']] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    actionTimeout: 10_000,
    navigationTimeout: 20_000,
  },
  projects: BROWSERS
    .filter((b): b is 'chromium' | 'firefox' | 'webkit' =>
      b === 'chromium' || b === 'firefox' || b === 'webkit')
    .flatMap(projectsForBrowser),
})

