/**
 * Generated by reviewqa.
 *
 * Security header smoke for https://petstore3.swagger.io. Hits the origin and checks
 * presence of the headers most browsers rely on to enforce baseline
 * web security: HSTS, CSP, X-Frame-Options (or CSP frame-ancestors),
 * X-Content-Type-Options, Referrer-Policy.
 *
 * Soft assertions — a missing header surfaces in the report without
 * cascading the rest of the suite. The hard assertion is "we got SOME
 * response at all".
 *
 * Filter: `npx playwright test --grep @kind:security`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('Petstore3SwaggerIo — security headers @ https://petstore3.swagger.io', () => {
  test('@kind:security @smoke baseline security headers present', async ({ request }) => {
    const response = await request.get('https://petstore3.swagger.io')
    expect(response.status(), 'origin should respond').toBeLessThan(500)
    const headers = response.headers()

    expect.soft(headers['strict-transport-security'], 'HSTS not set').toBeTruthy()
    const csp = headers['content-security-policy'] || ''
    expect.soft(csp, 'Content-Security-Policy not set').toBeTruthy()
    const xfo = headers['x-frame-options']
    const cspFrameAncestors = /frame-ancestors/i.test(csp)
    expect.soft(xfo || cspFrameAncestors, 'no clickjacking protection (X-Frame-Options or CSP frame-ancestors)').toBeTruthy()
    expect.soft(headers['x-content-type-options'], 'X-Content-Type-Options not set').toBe('nosniff')
    expect.soft(headers['referrer-policy'], 'Referrer-Policy not set').toBeTruthy()
  })
})

