package composer

import "testing"

// v0.92: the bug from the user's UI Run screenshot — a humanized
// step value with nested unescaped quotes makes Gherkin parse the
// step with the wrong {string} count, no step-def binds, bddgen
// aborts. IsGherkinSafe must catch this exact shape.
func TestIsGherkinSafe_RejectsNestedQuotesInValue(t *testing.T) {
	body := []byte(`# Generated by quail.

Feature: Ing — contact journey

  Scenario: user navigates through the site
    Given I open the landing page
    When I enter "she said "hello" & 'goodbye'" into the "Typ hier wat je wil vinden" field
    Then no error message is shown in the form region
`)
	if IsGherkinSafe(body) {
		t.Errorf("expected nested-quote step to be unsafe; got safe")
	}
}

func TestIsGherkinSafe_AcceptsCleanDeterministic(t *testing.T) {
	body := []byte(`# Generated by quail.

Feature: Ing — contact journey

  Scenario: user submits the contact form
    Given I open the landing page
    When I enter "test query" into the "Typ hier wat je wil vinden" field
    And I submit the form
    Then no error message is shown in the form region
`)
	if !IsGherkinSafe(body) {
		t.Errorf("expected clean deterministic Gherkin to be safe; got unsafe")
	}
}

// And / But / asterisk continuations must all be checked, not just
// Given/When/Then.
func TestIsGherkinSafe_HandlesAllStepKeywords(t *testing.T) {
	body := []byte(`Feature: x

  Scenario: y
    Given I open the landing page
    And I open the menu
    But no error message is shown in the form region
    * I close the menu
`)
	if !IsGherkinSafe(body) {
		t.Errorf("expected all-keyword sample to be safe; got unsafe")
	}
}

// Non-step lines (Feature:, Scenario:, comments, tags, blank lines)
// must NOT be checked — they're not step text. A funky title doesn't
// invalidate the file.
func TestIsGherkinSafe_IgnoresNonStepLines(t *testing.T) {
	body := []byte(`# A "comment" with "weird" quotes: not a problem.

Feature: Title "with quotes" inside

  @smoke @journey:contact
  Scenario: Scenario name with "embedded" quotes
    Given I open the landing page
`)
	if !IsGherkinSafe(body) {
		t.Errorf("non-step lines should not affect safety; got unsafe")
	}
}

func TestLooksLikeFeatureFile_True(t *testing.T) {
	body := []byte(`# Generated by quail.

Feature: Something

  Scenario: x
`)
	if !LooksLikeFeatureFile(body) {
		t.Errorf("expected file with Feature: header to be detected")
	}
}

func TestLooksLikeFeatureFile_FalseOnTsContent(t *testing.T) {
	body := []byte(`import { test, expect } from '@playwright/test'

test('something', async ({ page }) => {
  await page.goto('https://example.com')
})
`)
	if LooksLikeFeatureFile(body) {
		t.Errorf("expected .ts content to not be detected as feature")
	}
}
