package composer

import (
	"bufio"
	"bytes"
	"strings"
)

// IsGherkinSafe validates that every Given/When/Then/And/But step in
// a rendered .feature file matches the registered step-def
// vocabulary. Lines outside step keywords (Feature:, Scenario:,
// comments, tags, blank lines) pass through unchanged.
//
// The humanize pass can rewrite arbitrary substrings inside a
// generated file. For .ts test files, the structurePreserved guard
// catches semantic damage. For .feature files there's no such guard
// — the LLM can rewrite a step value to include nested unescaped
// quotes, which Gherkin's parser then splits into the wrong number
// of {string} placeholders, and bddgen aborts with "Missing step
// definitions". This function is the defense: call it post-humanize
// on .feature content; reject the rewrite if it returns false.
//
// v0.92.
func IsGherkinSafe(content []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64<<10), 1<<20)
	for scanner.Scan() {
		raw := scanner.Text()
		trimmed := strings.TrimSpace(raw)
		body, ok := stripGherkinKeyword(trimmed)
		if !ok {
			continue
		}
		if !matchesRegisteredPattern(body) {
			return false
		}
	}
	return true
}

// stripGherkinKeyword returns the step body when the line starts
// with a Gherkin step keyword. Comparing the body against the
// registered-pattern set lets us reuse the composer's vocabulary
// regex set rather than maintaining a parallel one.
//
// Returns (body, true) when the line is a step; (raw, false)
// otherwise. Recognises Given/When/Then/And/But/* with the optional
// trailing space.
func stripGherkinKeyword(line string) (string, bool) {
	for _, kw := range []string{"Given ", "When ", "Then ", "And ", "But ", "* "} {
		if strings.HasPrefix(line, kw) {
			return strings.TrimSpace(line[len(kw):]), true
		}
	}
	return line, false
}

// LooksLikeFeatureFile sniffs whether a rendered file is Gherkin so
// the humanize layer can route .feature content through the
// Gherkin-safe gate.
func LooksLikeFeatureFile(content []byte) bool {
	// Cheap shape check: scan the first ~50 lines for a Feature:
	// header. Generated files start with a `# Generated by reviewqa.`
	// comment block, so the Feature: line isn't at line 1.
	scanner := bufio.NewScanner(bytes.NewReader(content))
	scanner.Buffer(make([]byte, 0, 64<<10), 1<<20)
	for i := 0; i < 50 && scanner.Scan(); i++ {
		t := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(t, "Feature:") {
			return true
		}
	}
	return false
}
