/**
 * Generated by reviewqa.
 *
 * Integration-layer DB SCAFFOLD for https://playwright.dev. Emitted when the
 * probe detected ORM-shaped response payloads (id / createdAt /
 * updatedAt fields, or a Set-Cookie carrying a session id). This
 * file is intentionally `test.skip()` until the consumer wires a
 * real backing database via `reviewqa.yml`.
 *
 * To activate:
 *   1. Declare a `database:` block in reviewqa.yml (driver, image,
 *      schema initialisation script).
 *   2. Re-run `reviewqa generate`. reviewqa will replace this stub
 *      with the matching integration_db spec backed by
 *      Testcontainers.
 *
 * Filter: `npx playwright test --grep @kind:integration-db`
 */
import { test, expect } from '@playwright/test'

test.describe('PlaywrightDev — integration DB scaffold (skipped)', () => {
  test.skip('integration DB: round-trip (create, insert, select, delete)', async ({ request }) => {
    // When wired this test would:
    //   1. Start a Testcontainers DB instance (postgres / mysql / mariadb)
    //   2. Apply the schema declared in reviewqa.yml
    //   3. POST to https://playwright.dev, then SELECT to confirm the row landed
    //   4. DELETE via API or SQL, confirm SELECT returns 0
    //   5. Tear down the container
    const r = await request.get('/')
    expect(r.ok()).toBeTruthy()
  })

  test.skip('integration DB: transaction rolls back on error', async ({ request }) => {
    // When wired:
    //   1. Begin transaction
    //   2. POST with one valid + one invalid record
    //   3. Confirm no rows committed (full rollback)
    //   4. Confirm DB pool returned to idle
    const r = await request.get('/')
    expect(r.ok()).toBeTruthy()
  })

  test.skip('integration DB: concurrent requests do not exhaust the connection pool', async ({ request }) => {
    // When wired:
    //   1. Issue N concurrent reads where N > pool.max
    //   2. Confirm all N return < 500
    //   3. Confirm pool.metrics.waiting drops to 0 within 30s
    const r = await request.get('/')
    expect(r.ok()).toBeTruthy()
  })
})

