// Generated by reviewqa. Review and extend with edge cases.
package integration

import (
	"testing"
	"reflect"
)

func TestIsEmpty(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		got := IsEmpty()
		if reflect.DeepEqual(got, *new(bool)) {
			t.Fatalf("got zero value: %#v", got)
		}
	})

	t.Run("returns expected type", func(t *testing.T) {
		got := IsEmpty()
		if got, want := reflect.TypeOf(got), reflect.TypeOf(*new(bool)); got != want {
			t.Fatalf("type = %v, want %v", got, want)
		}
	})
}
