// Generated by reviewqa. Review and extend with edge cases.
package integration

import (
	"testing"
	"reflect"
)

func TestEmitItems(t *testing.T) {
	t.Run("happy path", func(t *testing.T) {
		got := EmitItems(nil)
		if reflect.DeepEqual(got, *new([]plan.Item)) {
			t.Fatalf("got zero value: %#v", got)
		}
	})

	t.Run("returns expected type", func(t *testing.T) {
		got := EmitItems(nil)
		if got, want := reflect.TypeOf(got), reflect.TypeOf(*new([]plan.Item)); got != want {
			t.Fatalf("type = %v, want %v", got, want)
		}
	})
}
