/**
 * Generated by reviewqa.
 *
 * Health / readiness probe smoke for https://books.toscrape.com. Hits the well-known
 * health endpoints and asserts at least one responds 2xx. Sites that
 * expose none of them produce a soft warning — the spec doesn't fail
 * because not having a health endpoint is a valid choice.
 *
 * Filter: `npx playwright test --grep @kind:health`
 */
import { test, expect } from '@playwright/test'

const HEALTH_PATHS = ['/health', '/healthz', '/ready', '/readyz', '/status', '/livez']

test.describe.configure({ mode: 'parallel' })
test.describe('BooksToscrape — health probes @ https://books.toscrape.com', () => {
  test('@kind:health @smoke at least one well-known health endpoint responds', async ({ request }) => {
    const results: Array<{ path: string; status: number }> = []
    for (const path of HEALTH_PATHS) {
      try {
        const url = new URL(path, 'https://books.toscrape.com').toString()
        const r = await request.get(url, { timeout: 5_000, maxRedirects: 0 })
        results.push({ path, status: r.status() })
      } catch (e) {
        results.push({ path, status: -1 })
      }
    }
    console.log('health probe results:', results)
    const anyHealthy = results.some(r => r.status >= 200 && r.status < 300)
    if (!anyHealthy) {
      console.log('no well-known health endpoint responded 2xx — consider exposing /health or /healthz')
    }
    expect.soft(anyHealthy, 'no health endpoint responded 2xx').toBe(true)
    // Hard fail only when EVERY probe errored (network down) — a 404 is
    // a perfectly valid response.
    const allErrored = results.every(r => r.status === -1)
    expect(allErrored, 'all health probes errored — origin unreachable?').toBe(false)
  })
})

