/**
 * Generated by reviewqa.
 *
 * Integration-layer AUTH SCAFFOLD for https://gohugo.io. Emitted when the
 * probe observed WWW-Authenticate or required Authorization headers
 * on at least one response. Skipped until the consumer declares an
 * auth provider in reviewqa.yml.
 *
 * To activate:
 *   1. Declare an `auth:` block in reviewqa.yml (kind: oauth2 / oidc /
 *      basic; issuer; client_id; scopes).
 *   2. Set REVIEWQA_AUTH_TOKEN at runtime, OR declare a token-mint
 *      strategy.
 *   3. Re-run `reviewqa generate`.
 *
 * Filter: `npx playwright test --grep @kind:integration-auth`
 */
import { test, expect } from '@playwright/test'

test.describe('GohugoIo — integration: auth scaffold (skipped)', () => {
  test.skip('@kind:integration-auth @wireable @unauth missing Authorization returns 401', async ({ request }) => {
    // When wired:
    //   1. Probe a protected endpoint without Authorization
    //   2. Confirm 401 (not 403) — 401 signals "needs auth" properly
    //   3. Confirm WWW-Authenticate header points at the issuer
    const r = await request.get('/', { failOnStatusCode: false })
    expect.soft(r.status()).toBe(401)
  })

  test.skip('@kind:integration-auth @wireable @valid-token Authorization with valid token returns 2xx', async ({ request }) => {
    // When wired:
    //   1. Mint a token (or read REVIEWQA_AUTH_TOKEN)
    //   2. Request with Authorization: Bearer <token>
    //   3. Confirm 2xx response shape includes the expected resource
    const token = process.env.REVIEWQA_AUTH_TOKEN || ''
    if (!token) test.skip()
    const r = await request.get('/', {
      headers: { Authorization: `Bearer ${token}` },
    })
    expect(r.ok()).toBeTruthy()
  })

  test.skip('@kind:integration-auth @wireable @expired expired-token Authorization is rejected', async ({ request }) => {
    // When wired:
    //   1. Mint a token with exp in the past, OR use an obviously bad
    //      token from REVIEWQA_AUTH_TOKEN_EXPIRED
    //   2. Request → expect 401 (NOT 200; NOT 5xx)
    //   3. Confirm response body does NOT echo the token
    const r = await request.get('/', {
      headers: { Authorization: 'Bearer expired.token.placeholder' },
      failOnStatusCode: false,
    })
    expect.soft(r.status()).toBe(401)
    const body = await r.text().catch(() => '')
    expect.soft(body).not.toContain('expired.token.placeholder')
  })
})

