/**
 * Generated by reviewqa.
 *
 * Storage resilience for https://es.wikipedia.org/wiki/Wikipedia:Portada. Asserts the page handles
 * corrupt or absent localStorage / sessionStorage / cookies without
 * blank-screening. Storage-corruption bugs are a frequent cause of
 * "works on my machine" support tickets — covering them deterministic-
 * ally lifts production reliability.
 *
 * Filter: `npx playwright test --grep @kind:storage`
 */
import { test, expect } from '@playwright/test'

test.describe.configure({ mode: 'parallel' })
test.describe('EsWikipedia — storage resilience @ https://es.wikipedia.org/wiki/Wikipedia:Portada', () => {
  test('@kind:storage @smoke renders with empty storage', async ({ page, context }) => {
    await context.clearCookies()
    await page.goto('/wiki/Wikipedia:Portada')
    await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear() } catch {} })
    await page.reload()
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })

  test('@kind:storage @corrupt page survives garbage in storage', async ({ page }) => {
    await page.goto('/wiki/Wikipedia:Portada')
    await page.evaluate(() => {
      try {
        localStorage.setItem('user', '{not_json_at_all}')
        sessionStorage.setItem('theme', '\x00\x01\x02')
      } catch {}
    })
    await page.reload()
    // Page should still render — a JSON.parse exception on app boot
    // surfaces here as a missing h1.
    await expect(page.locator('h1, [role="heading"][aria-level="1"]').first()).toBeVisible()
  })
})

